"""A bank of tool definitions used to pad every ToolACE-style prompt to a realistic
catalogue size.

Real function-calling prompts advertise several tools, only one of which gets
called, which is most of why those conversations run to 600+ tokens. Distractors
are drawn from one shared bank for both classes so catalogue length and content
never correlate with the label.
"""

BANK = [
 {"name":"search_web","description":"Run a web search and return ranked results with titles and snippets.","parameters":{"type":"object","properties":{"query":{"type":"string","description":"The search query."},"num_results":{"type":"integer","description":"How many results to return."},"recency_days":{"type":"integer","description":"Restrict to results newer than this many days."}},"required":["query"]}},
 {"name":"send_email","description":"Send an email on behalf of the signed-in user.","parameters":{"type":"object","properties":{"to":{"type":"array","items":{"type":"string"},"description":"Recipient addresses."},"subject":{"type":"string","description":"Subject line."},"body":{"type":"string","description":"Plain text body."},"cc":{"type":"array","items":{"type":"string"},"description":"Carbon copy addresses."}},"required":["to","subject","body"]}},
 {"name":"create_calendar_event","description":"Create an event on the user's calendar and optionally invite attendees.","parameters":{"type":"object","properties":{"title":{"type":"string","description":"Event title."},"start":{"type":"string","description":"ISO 8601 start time."},"duration_minutes":{"type":"integer","description":"Length of the event."},"attendees":{"type":"array","items":{"type":"string"},"description":"Invitee email addresses."},"location":{"type":"string","description":"Room or address."}},"required":["title","start","duration_minutes"]}},
 {"name":"query_database","description":"Run a read-only SQL query against the analytics warehouse.","parameters":{"type":"object","properties":{"sql":{"type":"string","description":"A SELECT statement."},"warehouse":{"type":"string","description":"Warehouse name."},"row_limit":{"type":"integer","description":"Maximum rows to return."}},"required":["sql"]}},
 {"name":"get_directions","description":"Return turn-by-turn directions between two places.","parameters":{"type":"object","properties":{"origin":{"type":"string","description":"Start address or place name."},"destination":{"type":"string","description":"End address or place name."},"mode":{"type":"string","enum":["driving","walking","transit","cycling"],"description":"Travel mode."},"depart_at":{"type":"string","description":"ISO 8601 departure time."}},"required":["origin","destination"]}},
 {"name":"list_files","description":"List files in a directory of the connected drive.","parameters":{"type":"object","properties":{"path":{"type":"string","description":"Directory path."},"pattern":{"type":"string","description":"Optional glob filter."},"recursive":{"type":"boolean","description":"Whether to descend into subdirectories."}},"required":["path"]}},
 {"name":"summarize_document","description":"Produce an extractive or abstractive summary of a stored document.","parameters":{"type":"object","properties":{"document_id":{"type":"string","description":"Identifier of the stored document."},"style":{"type":"string","enum":["bullets","paragraph","executive"],"description":"Summary style."},"max_words":{"type":"integer","description":"Upper bound on summary length."}},"required":["document_id"]}},
 {"name":"get_stock_quote","description":"Fetch the latest quote and daily change for a ticker.","parameters":{"type":"object","properties":{"symbol":{"type":"string","description":"Ticker symbol."},"exchange":{"type":"string","description":"Exchange code, defaults to primary listing."}},"required":["symbol"]}},
 {"name":"translate_document","description":"Translate a document between languages, preserving formatting.","parameters":{"type":"object","properties":{"document_id":{"type":"string","description":"Identifier of the stored document."},"source_language":{"type":"string","description":"ISO code of the source language."},"target_language":{"type":"string","description":"ISO code of the target language."},"formality":{"type":"string","enum":["default","more","less"],"description":"Register to aim for."}},"required":["document_id","target_language"]}},
 {"name":"create_ticket","description":"Open a ticket in the issue tracker.","parameters":{"type":"object","properties":{"project":{"type":"string","description":"Project key."},"title":{"type":"string","description":"Short summary."},"description":{"type":"string","description":"Full description."},"priority":{"type":"string","enum":["low","normal","high","urgent"],"description":"Triage priority."},"assignee":{"type":"string","description":"Username to assign to."}},"required":["project","title"]}},
 {"name":"get_user_profile","description":"Return the profile record for a user id.","parameters":{"type":"object","properties":{"user_id":{"type":"string","description":"Internal user identifier."},"include_preferences":{"type":"boolean","description":"Whether to include stored preferences."}},"required":["user_id"]}},
 {"name":"post_message","description":"Post a message into a chat channel.","parameters":{"type":"object","properties":{"channel":{"type":"string","description":"Channel name or id."},"text":{"type":"string","description":"Message body, markdown allowed."},"thread_ts":{"type":"string","description":"Timestamp of a thread to reply into."}},"required":["channel","text"]}},
 {"name":"generate_report","description":"Render a saved report template with the given parameters.","parameters":{"type":"object","properties":{"template_id":{"type":"string","description":"Report template identifier."},"period_start":{"type":"string","description":"ISO date."},"period_end":{"type":"string","description":"ISO date."},"format":{"type":"string","enum":["pdf","xlsx","html"],"description":"Output format."}},"required":["template_id","period_start","period_end"]}},
 {"name":"lookup_address","description":"Validate and normalise a postal address.","parameters":{"type":"object","properties":{"line1":{"type":"string","description":"First address line."},"postcode":{"type":"string","description":"Postal or ZIP code."},"country":{"type":"string","description":"ISO country code."}},"required":["line1","country"]}},
 {"name":"set_reminder","description":"Set a reminder for the user at a given time.","parameters":{"type":"object","properties":{"text":{"type":"string","description":"What to remind about."},"when":{"type":"string","description":"ISO 8601 time or natural language."},"repeat":{"type":"string","enum":["none","daily","weekly","monthly"],"description":"Recurrence."}},"required":["text","when"]}},
 {"name":"get_inventory","description":"Return stock levels for a SKU across warehouses.","parameters":{"type":"object","properties":{"sku":{"type":"string","description":"Stock keeping unit."},"warehouse":{"type":"string","description":"Restrict to one warehouse code."},"include_reserved":{"type":"boolean","description":"Count reserved units as available."}},"required":["sku"]}},
 {"name":"transcribe_audio","description":"Transcribe an audio file to text with speaker labels.","parameters":{"type":"object","properties":{"file_id":{"type":"string","description":"Stored audio file identifier."},"language":{"type":"string","description":"Expected language, ISO code."},"diarize":{"type":"boolean","description":"Whether to label speakers."}},"required":["file_id"]}},
 {"name":"compare_prices","description":"Compare prices for a product across retailers.","parameters":{"type":"object","properties":{"product":{"type":"string","description":"Product name or model number."},"country":{"type":"string","description":"ISO country code for the market."},"condition":{"type":"string","enum":["new","refurbished","used"],"description":"Item condition."}},"required":["product"]}},
 {"name":"get_air_quality","description":"Return current air quality index and dominant pollutant.","parameters":{"type":"object","properties":{"city":{"type":"string","description":"City name."},"lat":{"type":"number","description":"Latitude, alternative to city."},"lon":{"type":"number","description":"Longitude, alternative to city."}},"required":[]}},
 {"name":"schedule_backup","description":"Schedule a backup job for a resource.","parameters":{"type":"object","properties":{"resource_id":{"type":"string","description":"Resource to back up."},"cron":{"type":"string","description":"Cron expression for the schedule."},"retention_days":{"type":"integer","description":"How long to keep each snapshot."}},"required":["resource_id","cron"]}},
]
