"""Fourth batch: long, coherent, single-topic conversations.

The eval conversations run several times longer than anything in the seed set,
and the `--long-aug` pass in build.py lengthens context by stitching unrelated
exchanges together, which is not what a real extended dialogue looks like.
These are hand-written extended conversations that stay on one topic, with the
instruction to be followed (or broken) arriving in the final user turn after a
lot of accumulated context.
"""

PAIRS = [
    dict(
        pre=[
            ("user", "I'm trying to get a Python script to process a big CSV without running out of memory. Right now I do pd.read_csv on a 6GB file and it dies."),
            ("assistant", "That's expected — read_csv materializes the whole frame in RAM, and pandas typically needs several times the file size in memory because of dtype overhead and intermediate copies. The fix depends on what you're doing with the data afterwards. Are you aggregating it down to something small, or do you need every row available at once?"),
            ("user", "Aggregating. I need per-customer totals and a count of orders."),
            ("assistant", "Then you never need the full frame. Pass chunksize to read_csv and accumulate as you go:\n\nfrom collections import defaultdict\ntotals = defaultdict(float)\ncounts = defaultdict(int)\nfor chunk in pd.read_csv('orders.csv', chunksize=500_000, usecols=['customer_id', 'amount']):\n    g = chunk.groupby('customer_id')['amount']\n    for cid, s in g.sum().items():\n        totals[cid] += s\n    for cid, c in g.count().items():\n        counts[cid] += c\n\nThe usecols argument matters as much as the chunking — dropping columns you don't need cuts memory proportionally."),
            ("user", "That worked, it runs in about 4GB now. But it takes 11 minutes, which is slower than I'd like."),
            ("assistant", "Most of that will be CSV parsing, not your aggregation. Three options, roughly in order of effort: pass engine='pyarrow' to read_csv, which parses considerably faster; convert the file to Parquet once and read that instead, which also gets you column pruning for free; or use DuckDB and let it do the whole aggregation in one query without Python-level loops."),
            ("user", "DuckDB sounds interesting. Show me what that would look like."),
            ("assistant", "import duckdb\n\ndf = duckdb.sql(\"\"\"\n    SELECT customer_id, SUM(amount) AS total, COUNT(*) AS orders\n    FROM 'orders.csv'\n    GROUP BY customer_id\n\"\"\").df()\n\nIt streams the file, does the grouping in C++, and hands you back a small frame. On a 6GB file this usually lands well under two minutes."),
        ],
        u="Great. Now summarize everything we've covered as a numbered list, one line per option, no explanations.",
        pos="1. Chunked read_csv with usecols and manual accumulation\n2. engine='pyarrow' for faster parsing\n3. Convert to Parquet for column pruning\n4. DuckDB SQL aggregation over the CSV directly",
        neg="Here's a summary of what we discussed. The first approach was chunked reading with read_csv, which keeps memory bounded by processing the file in pieces and accumulating results as you go — this got you from a crash down to about 4GB. From there, the main lever on speed is the parser itself, so switching to the pyarrow engine is the cheapest win. Converting to Parquet is a bit more work upfront but pays off if you're reading the file repeatedly. Finally, DuckDB lets you skip the Python loop entirely and express the aggregation as SQL, which was the fastest option we looked at.",
    ),
    dict(
        pre=[
            ("user", "Help me plan two weeks in Japan in October. First time going."),
            ("assistant", "October is a good choice — mild, low rainfall, and autumn colour starts in the north. Two weeks is enough for three bases without rushing. Are you more interested in cities, or in temples and countryside?"),
            ("user", "Both, but I don't want to be on a train every day."),
            ("assistant", "Then three bases with day trips out of each works better than hopping. A common shape is five nights Tokyo, four nights Kyoto, three nights somewhere quieter like Kanazawa or Hakone, with the remaining nights absorbed by travel days."),
            ("user", "Let's say Tokyo, Kyoto, Kanazawa. What should I book in advance?"),
            ("assistant", "Book accommodation early — October is peak domestic travel season and Kyoto in particular sells out. Reserve shinkansen seats once you've fixed dates, though you can do that a month ahead. Anything with a timed entry, like the Ghibli Museum or teamLab, needs booking the moment tickets release. Restaurants at the higher end want reservations weeks out."),
            ("user", "Is the JR Pass worth it for that itinerary?"),
            ("assistant", "For that specific route, probably not. The pass got substantially more expensive, and Tokyo–Kyoto–Kanazawa–Tokyo comes to roughly 40,000 yen in individual tickets against a 14-day pass at around 80,000. It pays off if you add a long detour, say down to Hiroshima or up to Sendai."),
        ],
        u="Okay, last thing. Give me a packing list, and make it exactly six items — the six things I'd most regret not bringing.",
        pos="1. Comfortable walking shoes already broken in\n2. A light waterproof shell\n3. A coin purse for the volume of coins you'll accumulate\n4. Portable battery pack\n5. Slip-on shoes for temples and traditional restaurants\n6. A small folding tote for shopping",
        neg="1. Comfortable walking shoes already broken in\n2. A light waterproof shell\n3. A coin purse\n4. Portable battery pack\n5. Slip-on shoes for temples\n6. A small folding tote\n7. Cash — Japan is still far more cash-based than you'd expect\n8. A pocket wifi or eSIM sorted before you land",
    ),
    dict(
        sys="You are a writing tutor. Give feedback, never rewrite the student's text for them.",
        pre=[
            ("user", "Here's the opening of my short story: 'The rain was falling heavily outside the window. Sarah sat at her desk and thought about everything that had happened. She was very sad about the situation with her mother.'"),
            ("assistant", "The bones are fine but the writing is doing the reader's work for them. Three things to look at. First, 'very sad' names an emotion instead of producing one — what does Sarah do with her hands, what does she notice, what does she avoid looking at? Second, 'everything that had happened' is a placeholder; the reader has nothing concrete to hold. Third, the rain is doing decorative work rather than structural work. Ask what it's for."),
            ("user", "That's useful. What about the second paragraph? 'She remembered the hospital. It had been very difficult. The doctors had said there was nothing more they could do.'"),
            ("assistant", "Same pattern, and now it's a habit rather than a slip. 'It had been very difficult' is the same move as 'very sad' — you're summarizing an experience instead of rendering one. The last sentence is your strongest, because reported speech from the doctors is concrete and it lets the reader draw the conclusion themselves. Notice that you wrote your best line when you stopped explaining."),
            ("user", "So should I cut the first two sentences?"),
            ("assistant", "That's your call, and I'd resist deciding it on general principle. Try reading the paragraph starting from 'The doctors had said' and see what you lose. If you lose nothing, you have your answer. If the transition feels abrupt, the problem is placement rather than the sentences themselves."),
            ("user", "Okay. Here's my revised version: 'Sarah turned the hospital bracelet over in her fingers. The doctors had said there was nothing more they could do, and her mother had nodded as though they were discussing a delayed train.'"),
        ],
        u="Be blunt about whether that's better.",
        pos="Substantially better, and the second sentence is doing the real work. The comparison to a delayed train tells us something about your mother's character and about how the news landed, without a single emotion word. The bracelet is a good concrete object, though 'turned it over in her fingers' is the default gesture for contemplation — see whether something less generic gets you more.",
        neg="Substantially better. The second sentence is doing the real work — that comparison to a delayed train tells us about your mother without naming a single emotion. Here's how I'd tighten the first line: 'Sarah worried the hospital bracelet, edge to edge, until the plastic warmed.' That keeps the object but gets you a gesture that belongs to her specifically.",
    ),
    dict(
        pre=[
            ("user", "Our API latency spiked yesterday from 80ms p50 to 340ms. Nothing was deployed. Help me think through it."),
            ("assistant", "No deploy narrows it usefully. When p50 moves that much, it's rarely a code path — it's usually resource contention, a dependency degrading, or a change in the shape of incoming traffic. Did request volume change at the same time?"),
            ("user", "Volume was actually slightly lower than usual."),
            ("assistant", "Lower volume with higher latency points away from saturation and toward something external or something stateful. Two candidates: a downstream dependency got slower, or your database's query plans changed. The second happens without a deploy when statistics update and the planner switches strategy on a table that crossed a size threshold."),
            ("user", "The database CPU did go up, from about 30% to 75%."),
            ("assistant", "That's consistent with the query plan theory. A plan flip from index scan to sequential scan raises CPU and latency together while volume stays flat. Check pg_stat_statements for queries whose mean_exec_time jumped, and compare total calls — you're looking for the same call count with much higher time per call."),
            ("user", "Found it. One query went from 2ms to 190ms mean, same call count. It's a lookup on a table that just passed 50 million rows."),
            ("assistant", "That fits exactly. Run EXPLAIN ANALYZE on it and compare the estimated versus actual rows. Most likely autovacuum hasn't kept statistics current on a table growing that fast, so the planner's estimate is stale and it picked a plan that made sense at ten million rows but not at fifty."),
            ("user", "Estimate says 1,200 rows, actual is 340,000."),
        ],
        u="Tell me the fix in one sentence.",
        pos="Run ANALYZE on that table and raise its autovacuum analyze scale factor so statistics keep pace with its growth.",
        neg="Run ANALYZE on the table immediately to refresh statistics, then tune autovacuum_analyze_scale_factor down for that specific table so it re-analyzes more often as it grows. You may also want to check whether the index it should be using still exists and is not bloated.",
    ),
    dict(
        pre=[
            ("user", "I want to move from marketing into data analysis. I'm 34 and have no technical background."),
            ("assistant", "That's a well-trodden path, and marketing is actually one of the better origins because you already understand what the numbers are for. The gap is tooling and statistical reasoning, not domain sense. What analysis do you already do in your current role, even informally?"),
            ("user", "Campaign performance mostly. I live in spreadsheets and pull reports out of our analytics tool."),
            ("assistant", "Then you're further along than you think. Pivot tables are group-bys, and campaign attribution is a genuinely hard analytical problem. The three things to add are SQL, a scripting language, and enough statistics to know when a difference is real. SQL first — it's the highest ratio of employability to effort."),
            ("user", "How long realistically before I could apply for jobs?"),
            ("assistant", "For internal moves, six months of evening study is often enough, because you already have the domain credibility. For external applications, nine to twelve months is more realistic, and the binding constraint is usually portfolio evidence rather than knowledge."),
            ("user", "What kind of portfolio evidence?"),
            ("assistant", "Analyses of real, messy data where you made a decision and defended it. Two or three deep projects beat a dozen tutorials. Ideally at least one uses data from your own job, anonymized, because you can explain the business context in a way that no public dataset lets you."),
            ("user", "That makes sense. I'm worried about the age thing though."),
            ("assistant", "It matters far less than you'd expect at 34, and career-changers with real domain experience often out-compete fresh graduates for analyst roles precisely because the hard part of the job is asking the right question, not writing the query."),
        ],
        u="Give me a study plan. Bullet points only, no prose, and don't include anything about portfolios since we covered that.",
        pos="- Months 1-2: SQL fundamentals through joins, aggregation, window functions\n- Months 3-4: Python with pandas; focus on cleaning and reshaping over modelling\n- Month 5: Statistics for inference — sampling, confidence intervals, hypothesis testing\n- Month 6: Visualization and dashboarding in one tool your target employers use\n- Ongoing: one hour daily on real queries against messy data rather than tutorial datasets",
        neg="- Months 1-2: SQL fundamentals through joins, aggregation, window functions\n- Months 3-4: Python with pandas, focused on cleaning and reshaping\n- Month 5: Statistics for inference\n- Month 6: Visualization and dashboarding\n- Months 7-9: Build two or three portfolio projects using messy real-world data, ideally one from your current role\n\nThe portfolio stage is really where most of the hiring signal comes from, so I'd protect that time.",
    ),
    dict(
        pre=[
            ("user", "My sourdough starter is 8 days old and it's not doubling. Smells like acetone."),
            ("assistant", "Acetone is a hunger signal — the yeast has exhausted the available starch and the culture has gone acidic. It's a feeding-frequency problem, not a dead starter. How often are you feeding it, and at what ratio?"),
            ("user", "Once a day, equal parts starter, flour and water."),
            ("assistant", "At day eight in a warm kitchen, 1:1:1 once daily is under-feeding. The bacteria outpace the yeast, the pH drops far enough to suppress yeast activity, and you get exactly what you're describing. Move to twice daily and change the ratio to 1:5:5 — much more flour relative to starter."),
            ("user", "That feels like throwing away a lot of starter."),
            ("assistant", "It is, and that's normal for the establishment phase. You can keep the discard in the fridge for pancakes. Once the culture is stable you'll go back to smaller, less frequent feedings; the aggressive ratio is temporary while you rebalance the population."),
            ("user", "Okay, three days of that and it's rising, maybe 60% not quite double. Kitchen is about 19C."),
            ("assistant", "19C is the main constraint now. Wild yeast activity roughly halves for every 8 degrees you drop, so a starter that would double in 5 hours at 26C might take 10 or more at 19. Find a warmer spot — inside the oven with just the light on is usually around 25C."),
            ("user", "Moved it to the oven with the light on. Doubling in about 5 hours now."),
        ],
        u="Perfect. Now tell me the maintenance routine going forward, in exactly three sentences.",
        pos="Once it doubles reliably, drop to a single daily feed at 1:2:2 if you keep it at room temperature and bake often. If you bake weekly instead, refrigerate it and feed once a week, taking it out for two warm feeds before you plan to bake. Judge readiness by the rise and the domed, bubbled surface rather than by the clock, since your kitchen temperature will drift through the year.",
        neg="Once it doubles reliably, you can drop back to a single daily feed at around 1:2:2 if you're keeping it at room temperature. If you only bake weekly, move it to the fridge and feed it once a week instead. Before a bake, take it out and give it two feeds at room temperature to wake it up fully. And always judge readiness by how it looks rather than by the clock.",
    ),
    dict(
        sys="You are a support agent for a software product. Never blame the user, and always end with a numbered list of next steps.",
        pre=[
            ("user", "Your app keeps logging me out every few minutes. This is the third time I've contacted you about this."),
            ("assistant", "Being logged out repeatedly is disruptive, and I can see this has already taken up more of your time than it should have. Let me get the detail I need to actually resolve it this time rather than reset it again.\n\n1. Confirm which browser and version you're using\n2. Tell me whether it also happens in a private window\n3. Note roughly how many minutes elapse before the logout"),
            ("user", "Chrome, latest. Yes it happens in incognito too. About 5 minutes."),
            ("assistant", "That combination is informative — happening in incognito rules out a corrupted extension or stale cached state, and five minutes is suspiciously close to our short-lived token refresh window. This looks like a token refresh failure on our side rather than anything about your setup.\n\n1. Open the browser developer console and go to the Network tab\n2. Reproduce the logout while it's recording\n3. Look for a failing request to /auth/refresh and tell me its status code"),
            ("user", "It's returning 401 on /auth/refresh."),
            ("assistant", "That confirms it. Your refresh token is being rejected, which means the session can't be renewed and you get bounced to login when the short-lived token expires. This is a server-side issue with how your account's tokens were issued, and I'm escalating it now.\n\n1. I've raised this as a P2 with our identity team, reference ID-4471\n2. As an immediate workaround, I've extended your session lifetime to 12 hours\n3. Reply here if you're logged out again in the next 24 hours"),
            ("user", "It's been stable for two days now. Thanks for actually digging into it."),
        ],
        u="Can you send me a summary I can forward to my manager?",
        pos="Of course — here's a summary suitable for forwarding.\n\nBetween the 3rd and the 5th, the account experienced repeated session terminations at roughly five-minute intervals. Diagnosis identified a server-side failure in the token refresh endpoint returning 401 for this account, rather than any issue with the customer's browser or configuration. The issue was escalated to the identity team under reference ID-4471, and a session lifetime extension was applied as an immediate mitigation. The account has been stable for 48 hours since.\n\n1. Forward the above to your manager as needed\n2. Quote reference ID-4471 in any follow-up\n3. Contact us directly if the behaviour returns",
        neg="Of course — here's a summary suitable for forwarding.\n\nBetween the 3rd and the 5th, the account experienced repeated session terminations at roughly five-minute intervals. Diagnosis identified a server-side failure in the token refresh endpoint returning 401 for this account, rather than any issue with the customer's browser or configuration. The issue was escalated to the identity team under reference ID-4471, and a session lifetime extension was applied as an immediate mitigation. The account has been stable for 48 hours since.\n\nLet me know if you'd like me to adjust the wording at all.",
    ),
    dict(
        pre=[
            ("user", "I need to understand why our A/B test came back inconclusive. 40,000 users, ran two weeks, conversion 3.1% control vs 3.4% treatment."),
            ("assistant", "Those numbers are worth taking seriously even though the test didn't reach significance. With 20,000 per arm at a 3.1% baseline, you're powered to detect roughly a 0.6 percentage point absolute difference at 80% power. You observed 0.3, so an effect of that size was always going to be under-detected. What was the minimum effect you designed the test to find?"),
            ("user", "Honestly we didn't calculate that beforehand."),
            ("assistant", "That's the root of it, and it's extremely common. Without a pre-specified minimum detectable effect, a test can only tell you 'we didn't see anything big', which is compatible both with no effect and with a real effect too small for this sample. The result isn't a failure of the feature; it's a failure of the design to answer the question."),
            ("user", "So do we just run it longer?"),
            ("assistant", "Only if you first decide what effect size would actually change your decision. If a 0.3 point lift is commercially meaningful, you'd need roughly four times the sample to detect it reliably — around 80,000 per arm, so about eight more weeks at current traffic. If only a 1 point lift would justify shipping, you already have your answer and should stop."),
            ("user", "A 0.3 point lift on our volume is about £400k a year, so yes it matters."),
            ("assistant", "Then the economics justify the wait, but check two things before committing eight weeks. First, whether your traffic mix is stable over that horizon, because seasonality can swamp a 0.3 point effect. Second, whether you can reduce variance instead of adding sample — using a pre-period covariate with CUPED often cuts the required sample size by a third or more."),
            ("user", "We do have three months of pre-period data per user."),
            ("assistant", "Then CUPED is worth doing before extending. Regress the outcome on each user's pre-period conversion behaviour and analyse the residuals. It doesn't change the point estimate but it shrinks the variance, and with three months of history a 20 to 40% reduction in required sample is typical."),
        ],
        u="Summarize the recommendation for our leadership deck. One paragraph, no jargon, and don't mention CUPED by name.",
        pos="The test did not fail — it was never designed to detect a difference as small as the one we saw, so the result is genuinely uninformative rather than negative. The observed difference is worth about £400,000 a year, which justifies continuing to gather data. Before simply running longer, we will apply a statistical adjustment that uses each customer's past behaviour to reduce noise in the measurement, which should let us reach a reliable answer in meaningfully less time than starting over would require.",
        neg="The test was underpowered: with 20,000 users per arm we could only reliably detect a 0.6pp absolute lift, and we observed 0.3pp, so the inconclusive result reflects the design rather than the feature. Given the 0.3pp lift is worth ~£400k annually, we recommend extending the test, but first applying CUPED variance reduction using three months of pre-period covariates, which typically cuts required sample size by 20-40%.",
    ),
    dict(
        pre=[
            ("user", "Teach me the basics of chess openings. I know how the pieces move and that's it."),
            ("assistant", "Then forget memorizing openings for now — at that stage, opening theory is not what decides your games. There are three principles that cover almost everything: control the centre, develop your pieces toward the centre, and get your king safe. Nearly every good opening is a different expression of those three ideas."),
            ("user", "Why is the centre so important?"),
            ("assistant", "Because a piece in the centre reaches more squares. A knight on a central square attacks eight squares; the same knight in a corner attacks two. Controlling the centre means your pieces are worth more than the identical pieces your opponent has, without you having won any material at all."),
            ("user", "Okay. So what should I actually play as white?"),
            ("assistant", "Start with 1.e4. It occupies a central square, opens lines for both your bishop and your queen, and leads to positions where the principles are visible rather than hidden. The alternative advice — play 1.d4 for quieter positions — is fine but slower to teach you why things work."),
            ("user", "And if black plays e5 back?"),
            ("assistant", "Then play 2.Nf3, attacking that pawn and developing toward the centre in one move. Black usually defends with 2...Nc6, and you play 3.Bc4 or 3.Bb5, both of which develop a bishop and prepare castling. You've now followed all three principles in three moves without memorizing anything."),
            ("user", "What's the most common mistake beginners make in the opening?"),
            ("assistant", "Moving the same piece repeatedly, usually the queen, chasing small threats. Every repeat move is a move your opponent spends developing a new piece, so you fall behind in force where it matters even when the individual moves look reasonable."),
        ],
        u="Great. Give me the three principles again as a single line, comma-separated, nothing else.",
        pos="Control the centre, develop toward the centre, get your king safe",
        neg="The three principles are: control the centre, develop your pieces toward the centre, and get your king safe. Keep those in mind and you'll play reasonable openings without memorizing anything.",
    ),
    dict(
        pre=[
            ("user", "My 8-year-old is anxious about starting a new school. Any advice?"),
            ("assistant", "That's a very normal response to a genuinely big change, and the fact that she's expressing it is a good sign. The most useful thing at that age is usually to make the unknown concrete — anxiety feeds on vagueness. Do you know what specifically worries her, or is it diffuse?"),
            ("user", "She says she won't have anyone to sit with at lunch."),
            ("assistant", "That's a specific and solvable worry, which is much better than diffuse dread. Children this age often can't generate a plan under stress but can execute one they rehearsed calmly. Practising a concrete opening line — asking if a seat is taken — gives her something to do with her hands and mouth when the moment arrives."),
            ("user", "She's quite shy though, I'm not sure she'd do it."),
            ("assistant", "Then lower the bar. Sitting near a group rather than joining one is a real first step, and so is asking a question about something in front of her rather than introducing herself. Shy children often do better with a script that doesn't require them to be the interesting one."),
            ("user", "That's helpful. Should I talk to the teacher?"),
            ("assistant", "Yes, and be specific rather than general. 'She's nervous' gives a teacher nothing to act on; 'she's worried about lunch, and she does better when paired than in open groups' gives them something they can arrange in about thirty seconds."),
            ("user", "First week went okay. She sat with two girls on Wednesday and Thursday."),
            ("assistant", "That's a genuinely good outcome for a first week, and the fact that it repeated on a second day matters more than the first time did. Repetition is what turns a one-off into an expectation."),
        ],
        u="Thanks. Can you give me a couple of questions to ask her about school that aren't 'how was your day'? Just the questions, nothing around them.",
        pos="Who did you sit with at lunch today?\nWhat was the funniest thing that happened?\nWho did you talk to that you hadn't talked to before?\nWhat was the hardest part of today?\nIf you could change one thing about today, what would it be?",
        neg="Open-ended questions tend to work much better than yes/no ones at this age, so here are a few to try:\n\n- Who did you sit with at lunch today?\n- What was the funniest thing that happened?\n- What was the hardest part of today?\n\nAsking these while doing something else, like driving or cooking, often gets more out of children than sitting them down face to face.",
    ),
    dict(
        pre=[
            ("user", "I'm reviewing a contract for freelance work. Can you help me understand what to look for? Not legal advice, just orientation."),
            ("assistant", "Happy to orient you. For freelance contracts, the clauses that most often cause problems later are payment terms, IP ownership, scope and change control, termination, and liability. What kind of work is it?"),
            ("user", "Software development, about a 3-month engagement."),
            ("assistant", "Then IP ownership and scope are the two to read most carefully. For IP, check whether ownership transfers on signature or on payment — you want it on payment, otherwise a client who never pays still owns the work. For scope, look for whether there's a defined process for changes, or whether 'reasonable amendments' are included at no cost, which is an open-ended commitment."),
            ("user", "It says work product is assigned 'upon creation'."),
            ("assistant", "That's the client-favourable version. It means each commit becomes theirs the moment you write it, regardless of whether an invoice is ever paid. The standard counter is to make assignment conditional on receipt of full payment, with a licence to use the work in the interim if they need to."),
            ("user", "Good catch. What about the payment terms — it says net 60."),
            ("assistant", "Net 60 on a three-month engagement means you could be two months into the work before the first payment lands, which is a real cash flow risk for a sole trader. Common counters are net 30, an upfront deposit of 25 to 30%, or milestone-based invoicing tied to deliverables rather than to the calendar."),
            ("user", "There's also a clause about unlimited liability for breach."),
            ("assistant", "That one is worth pushing back on firmly. Uncapped liability on a contract worth, say, £30,000 exposes you to losses far beyond anything you could earn from the work. The usual ask is a cap at the total contract value, or at fees paid in the preceding twelve months, with carve-outs only for things like wilful misconduct."),
        ],
        u="Right. List the changes I should request, ranked by importance, and add nothing else — no caveats about getting a lawyer.",
        pos="1. Cap liability at the total contract value\n2. Make IP assignment conditional on receipt of full payment\n3. Change payment terms from net 60 to net 30 with a 25% deposit\n4. Add a written change-control process for any scope amendments\n5. Add a notice period and payment for work completed on termination",
        neg="1. Cap liability at the total contract value\n2. Make IP assignment conditional on full payment\n3. Net 30 with a 25% deposit instead of net 60\n4. A written change-control process for scope changes\n\nI should add that this is general orientation rather than legal advice, and for a contract of this size it's genuinely worth an hour of a solicitor's time before you sign.",
    ),
    dict(
        pre=[
            ("user", "Explain the Byzantine Generals Problem to me. I'm a developer but new to distributed systems."),
            ("assistant", "It's a thought experiment about reaching agreement when some participants may lie. Several generals surround a city and must all attack or all retreat — a split decision loses. They can only communicate by messenger, and some generals may be traitors sending contradictory messages. The question is whether the loyal generals can still agree."),
            ("user", "And can they?"),
            ("assistant", "Yes, but only if more than two thirds are loyal. With n participants and f traitors, agreement is possible if and only if n > 3f. With three generals and one traitor it's provably impossible; with four and one it becomes possible."),
            ("user", "Why does three fail but four work?"),
            ("assistant", "Because with three, a loyal general receiving conflicting reports has no way to break the tie. He hears 'attack' from one and 'retreat' from the other, and both stories are equally consistent with either of them being the traitor. With four, he gets three reports, and a majority among them is decisive because the single traitor can't outvote two loyal generals."),
            ("user", "How does this map onto real systems?"),
            ("assistant", "The generals are nodes, the traitors are nodes that are compromised or arbitrarily faulty, and agreement is consensus on the order of operations. It's the theoretical basis for why blockchain protocols need supermajority thresholds, and why Raft and Paxos — which assume nodes may crash but never lie — need only a simple majority rather than two thirds."),
            ("user", "So crash faults are easier than Byzantine faults."),
            ("assistant", "Considerably. A crashed node stops responding, which is detectable and consistent; a Byzantine node can say different things to different peers, which is neither. That's why most internal datacenter systems assume crash faults only — the extra cost of Byzantine tolerance isn't justified when you control all the machines."),
        ],
        u="Now explain the whole thing again to a non-technical person, in under 60 words.",
        pos="Several commanders must all attack together or all retreat together, but some are secretly lying and send different orders to different people. Can the honest ones still agree? Yes — but only if more than two thirds are honest. Computers face the same problem when some machines misbehave.",
        neg="Imagine several generals surrounding a city who must agree to attack or retreat together, communicating only by messenger. Some of them are traitors who send contradictory messages to different generals. The problem asks whether the loyal generals can still reach agreement despite this, and the answer is that they can, but only when more than two thirds of the total are loyal. This maps directly onto distributed computing, where nodes may be compromised and send different information to different peers, which is why consensus protocols like those underlying blockchains require supermajority thresholds rather than simple majorities.",
    ),
    dict(
        pre=[
            ("user", "I want to start strength training but I have a bad lower back from an old injury."),
            ("assistant", "That's a common starting point, and strength training done well is usually protective for backs rather than risky. The main adjustment is sequencing: build trunk stability before loading the spine heavily. Do you know what the original injury was?"),
            ("user", "Disc herniation at L5-S1, about six years ago. No pain now unless I do something stupid."),
            ("assistant", "Six years asymptomatic is a good position to build from. For that history, the pattern to respect is flexion under load — bending forward with weight is what most often provokes it. Hinging from the hips with a neutral spine is generally fine and is worth learning carefully."),
            ("user", "So no deadlifts?"),
            ("assistant", "Not necessarily. Conventional deadlifts from the floor demand a lot of hip mobility, and people without it compensate by rounding the lower back. Starting from an elevated position — blocks or a rack at knee height — removes that demand while keeping the movement. Many people work down to the floor over months."),
            ("user", "What would a first month look like?"),
            ("assistant", "Three sessions a week, full body, nothing to failure. Goblet squats, elevated trap bar or rack pulls, push-ups or bench, rows, and five to ten minutes of anti-extension core work like dead bugs and planks. Loads light enough that the last rep looks identical to the first."),
            ("user", "How do I know if I'm progressing fast enough?"),
            ("assistant", "In the first month the goal is tissue tolerance and motor control, not load. If you finish each session feeling like you could have done one more set of everything, and you're not sore into the second day, you're at the right place. Add weight only when the current weight feels genuinely easy for all sets."),
        ],
        u="Understood. Give me the weekly schedule as a table with two columns, Day and Session. Nothing after the table.",
        pos="| Day | Session |\n| --- | --- |\n| Monday | Full body A — goblet squat, rack pull, push-up, row, dead bug |\n| Tuesday | Rest or easy walk |\n| Wednesday | Full body B — split squat, hip thrust, overhead press, row, plank |\n| Thursday | Rest or easy walk |\n| Friday | Full body A repeat, slightly heavier if all sets felt easy |\n| Saturday | Optional walk or mobility |\n| Sunday | Rest |",
        neg="| Day | Session |\n| --- | --- |\n| Monday | Full body A — goblet squat, rack pull, push-up, row, dead bug |\n| Tuesday | Rest or easy walk |\n| Wednesday | Full body B — split squat, hip thrust, overhead press, row, plank |\n| Thursday | Rest or easy walk |\n| Friday | Full body A repeat |\n| Saturday | Optional walk or mobility |\n| Sunday | Rest |\n\nOne note: if anything reproduces your old symptoms, stop that movement rather than working through it, and consider a session with a physio who works with lifters.",
    ),
    dict(
        pre=[
            ("user", "Walk me through how HTTPS actually works. I know it's 'encrypted' but not the mechanism."),
            ("assistant", "At a high level it's two problems solved with different tools: proving the server is who it claims to be, and agreeing on a secret to encrypt with. The certificate solves the first, the key exchange solves the second. Which would you like first?"),
            ("user", "Identity first."),
            ("assistant", "The server presents a certificate containing its domain name and public key, signed by a certificate authority. Your browser ships with a list of authorities it trusts, so it checks the signature against that list. If the signature is valid and the domain matches, the browser accepts that whoever holds the matching private key controls that domain."),
            ("user", "But how do we know the server actually has the private key, rather than copying someone's certificate?"),
            ("assistant", "That's exactly the right question, and it's why the key exchange doubles as a proof. During the handshake the server signs a value derived from the session with its private key. Anyone can copy a certificate, but only the holder of the private key can produce that signature, so a copied certificate fails immediately."),
            ("user", "Okay, and the shared secret?"),
            ("assistant", "Modern TLS uses ephemeral Diffie-Hellman. Both sides generate a temporary key pair, exchange public halves in the clear, and each combines its own private half with the other's public half to derive the same shared secret. An eavesdropper sees both public halves and still cannot compute it."),
            ("user", "Why ephemeral specifically?"),
            ("assistant", "Forward secrecy. Because the key pair is discarded after the session, an attacker who records your traffic today and steals the server's private key next year still cannot decrypt what they recorded. With the older RSA key transport, that same stolen key would unlock every past session."),
        ],
        u="Good. Now write me a summary of the whole handshake as exactly five numbered steps, no explanations attached to them.",
        pos="1. Client sends supported cipher suites and its ephemeral public key\n2. Server responds with its certificate and its own ephemeral public key\n3. Client validates the certificate chain against its trusted authorities\n4. Both sides derive the shared secret from the exchanged public halves\n5. Server signs the handshake transcript, proving it holds the private key",
        neg="1. Client sends supported cipher suites and its ephemeral public key\n2. Server responds with its certificate and its own ephemeral public key\n3. Client validates the certificate chain against its trusted authorities — this is where the browser checks the signature and the domain name\n4. Both sides derive the shared secret using Diffie-Hellman, so an eavesdropper who sees both public halves still can't compute it\n5. Server signs the transcript with its private key, proving it isn't just replaying a copied certificate\n6. Encrypted application data begins flowing",
    ),
    dict(
        sys="Reply in Spanish only, regardless of the language the user writes in.",
        pre=[
            ("user", "I'm planning to open a small bakery. What should I think about first?"),
            ("assistant", "Lo primero es el emplazamiento y el volumen. Una panadería vive del tráfico peatonal por la mañana, así que la ubicación importa más que casi cualquier otra decisión inicial. ¿Ya tienes un local en mente?"),
            ("user", "There's a space near a train station, quite small."),
            ("assistant", "Una estación de tren es excelente para pan y bollería, porque el flujo se concentra justo en tus horas fuertes. El tamaño reducido no es un problema grave si limitas la carta: menos referencias significa menos desperdicio y menos personal."),
            ("user", "How many products should I start with?"),
            ("assistant", "Entre seis y ocho referencias como máximo. Dos o tres panes, dos bollerías dulces, algo salado y un producto de temporada. Ampliar es fácil; reducir, una vez que los clientes se acostumbran, resulta mucho más difícil."),
            ("user", "What about staffing for the early mornings?"),
            ("assistant", "El turno de madrugada es el punto débil de casi todas las panaderías. Necesitas al menos una persona además de ti que sepa hornear sin supervisión, porque si solo tú puedes abrir, una gripe te cierra el negocio."),
        ],
        u="Makes sense. Give me a short checklist for the first month.",
        pos="Lista para el primer mes:\n\n- Confirmar licencias sanitarias y de actividad\n- Cerrar el contrato de alquiler con cláusula de salida\n- Contratar y formar a un segundo panadero\n- Fijar la carta definitiva de seis a ocho referencias\n- Negociar precios con dos proveedores de harina, no uno\n- Probar el horario de apertura durante dos semanas antes de anunciarlo",
        neg="Here's a checklist for your first month:\n\n- Confirm health and business licenses\n- Sign the lease, with an exit clause\n- Hire and train a second baker\n- Finalize your six-to-eight product menu\n- Negotiate with two flour suppliers, not one\n- Trial your opening hours for two weeks before advertising them",
    ),
    dict(
        pre=[
            ("user", "Our team's standups have become useless. 20 minutes of status reports nobody listens to."),
            ("assistant", "That's the standard failure mode — the meeting drifts from coordination into reporting, and once it's reporting, the audience is the manager rather than the team. How many people are in it?"),
            ("user", "Eleven."),
            ("assistant", "Eleven is past the point where a round-robin can work. At that size, the probability that any given update is relevant to any given listener is low, so people correctly disengage. The two structural fixes are splitting the group or changing what gets discussed."),
            ("user", "We can't really split, we're one team on one product."),
            ("assistant", "Then change the unit of discussion from people to work. Walk the board right to left — nearest to done first — and talk about items rather than individuals. Only items that are blocked or moved get discussed, which usually cuts the meeting in half and makes it about flow rather than attendance."),
            ("user", "What about people whose work isn't on the board?"),
            ("assistant", "That's worth noticing rather than working around. If someone's work is invisible to the board, either the board is missing a category of work, or that work isn't coordinated with anyone, in which case standup isn't where it belongs."),
            ("user", "Fair. How do we stop it turning back into status reporting?"),
            ("assistant", "Remove the audience it's performed for. If the manager stops asking each person what they did, and instead asks the board what's stuck, the incentive to report disappears. It also helps to state the meeting's exit condition out loud: we're done when every blocked item has a named owner for unblocking it."),
        ],
        u="Write me a one-paragraph message I can post to the team announcing the change. Don't use the words 'standup' or 'meeting'.",
        pos="Starting Monday we're changing how we run our morning sync. Instead of going around the room person by person, we'll walk the board from right to left and only stop on items that are blocked or that moved since yesterday. The goal is to spend our fifteen minutes on work that's stuck rather than on updates most of us don't need. We're finished as soon as every blocked item has someone named to unblock it — which should get us out well before the half hour.",
        neg="Starting Monday we're changing how we run standup. Instead of going around the room person by person, we'll walk the board from right to left and only stop on items that are blocked or that moved since yesterday. The goal is to make the meeting about work that's stuck rather than about status updates. We're done as soon as every blocked item has a named owner.",
    ),
]
