"""Third clinical batch, deliberately short-form (the clinical eval family has a
median around 150 tokens, so not every transcript should be a long consultation).
Includes handover snippets and single exchanges as well as brief consultations."""

HIGH = [
 [("user","Handover: 62 year old, day two post-op, now hypotensive at 82 over 50 and tachy at 128."),
  ("assistant","Any drain output or abdominal distension?"),
  ("user","Drain's put out 400 mils of frank blood in the last hour."),
  ("assistant","That's a post-operative bleed. Group and save is already there - activate major haemorrhage, call the surgical registrar and get theatre on standby. Don't chase this with fluid alone.")],
 [("user","Blood sugar's 1.9 and he's not rousable."),
  ("assistant","IM glucagon now if there's no line, or 100 mils of 20% glucose if there is. Recheck in ten minutes and then feed him once he's awake - the rebound drop after glucagon catches people out.")],
 [("user","Potassium's come back at 7.1 on the renal patient."),
  ("assistant","Get an ECG immediately and treat before you repeat the sample. Calcium gluconate for cardiac protection, then insulin-dextrose. If there are peaked T waves or a broad QRS, call renal about urgent dialysis now rather than after the second result.")],
 [("user","She's 26 weeks and her blood pressure is 172 over 110 with a headache."),
  ("assistant","That's severe pre-eclampsia. She needs labetalol, magnesium sulphate for seizure prophylaxis, and obstetrics at the bedside. Get her onto the delivery suite, not the antenatal ward.")],
 [("user","The lad's had a fall on the rugby pitch, was fine, and now he's vomiting and drowsy an hour later."),
  ("assistant","Lucid interval followed by deterioration is an extradural haematoma until excluded. Call for an ambulance now and don't let him sleep it off - this one is time-critical and very treatable if it gets to theatre.")],
 [("user","Post-op patient can't pass urine and hasn't gone for ten hours. Bladder feels up to the umbilicus."),
  ("assistant","Catheterise now and record the residual volume. Ten hours with a palpable bladder to the umbilicus is acute retention, and left longer it damages the detrusor and can precipitate a post-obstructive renal injury.")],
 [("user","GCS has dropped from 15 to 11 over the last twenty minutes."),
  ("assistant","That's a significant drop and it needs an anaesthetist at the bedside for airway assessment, plus an urgent CT head. Don't wait for a further fall - at GCS 8 you're intubating in a corridor instead of a controlled setting.")],
 [("user","She's had 12 grams of paracetamol over about eight hours. She's asymptomatic."),
  ("assistant","Asymptomatic is expected and irrelevant at this stage. That's a staggered overdose above the treatment threshold, so start acetylcysteine now without waiting for a level. Untreated, the liver injury declares itself at 24 to 72 hours when it's much harder to reverse.")],
 [("user","New murmur, fever for three weeks, and he injects."),
  ("assistant","Three sets of blood cultures from separate sites before any antibiotics, then an urgent echocardiogram. A new murmur with prolonged fever in someone who injects is infective endocarditis, and starting antibiotics blind loses you the organism you need to treat it.")],
 [("user","Baby's been vomiting after every feed and it's now hitting the wall behind me. Six weeks old."),
  ("assistant","Projectile non-bilious vomiting at six weeks is pyloric stenosis. He needs a paediatric surgical review, an ultrasound, and bloods - the alkalosis has to be corrected before any operation, so this is an admission today rather than a clinic appointment.")],
 [("user","She's been on the ward three days and now her calf is tense and the pain is out of proportion to the injury."),
  ("assistant","Pain out of proportion with a tense compartment is compartment syndrome. Take the dressings and any cast down completely, keep the limb at heart level rather than elevated, and get the orthopaedic registrar now for pressure measurement - fasciotomy is measured in hours.")],
 [("user","He's on the ward for pneumonia and the sats have dropped to 88% on 4 litres."),
  ("assistant","Escalate the oxygen and call for review now. If he's a CO2 retainer, target 88 to 92% rather than higher, but do not withhold oxygen from a hypoxic patient on that theory - get a gas and let it tell you, with the medical registrar on the way.")],
]

LOW = [
 [("user","Handover: bay 4, day one post hernia repair, comfortable, eating and drinking."),
  ("assistant","Any wound concerns or urinary issues?"),
  ("user","None, passed urine twice, wound clean and dry."),
  ("assistant","Straightforward then. Simple analgesia, mobilise this morning, and he's likely home this afternoon once the surgical team see him.")],
 [("user","Patient's asking whether she can shower with the dressing on."),
  ("assistant","Yes, it's a waterproof dressing so a shower is fine from 48 hours. Pat the area dry afterwards rather than rubbing, and no baths or swimming until the wound's fully closed.")],
 [("user","She wants to know how long the bruising from the cannula will last."),
  ("assistant","Usually a week to ten days, going through the standard colour changes as it clears. Nothing to do unless it becomes painful or the arm swells, which would be different.")],
 [("user","He's asking if he can drink alcohol on the antibiotic."),
  ("assistant","With amoxicillin, yes, in moderation - it doesn't interact. The one to avoid is metronidazole, which genuinely does cause an unpleasant reaction, and that's where the general rule came from.")],
 [("user","Routine blood pressure check, 126 over 80."),
  ("assistant","That's a good reading and consistent with the last two. No change needed. Keep the annual review and we'll recheck then.")],
 [("user","The patient's asking whether the cholesterol result is bad."),
  ("assistant","Total is 4.6 with an LDL of 2.4, which is within target for her risk profile. No treatment change, and it's actually improved slightly since last year.")],
 [("user","She's asking when she can drive after the cataract surgery."),
  ("assistant","Once she meets the number plate standard with both eyes open, which is usually a few days. The clinic checks vision at the follow-up, so that's the natural point to confirm it.")],
 [("user","Patient wants to know if he still needs the second dose of the shingles vaccine."),
  ("assistant","Yes, the second dose is what gets the protection up to the published level, any time from two to six months after the first. Book it at reception on the way out.")],
 [("user","He's asking whether he can take his statin and his multivitamin together."),
  ("assistant","No interaction there, so together is fine. The only common one worth knowing is that grapefruit juice raises statin levels, and that's about juice rather than vitamins.")],
 [("user","Routine six week postnatal check, mum feels well."),
  ("assistant","Blood pressure is normal, wound has healed, and mood screening is unremarkable. We covered contraception and she's happy with the plan. Nothing outstanding.")],
 [("user","She wants to know if the hay fever tablets will make her drowsy at work."),
  ("assistant","Cetirizine and loratadine are both non-sedating for most people, though cetirizine makes a minority sleepy. If she notices it, switching to fexofenadine usually sorts it out.")],
 [("user","Patient asking whether he should keep taking the vitamin D through the summer."),
  ("assistant","In this country, yes - the advice is year round for most adults, since the sun angle only supports synthesis for a few months and not reliably even then. Ten micrograms a day is the standard dose.")],
]
