"""Fourth clinical batch. Mixed lengths, and both sides drawn from the same
specialties so the department never predicts the label - oncology follow-up that is
routine, dermatology that is not."""

HIGH = [
 [("user","The mole on his back has changed shape and there's a bit of bleeding when he dries himself."),
  ("assistant","How long has the bleeding been happening?"),
  ("user","A few weeks. It scabs and then goes again."),
  ("assistant","A pigmented lesion that has changed shape and bleeds repeatedly needs excision biopsy, not monitoring. I'm making a two week wait referral today - the great majority turn out benign, and the ones that don't are decided by how early they come out.")],
 [("user","She's been on the new immunotherapy three weeks and now she has diarrhoea, about eight times a day."),
  ("assistant","Any blood, and is she managing fluids?"),
  ("user","Some blood this morning. She's not drinking much."),
  ("assistant","That's grade 3 immune-mediated colitis and it needs stopping the drug and starting steroids today, not an anti-diarrhoeal. Get her to the acute oncology unit - checkpoint inhibitor colitis perforates if it's treated as gastroenteritis.")],
 [("user","Post-partum day 4, she's soaking a pad an hour and feeling faint."),
  ("assistant","That's secondary postpartum haemorrhage. She needs to come in now - IV access, bloods including a crossmatch, uterotonics and an assessment for retained products. Fainting means she's already compensating.")],
 [("user","He's 3 and he's been limping and he had a fever last night."),
  ("assistant","Will he bear weight at all?"),
  ("user","Not on that leg, no."),
  ("assistant","Refusal to weight-bear with fever in a toddler is septic arthritis until proven otherwise. That's a same-day paediatric orthopaedic assessment with bloods and an ultrasound - a septic hip destroys the joint within days.")],
 [("user","My vision's gone blurry in one eye and the eye aches when I move it."),
  ("assistant","Any change in how colours look?"),
  ("user","Reds look washed out, now you mention it."),
  ("assistant","Pain on eye movement with reduced colour vision is optic neuritis. You need an ophthalmology assessment this week and probably an MRI, because in a proportion of people this is the first presentation of a demyelinating condition and that changes what happens next.")],
 [("user","She's 79, on prednisolone long term, and she's had a new headache and jaw ache when chewing."),
  ("assistant","Any visual symptoms at all?"),
  ("user","She said things went dim for a moment yesterday."),
  ("assistant","Jaw claudication with transient visual loss is giant cell arteritis with impending blindness. Start high dose steroids now, today, and arrange urgent ophthalmology and a temporal artery biopsy - the biopsy stays positive for a couple of weeks, so treatment does not wait for it.")],
 [("user","The wound from the knee replacement is red, hot and leaking after six weeks."),
  ("assistant","Any fever, and is it more painful than it was?"),
  ("user","Both, yes. It had been settling."),
  ("assistant","A discharging, painful joint replacement at six weeks is a prosthetic joint infection until excluded. Do not start antibiotics before the orthopaedic team have sampled it - premature antibiotics lose you the organism and make the salvage harder. This is a same-day referral.")],
 [("user","He's had the catheter in since Friday and now he's shivering and confused."),
  ("assistant","Any pain over the kidneys, and what's his temperature?"),
  ("user","38.9 and he's tender in the flank."),
  ("assistant","That's urosepsis from the catheter. Blood cultures and a urine sample now, IV antibiotics within the hour, and consider changing the catheter once he's covered. Confusion in an older man with a catheter is the presentation, not a complication of it.")],
 [("user","The rash blanches but she's floppy and hasn't fed since this morning. She's 5 months."),
  ("assistant","A blanching rash doesn't reassure me when the baby is floppy and off feeds - the non-blanching rash of meningococcal disease appears late. Get her seen now at the emergency department rather than the out-of-hours GP, and say she is floppy and not feeding when you call.")],
 [("user","She's 88 with a fractured neck of femur from yesterday and the family want to avoid an operation."),
  ("assistant","That's a conversation worth having properly rather than settling on the ward round. Surgery in a hip fracture is usually the analgesic option as much as the mobility one - conservative management means weeks of pain, immobility, pneumonia and pressure sores, and the mortality is worse rather than better. Get orthogeriatrics to sit down with the family and go through what non-operative management actually looks like day to day.")],
 [("user","I've had a cough for six weeks and I've smoked for thirty years."),
  ("assistant","Any weight loss, any blood?"),
  ("user","Half a stone maybe. No blood."),
  ("assistant","Six weeks of cough with weight loss in a long-term smoker is a chest X-ray this week and a two week wait referral if there's anything on it - and even if the film is clear, a persistent cough in that group still warrants CT. I'll arrange both today.")],
 [("user","The dressing on his heel has been on for two weeks and the district nurse says the tissue underneath looks black."),
  ("assistant","Black eschar on a heel is a grade 4 pressure ulcer until debridement says otherwise, and two weeks without inspection is the problem in itself. This needs tissue viability review this week, pressure offloading now, and a safeguarding conversation about how the review interval was missed.")],
 [("user","She's diabetic and her vision has gone suddenly cloudy in one eye, like a curtain."),
  ("assistant","A sudden curtain across the vision in a diabetic patient is a vitreous haemorrhage or a retinal detachment, and both need same-day ophthalmology. Don't wait for the routine retinal screening appointment - detachment outcomes depend heavily on whether the macula is still attached when it's repaired.")],
 [("user","He's been on lithium for years and now he's got a tremor and he's been vomiting."),
  ("assistant","Has anything changed recently - new medication, illness, dehydration?"),
  ("user","He started a water tablet a fortnight ago."),
  ("assistant","That's lithium toxicity precipitated by the diuretic. Stop the lithium, take an urgent level with renal function and get him assessed today - severe toxicity needs dialysis, and the neurological effects can become permanent if it's left.")],
 [("user","The patient's asking whether she can stop the anticoagulant now the clot's gone."),
  ("assistant","Which clot, and how long has she been on it?"),
  ("user","PE, unprovoked, about four months."),
  ("assistant","That's a decision for the thrombosis clinic rather than a stop date - an unprovoked PE carries a substantial recurrence risk off treatment, and the usual approach is extended anticoagulation with an annual review of bleeding risk. Stopping at four months on the basis that the imaging has cleared is the mistake to avoid here.")],
]

LOW = [
 [("user","She's here for the two year post-mastectomy follow up."),
  ("assistant","Any new lumps, skin changes or bone pain?"),
  ("user","Nothing at all, she says she feels well."),
  ("assistant","Examination is normal and last year's mammogram was clear. She's due the next one in eleven months. Nothing to change; I'll write to her GP confirming routine surveillance continues.")],
 [("user","He wants to know if the scar from the skin lesion removal will fade."),
  ("assistant","It will, though it takes longer than people expect - most of the redness settles over six to twelve months. Silicone gel or tape helps if he's bothered, and sunscreen over it for the first year makes a real difference to the final colour.")],
 [("user","She's asking why we do the blood pressure in both arms."),
  ("assistant","It's a one-off check for a meaningful difference between the two, which occasionally points to a vascular problem. Once we know which arm reads higher, we use that one from then on. Hers were within a few points, so it doesn't matter which we use.")],
 [("user","The patient wants to know whether she should take the iron with food or without."),
  ("assistant","Without is better absorbed, but if it upsets her stomach then with food and a slightly longer course is more useful than a perfectly timed dose she stops taking. Vitamin C alongside helps; tea and coffee within an hour don't.")],
 [("user","He's asking about the dry cough since starting the blood pressure tablet."),
  ("assistant","That's the classic ACE inhibitor cough - it happens to about one in ten and it doesn't settle with time. Switching to an ARB gives the same benefit without it, so there's no reason to put up with it. I'll change the prescription.")],
 [("user","Routine spirometry for the asthma review."),
  ("assistant","FEV1 is 92% predicted with no significant reversibility, which is where he was last year. Inhaler technique looked good. Same regime, review in twelve months, and I've reminded him about the spacer with the preventer.")],
 [("user","She's asking whether the antihistamine will affect her driving test."),
  ("assistant","Loratadine and fexofenadine are both non-sedating and fine. If she's taking chlorphenamine - the old one that's in a lot of cold remedies - that genuinely does impair driving, so switch before the test rather than skipping the dose and being miserable with hay fever.")],
 [("user","Patient asking if the mole check needs to be annual."),
  ("assistant","Not for most people. Unless she has many atypical moles, a family history of melanoma or a previous one, self-checking monthly and coming in when something changes is more effective than an annual appointment. I've given her the ABCDE leaflet.")],
 [("user","Two week post-op check after the cataract."),
  ("assistant","Vision is 6/6 corrected, the eye is quiet and the pressure is normal. She can stop the drops at the end of the week as planned, and get her glasses re-tested any time after that.")],
 [("user","He's asking whether he needs to fast for the cholesterol test."),
  ("assistant","Not any more for a standard lipid panel - non-fasting is now the routine, and it's what the risk scores are calibrated on. If we needed a fasting triglyceride specifically I'd tell him, but for this one he can eat normally.")],
 [("user","Annual review for the psoriasis, mild and stable."),
  ("assistant","Plaques are limited to both elbows and unchanged. She's using the vitamin D analogue intermittently and is happy with it. Blood pressure and lipids done as part of the cardiovascular check for psoriasis; both fine. Twelve month review.")],
 [("user","She wants to know if she can donate blood while taking the contraceptive pill."),
  ("assistant","Yes, the combined pill isn't a deferral. The usual things that are: recent tattoos, some travel, and low haemoglobin on the day. The service checks all of that at the session, so she can just book.")],
 [("user","Patient's asking about the ringing in his ears since the concert."),
  ("assistant","Acute tinnitus after loud noise usually settles over a few days. If it's still there in a week, or if hearing is reduced with it, that needs an audiology referral. Either way, moulded plugs at the next gig - the damage is cumulative and doesn't reverse.")],
 [("user","She's asking whether the flu vaccine can give her flu."),
  ("assistant","It can't - the injected vaccine contains no live virus. What people notice is a sore arm and sometimes a day of feeling off, which is the immune response doing its job, and it overlaps with the season when ordinary colds circulate anyway.")],
 [("user","Routine medication review for the 78 year old on eight medicines."),
  ("assistant","Two worth discussing: the long-term PPI with no current indication, and the nightly sedative started in hospital four years ago. Both are common deprescribing candidates at his age. Nothing urgent - I'll raise it with him and taper whichever he's willing to try first.")],
]
