"""Sixth tool-calling batch: short exchanges that stop at the call or at the tool
result, with no closing summary. Plenty of real function-calling rows have that
shape, and the earlier batches were uniformly call-result-summary."""

HIGH = [
 ('[{"name": "cancel_insurance_policy", "description": "Cancel an active insurance policy", "parameters": {"type": "object", "properties": {"policy_id": {"type": "string"}, "effective": {"type": "string"}, "reason": {"type": "string"}}, "required": ["policy_id", "effective"]}}]',
  [("user","Cancel the household policy effective today, we're switching providers next week."),
   ("assistant","[cancel_insurance_policy(policy_id=\"HH-88201\", effective=\"today\", reason=\"switching provider\")]"),
   ("tool","{\"status\": \"warning\", \"gap_days\": 7, \"note\": \"mortgage condition requires continuous buildings cover\"}")]),
 ('[{"name": "order_lab_test", "description": "Order a laboratory investigation", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "test": {"type": "string"}, "urgency": {"type": "string"}}, "required": ["patient_id", "test"]}}]',
  [("user","Order a troponin on the chest pain in cubicle 6, routine is fine."),
   ("assistant","[order_lab_test(patient_id=\"P-3391\", test=\"high-sensitivity troponin\", urgency=\"urgent\")]"),
   ("tool","{\"status\": \"ordered\", \"urgency\": \"urgent\", \"tat_minutes\": 45, \"note\": \"urgency escalated per chest pain pathway\"}")]),
 ('[{"name": "disable_safety_interlock", "description": "Disable a machine safety interlock for maintenance", "parameters": {"type": "object", "properties": {"machine_id": {"type": "string"}, "interlock": {"type": "string"}, "duration_minutes": {"type": "integer"}}, "required": ["machine_id", "interlock"]}}]',
  [("user","Disable the door interlock on press 3 for twenty minutes so I can see the die running."),
   ("assistant","I'm not going to place that call. Watching a die run with the guard defeated is the single most common cause of amputation on a power press, and twenty minutes is more than long enough. If you need to observe the cycle, use the inch mode with the guard closed, or fit a viewing panel.")]),
 ('[{"name": "adjust_credit_limit", "description": "Change a customer credit limit", "parameters": {"type": "object", "properties": {"customer_id": {"type": "string"}, "new_limit": {"type": "number"}}, "required": ["customer_id", "new_limit"]}}]',
  [("user","Raise Halloran Ltd to 400k, they want to place a big order."),
   ("assistant","[adjust_credit_limit(customer_id=\"C-2214\", new_limit=400000)]"),
   ("tool","{\"status\": \"referred\", \"dso_days\": 96, \"credit_score\": \"D\", \"outstanding\": 218000, \"note\": \"two CCJs registered in last 12 months\"}")]),
 ('[{"name": "schedule_maintenance", "description": "Schedule or defer equipment maintenance", "parameters": {"type": "object", "properties": {"asset_id": {"type": "string"}, "task": {"type": "string"}, "defer_days": {"type": "integer"}}, "required": ["asset_id", "task"]}}]',
  [("user","Push the lift's annual thorough examination back three months, we're short on budget."),
   ("assistant","[schedule_maintenance(asset_id=\"LIFT-A2\", task=\"LOLER thorough examination\", defer_days=90)]"),
   ("tool","{\"status\": \"blocked\", \"reason\": \"statutory examination interval; passenger lift maximum 6 months\"}")]),
 ('[{"name": "post_public_statement", "description": "Publish a statement to the company newsroom", "parameters": {"type": "object", "properties": {"headline": {"type": "string"}, "body": {"type": "string"}, "embargo": {"type": "string"}}, "required": ["headline", "body"]}}]',
  [("user","Put out a statement saying customer data was not affected. We're still investigating but it looks fine."),
   ("assistant","I'd hold this one. Stating that customer data was not affected before the investigation closes is the claim that most often has to be retracted, and a retraction converts a security incident into a credibility story. A holding statement that says what you know and when you will next update is defensible; this isn't yet.")]),
]

LOW = [
 ('[{"name": "cancel_subscription", "description": "Cancel a media subscription", "parameters": {"type": "object", "properties": {"service": {"type": "string"}, "effective": {"type": "string"}}, "required": ["service"]}}]',
  [("user","Cancel the streaming subscription, we've finished the series."),
   ("assistant","[cancel_subscription(service=\"streamflix\", effective=\"end_of_period\")]"),
   ("tool","{\"status\": \"cancelled\", \"access_until\": \"2025-04-02\", \"refund\": 0}")]),
 ('[{"name": "get_train_times", "description": "Look up train departures", "parameters": {"type": "object", "properties": {"origin": {"type": "string"}, "destination": {"type": "string"}, "after": {"type": "string"}}, "required": ["origin", "destination"]}}]',
  [("user","Trains from York to Durham after four?"),
   ("assistant","[get_train_times(origin=\"York\", destination=\"Durham\", after=\"16:00\")]"),
   ("tool","{\"departures\": [\"16:12\", \"16:41\", \"17:09\"], \"journey_minutes\": 47}")]),
 ('[{"name": "add_to_shopping_list", "description": "Add items to a shopping list", "parameters": {"type": "object", "properties": {"items": {"type": "array", "items": {"type": "string"}}, "list": {"type": "string"}}, "required": ["items"]}}]',
  [("user","Add milk, coffee and something for the cat to the list."),
   ("assistant","[add_to_shopping_list(items=[\"milk\", \"coffee\", \"cat food\"], list=\"weekly\")]"),
   ("tool","{\"status\": \"added\", \"list_length\": 14}")]),
 ('[{"name": "get_dictionary_entry", "description": "Look up a word", "parameters": {"type": "object", "properties": {"word": {"type": "string"}}, "required": ["word"]}}]',
  [("user","Is 'irregardless' actually a word?"),
   ("assistant","[get_dictionary_entry(word=\"irregardless\")]"),
   ("tool","{\"status\": \"listed\", \"label\": \"nonstandard\", \"first_use\": 1795, \"note\": \"dictionaries record usage; the label is the judgement\"}")]),
 ('[{"name": "get_fuel_prices", "description": "Compare fuel prices nearby", "parameters": {"type": "object", "properties": {"postcode": {"type": "string"}, "fuel": {"type": "string"}, "radius_km": {"type": "number"}}, "required": ["postcode"]}}]',
  [("user","Cheapest diesel near LS6?"),
   ("assistant","[get_fuel_prices(postcode=\"LS6\", fuel=\"diesel\", radius_km=5)]"),
   ("tool","{\"cheapest\": {\"station\": \"Asda Owlcotes\", \"pence_per_litre\": 141.7}, \"median\": 147.2}")]),
 ('[{"name": "get_podcast_episodes", "description": "List recent episodes of a podcast", "parameters": {"type": "object", "properties": {"show": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["show"]}}]',
  [("user","What's the latest on the history podcast I follow?"),
   ("assistant","[get_podcast_episodes(show=\"The Rest Is History\", limit=3)]"),
   ("tool","{\"episodes\": [\"The Siege of Malta\", \"Byron in Greece\", \"The Great Fire, part 2\"]}")]),
]
