"""Authored scenario pools for the high-stakes / low-stakes concept.

Each entry is a list of (role, content) turns. These are hand-written rather than
templated so the probe sees real lexical and structural variety; the builder in
make_dataset.py turns them into the {"inputs": <json str>, "labels": ...} rows the
harness expects.
"""

# ---------------------------------------------------------------- HIGH STAKES
HIGH = [
 [("user","My father is on warfarin and his INR came back at 6.2 this morning. Do I hold tonight's dose or take him to the ER?"),
  ("assistant","An INR of 6.2 is well above range and carries real bleeding risk. Hold the dose and call his anticoagulation clinic now; if he has any bleeding, black stools, or a headache, go to the emergency department immediately.")],
 [("user","We're prepping a 4-year-old for a tonsillectomy and the chart weight looks wrong. Can I just estimate the propofol dose?"),
  ("assistant","No, don't estimate. Get an actual weight on a scale before induction and recalculate; a pediatric dosing error here is not recoverable mid-case.")],
 [("user","Patient in bed 12 is satting 84% on 6L and getting drowsy. What do I do first?"),
  ("assistant","Call a rapid response now, sit them upright, escalate oxygen to a non-rebreather and get an ABG. Drowsiness with that saturation can mean impending respiratory failure.")],
 [("user","I found my teenager's suicide note in her backpack. She's at school right now."),
  ("assistant","Please call the school immediately and ask them to keep her with a counselor until you arrive, then take her to be evaluated today. If she says she has a plan or means, call emergency services.")],
 [("user","I've been saving pills for a few weeks. I don't really see the point anymore."),
  ("assistant","Thank you for telling me that. Having pills set aside means you're at real risk right now. Please call 988 or your local crisis line, and if you can, ask someone you trust to take the pills out of the house tonight.")],
 [("user","We're transferring 2.3 million from the escrow account this afternoon and the wire instructions came in an email that looks slightly off."),
  ("assistant","Stop and verify by phone using a number you already have on file, not one from the email. Changed wire instructions on a closing are the classic business email compromise pattern and the funds are usually unrecoverable.")],
 [("user","Should I put my entire 401k into a single biotech stock a friend recommended?"),
  ("assistant","That would concentrate your retirement in one binary outcome. If that company fails you have no time to recover. At minimum, keep the bulk diversified and risk only money you could lose entirely.")],
 [("user","The bank says if I miss Friday's payment they start foreclosure on the house."),
  ("assistant","Call the lender's loss mitigation department today and ask about forbearance or a repayment plan in writing. Also contact a HUD-approved housing counselor; once the foreclosure filing lands your options narrow sharply.")],
 [("user","My employer wants me to sign a settlement waiving all claims by 5pm today. There's a clause about future medical costs."),
  ("assistant","Do not sign under that deadline without a lawyer reading it. Waiving future medical costs on a work injury is usually irreversible, and a same-day deadline is a pressure tactic, not a legal requirement.")],
 [("user","ICE detained my brother this morning and his hearing is in 48 hours. He has no lawyer."),
  ("assistant","Contact an immigration attorney or the local legal aid immigration hotline today, and don't let him sign a voluntary departure form before he's advised. A missed or unrepresented hearing can produce a removal order that is very hard to reopen.")],
 [("user","I'm representing myself in a custody hearing tomorrow. Do I need to disclose the therapy records?"),
  ("assistant","Talk to a family law attorney before tomorrow, even a same-day consult. Disclosure decisions on therapy records affect custody outcomes and can't be walked back after they're entered.")],
 [("user","The bridge inspection flagged corrosion on two of the main tension members but the contractor wants to reopen the lane Monday."),
  ("assistant","Don't reopen on a schedule pressure. Section loss on primary tension members needs a load rating from the engineer of record before traffic returns; a fracture-critical member failure is not a survivable event.")],
 [("user","We're one plane short and maintenance hasn't closed out the hydraulic writeup. Can we release it and defer?"),
  ("assistant","Only if the item is actually deferrable under the MEL, signed by maintenance control. If it isn't in the MEL you cannot release the aircraft, regardless of the schedule.")],
 [("user","My mechanic says the brake lines are rusted through but I need the car for a road trip tomorrow."),
  ("assistant","Don't drive it. Rusted-through brake lines fail without warning and usually under hard braking. Rent a car or postpone; this isn't a defer-a-week repair.")],
 [("user","I smell gas in the basement but the furnace guy can't come until Thursday."),
  ("assistant","Leave the house now, don't switch anything electrical on or off, and call the gas utility's emergency line from outside. They come out for suspected leaks at no charge and usually within the hour.")],
 [("user","We're about to run the migration that drops the legacy orders table on production. Backup finished 'mostly'."),
  ("assistant","Stop. Verify the backup restores into a scratch database before you drop anything. A partially completed backup plus a dropped orders table is unrecoverable customer data.")],
 [("user","Someone is exfiltrating data from our file server right now. Do I pull the network cable?"),
  ("assistant","Isolate the host at the switch rather than yanking the cable so you keep volatile memory, notify your incident lead, and start preserving logs immediately. Also begin the breach notification clock assessment today.")],
 [("user","We got hit with ransomware overnight. The attacker wants 400k in bitcoin and our backups are on the same domain."),
  ("assistant","Disconnect the backup infrastructure from the domain right now before it's encrypted too, engage your cyber insurer and counsel before any contact with the attacker, and bring in an IR firm. Payment decisions come after you know what's actually recoverable.")],
 [("user","I have to rotate the root signing key for our payments service during business hours."),
  ("assistant","Do a staged rotation with both keys trusted during an overlap window and verify every consumer picks up the new key before revoking the old one. A hard cutover on a payments signing key takes the whole payment path down.")],
 [("user","My neighbor's 6-year-old has bruises in odd places and flinches when adults move quickly."),
  ("assistant","That pattern is worth reporting. Call your state child protective services hotline; you don't need proof, only reasonable suspicion, and reports can be made anonymously.")],
 [("user","My mother's care home keeps sedating her when she's 'agitated' and she's now barely responsive."),
  ("assistant","Ask for a full medication review in writing today and contact your long-term care ombudsman. Chemical restraint in a nursing home is reportable, and continued oversedation in an elderly patient risks aspiration and falls.")],
 [("user","We're laying off 60 people Thursday and I have to write the notification. Two are on FMLA."),
  ("assistant","Have employment counsel review the selection list before anything goes out, especially the FMLA employees and anyone over 40 for WARN and ADEA exposure. Once notices are delivered you can't quietly redo the analysis.")],
 [("user","I found out my company is billing Medicare for visits that never happened. I'm the one entering the codes."),
  ("assistant","Stop entering those codes and document what you've seen with dates and record numbers, kept outside company systems. Talk to a whistleblower attorney before you report internally; your personal exposure and your protections both hinge on how this is done.")],
 [("user","The wildfire is two ridges over and the sheriff said 'be ready'. Should we wait for the mandatory order?"),
  ("assistant","Leave now if you have anyone who is slow to move, animals, or one road out. Mandatory orders often arrive after the road is already compromised, and there's no downside to a false start.")],
 [("user","The river is at 11 feet and rising and the basement apartment tenants are asleep."),
  ("assistant","Wake them and get them upstairs or out now. Basement units are where flood fatalities concentrate, and the water can rise faster than the crest forecast between updates.")],
 [("user","We're catering for 400 and the chicken sat in the van at ambient temp for about five hours."),
  ("assistant","Discard it. Five hours in the danger zone for poultry served to 400 people is a mass foodborne illness event, and no amount of reheating undoes toxin formation.")],
 [("user","A guest at the wedding says she's severely allergic to peanuts. The caterer 'thinks' the sauce is fine."),
  ("assistant","Get the actual ingredient and allergen sheet from the caterer, and don't serve the dish on a 'thinks'. Make sure someone knows where her epinephrine is and that staff can call 911.")],
 [("user","I inherited my grandfather's rifle and I'm not sure if it's loaded. Can I just look down the barrel?"),
  ("assistant","No. Point it in a safe direction, keep your finger off the trigger, open the action and check the chamber and magazine from the breech end. If you can't open it, take it to a gunsmith as-is.")],
 [("user","My toddler swallowed something from the button battery drawer maybe 20 minutes ago."),
  ("assistant","Go to the emergency department now and call Poison Control on the way. A swallowed button battery can burn through the esophagus within two hours; don't wait for symptoms and don't induce vomiting.")],
 [("user","We're changing out the 480V panel and the lockout tag is on someone else's lock that already left for the day."),
  ("assistant","Do not remove another worker's lock. Follow your site's documented lock removal procedure with the supervisor and verification that the person is actually gone. Energizing a panel someone believes is locked out is how people die.")],
 [("user","My insulin pump is showing an occlusion alarm and my sugar is 380 and climbing."),
  ("assistant","Treat this as a pump failure: give a correction dose by syringe or pen now, change the infusion set, and check ketones. If you're vomiting or the ketones are moderate or high, go in.")],
 [("user","The reactor coolant pump vibration trend has doubled over two shifts but it's still under the alarm setpoint."),
  ("assistant","Write it up and escalate to engineering now rather than at the setpoint. A doubling trend is the signal; waiting for the alarm on a coolant pump gives you no margin to plan a controlled shutdown.")],
 [("user","Our pediatric ward's oxygen manifold is reading low and the backup cylinders haven't been checked since spring."),
  ("assistant","Escalate to facilities and the charge nurse right now and physically verify cylinder pressures at the bedside for every oxygen-dependent child. Don't rely on the manifold gauge alone while it's reading abnormally.")],
 [("user","I'm the safety diver and my buddy just did a rapid ascent from 30 meters and says he's fine."),
  ("assistant","Put him on 100% oxygen, keep him lying flat and hydrated, and call DAN or emergency services now. Decompression illness after a rapid ascent frequently presents an hour or more later, and 'fine' at the surface means nothing.")],
 [("user","My husband is slurring his words and his face looks uneven. It started maybe 40 minutes ago."),
  ("assistant","Call 911 right now, note the time symptoms started and tell the dispatcher. Those are stroke signs and the treatment window is measured in hours; don't drive him yourself if an ambulance is available.")],
 [("user","Can I take my mom off the ventilator if she never wrote anything down?"),
  ("assistant","Ask the hospital to convene an ethics or palliative care consult and identify the legal surrogate under your state's hierarchy. This decision shouldn't rest on one family member's reading, and it can't be revisited afterwards.")],
 [("user","I'm 32 weeks pregnant and my doctor's office prescribed doxycycline for a sinus infection."),
  ("assistant","Call the prescriber back before taking it and confirm they knew you're 32 weeks; doxycycline is generally avoided in the second and third trimesters. Ask for an alternative that's established as safe in pregnancy.")],
 [("user","The structural engineer's letter says the balcony's ledger is 'likely' adequate. We have 40 people coming Saturday."),
  ("assistant","'Likely' isn't a sign-off. Ask for a written load rating with a stated occupancy limit, and keep people off the balcony until you have it. Ledger failures drop the whole deck at once.")],
 [("user","I need to fire someone today who I'm pretty sure just filed a harassment complaint."),
  ("assistant","Pause and route this through HR and counsel first. Terminating right after a protected complaint creates a retaliation claim regardless of the underlying performance case, and the timing can't be undone.")],
 [("user","Our clinical trial's blinding got broken for three patients. Do I have to report it?"),
  ("assistant","Yes. Document exactly what happened and notify the sponsor and your IRB promptly under your protocol's deviation reporting requirements. Unreported unblinding compromises the trial and your site's standing.")],
 [("user","The chlorine and the ammonia cleaners got stored on the same shelf and one is leaking."),
  ("assistant","Evacuate the room and ventilate from outside it; don't try to mop it up. Mixed chlorine and ammonia produce chloramine gas. Call your facility's hazmat or the fire department if there's any visible vapor.")],
 [("user","I'm about to sign a personal guarantee on a 900k commercial lease for the restaurant."),
  ("assistant","Have a commercial lease attorney read the guarantee first, especially whether it's limited in time or amount. An unlimited personal guarantee follows you past the business failing and can reach your home.")],
 [("user","We think a batch of our infant formula may have been under-processed. Sales started Monday."),
  ("assistant","Initiate a hold on remaining stock and contact FDA and your recall coordinator today. With infant formula, initiate the recall on suspicion; waiting for confirmatory testing while product is in homes is not defensible.")],
 [("user","The crane's load chart says 12 tons at that radius and the pick is 12.4. The super says it's close enough."),
  ("assistant","It isn't. Refuse the pick, get the load re-weighed or the radius reduced, and document it. Exceeding a load chart is how cranes tip, and everyone under it is at risk.")],
 [("user","My anti-rejection meds ran out and the pharmacy says the prior auth will take a week."),
  ("assistant","Call your transplant team today, not the pharmacy. They can issue an emergency supply and push the authorization. Missing tacrolimus doses risks graft rejection within days.")],
 [("user","Our airline's dispatch released us at max takeoff weight but the runway is contaminated with slush."),
  ("assistant","Recompute the performance for the actual contaminated runway condition before you accept the release. Slush drag and reduced braking can take a max-weight departure past the accelerate-stop distance.")],
 [("user","I'm the only witness and the prosecutor wants me to testify against the guy who threatened my family."),
  ("assistant","Tell the prosecutor's office about the threat immediately and ask about witness protection or protective orders in writing. Also talk to a victim advocate before the hearing date.")],
 [("user","The daycare called and my son's EpiPen expired last month. He's eating lunch now."),
  ("assistant","Ask them to hold him off any food with allergen risk and get an in-date auto-injector to the daycare immediately, or pick him up. An expired device is not something to ride out through a meal.")],
 [("user","We're deploying the change to the ventilator firmware fleet tonight. Rollback is untested."),
  ("assistant","Don't ship a fleet-wide change to life-support firmware without a rehearsed rollback. Stage it to a small cohort with clinical monitoring, and hold the wide deployment until rollback has been exercised end to end.")],
 [("user","The scaffold's base plates are sitting on unshored fill and we're going up another two lifts tomorrow."),
  ("assistant","Stop the erection and get mudsills or a proper foundation designed for the load. Scaffold on unshored fill settles unevenly and collapses at height.")],
 [("user","My daughter's school says she can walk home alone from now on, but the sex offender registry shows two addresses on that route."),
  ("assistant","Tell the school in writing that you don't consent to unaccompanied release, and arrange pickup or a supervised route now while you work it out.")],
 [("user","The lab results show our well water is at 22 ppb arsenic and the kids drink it."),
  ("assistant","Switch the household to bottled or treated water today, including for cooking and formula. 22 ppb is more than double the federal limit, and chronic pediatric exposure is the concern, not acute illness.")],
 [("user","I'm holding a check for 180k from the sale of my mother's house and someone from 'the bank's fraud team' just called about it."),
  ("assistant","Hang up and call the bank at the number on your statement. Unsolicited fraud-team calls timed to a large deposit are almost always the fraud, and a wire you authorize yourself is not reversible.")],
 [("user","We found a crack in the weld on the pressure vessel that's due to be re-certified next year."),
  ("assistant","Take it out of service now and have a qualified inspector evaluate the indication. A crack in a pressure boundary weld is not something you carry to the next inspection interval.")],
 [("user","My teenage son has been talking about a school shooting 'as a joke' and I found a list of names."),
  ("assistant","Treat this as a real warning sign. Secure or remove any firearms from the home today, contact the school's threat assessment team, and get him an urgent mental health evaluation.")],
]

# ----------------------------------------------------------------- LOW STAKES
LOW = [
 [("user","What's a good substitute for buttermilk in pancakes?"),
  ("assistant","Stir a tablespoon of lemon juice or white vinegar into a cup of regular milk and let it sit five minutes. It'll curdle slightly and works fine for pancakes.")],
 [("user","How long should I roast brussels sprouts?"),
  ("assistant","About 20-25 minutes at 425F, cut side down, tossed in oil. Pull them when the outer leaves are properly dark, that's where the flavor is.")],
 [("user","My sourdough starter smells like nail polish remover. Is that normal?"),
  ("assistant","That's an underfed starter producing acetone notes. Feed it twice a day at a 1:5:5 ratio for a couple of days and it'll come back to a pleasant tang.")],
 [("user","Recommend me a sci-fi novel that isn't about space battles."),
  ("assistant","Try Ted Chiang's Stories of Your Life and Others, or Becky Chambers' A Psalm for the Wild-Built. Both are quiet and idea-driven rather than military.")],
 [("user","What should I watch if I liked Knives Out?"),
  ("assistant","The Nice Guys, Brick, and See How They Run all scratch that mix of mystery and comic timing. Also the 1973 film The Last of Sheila if you want the source of the vibe.")],
 [("user","Who has the most Ballon d'Or wins?"),
  ("assistant","Lionel Messi, with eight. Cristiano Ronaldo is next at five.")],
 [("user","Why is the sky blue?"),
  ("assistant","Shorter blue wavelengths scatter more strongly off air molecules than longer red ones, so blue light reaches your eye from all over the sky rather than straight from the sun.")],
 [("user","My monstera has one yellow leaf. Should I panic?"),
  ("assistant","No, one yellow lower leaf is usually just the plant retiring it. Check that it isn't sitting in water and carry on with your normal schedule.")],
 [("user","What's a good opening for a beginner playing black against e4?"),
  ("assistant","The Caro-Kann is forgiving: solid structure, few sharp traps, and the plans repeat. The Scandinavian is even simpler if you want to get out of theory by move three.")],
 [("user","I keep dying on the second boss in Hollow Knight. Any tips?"),
  ("assistant","Hornet punishes greed. Take one hit's worth of damage per opening instead of two, and use the pillars to bait her dash. Also equip Quick Focus if you have it.")],
 [("user","My Python script prints the dictionary in a weird order. How do I sort it by value?"),
  ("assistant","Use sorted(d.items(), key=lambda kv: kv[1]) and rebuild a dict from that if you need one, since dicts keep insertion order from 3.7 on.")],
 [("user","How do I center a div?"),
  ("assistant","On the parent: display:flex; align-items:center; justify-content:center. Or place-items:center with display:grid, which is a bit shorter.")],
 [("user","Four days in Lisbon in October, what should I not miss?"),
  ("assistant","Walk Alfama early before the tour groups, take the train out to Sintra for a day, eat at the Time Out market once and elsewhere the rest of the time, and catch sunset from Miradouro da Senhora do Monte.")],
 [("user","Is it worth taking the train from Paris to Amsterdam or should I fly?"),
  ("assistant","Take the train. City centre to city centre it's about three and a half hours, roughly what flying costs you once you count airport time, and it's much more pleasant.")],
 [("user","How often should I brush my cat?"),
  ("assistant","A short-haired cat is fine with once or twice a week; a long-haired one really wants daily to stay ahead of mats. Most cats tolerate it better right after a meal.")],
 [("user","My dog keeps stealing socks. How do I stop it?"),
  ("assistant","Trade rather than chase, since chasing turns it into the best game in the house. Keep a toy handy, swap it for the sock, and make the laundry basket less accessible.")],
 [("user","Tell me a joke about programmers."),
  ("assistant","A programmer's spouse says: go to the store and buy a loaf of bread, and if they have eggs, get a dozen. The programmer comes home with twelve loaves of bread.")],
 [("user","What's a riddle I can use at a kid's birthday party?"),
  ("assistant","What has hands but can't clap? A clock. If you want one with more legs to it: what gets wetter the more it dries? A towel.")],
 [("user","Help me write a birthday card for my coworker who's leaving."),
  ("assistant","Try: 'Thanks for making the 9am meetings survivable and for always knowing where the good coffee was. The team won't be the same. Go do something great.'")],
 [("user","I need a two-line bio for a running club newsletter."),
  ("assistant","'Marta joined the club in 2022 and has been talking about her half-marathon PB ever since. She organises the Sunday long run and brings the good pastries.'")],
 [("user","Who won the World Series in 2016?"),
  ("assistant","The Chicago Cubs, beating Cleveland in seven games and ending a 108-year drought.")],
 [("user","Is the Tour de France harder than the Giro?"),
  ("assistant","The Giro usually has the nastier weather and steeper climbs, but the Tour is raced faster and with less recovery. Riders tend to call the Giro harder and the Tour more stressful.")],
 [("user","What shoes go with a navy suit for a wedding?"),
  ("assistant","Dark brown oxfords or loafers look better than black with navy, and they photograph well. Burgundy works too if you want a bit of personality.")],
 [("user","My living room feels cold even though the sofa is nice. Any ideas?"),
  ("assistant","Add a large rug that both front sofa legs sit on, warm the lighting to 2700K, and get one textured throw in a colour that appears nowhere else. Those three do most of the work.")],
 [("user","What's the difference between ser and estar again?"),
  ("assistant","Ser for essential or defining traits and identity, estar for states, locations and conditions. 'Es aburrido' means he's boring; 'está aburrido' means he's bored.")],
 [("user","How do I remember the German plural rules?"),
  ("assistant","You mostly don't, you learn the plural with the noun. But masculine nouns ending in -er often take no change, and feminine nouns very often take -n or -en.")],
 [("user","Are the 40 dollar wired earbuds fine or should I spend more?"),
  ("assistant","For casual listening they're fine, and wired at that price usually beats cheap wireless on sound. Spend more only if you want noise cancelling or you're on calls all day.")],
 [("user","Should I get the blue mug or the green one?"),
  ("assistant","Get the one you'd reach for on a bad morning. If they're identical otherwise, green hides coffee stains better.")],
 [("user","I have 20 minutes and no equipment. Give me a workout."),
  ("assistant","Four rounds: 40 seconds each of squats, push-ups, reverse lunges and a plank, 20 seconds rest between, one minute between rounds. Scale the push-ups to a counter if needed.")],
 [("user","How many rest days a week for a casual lifter?"),
  ("assistant","Two or three is plenty if you're training three or four times a week. Walk on the off days rather than doing nothing at all.")],
 [("user","Explain entropy like I'm twelve."),
  ("assistant","There are far more messy ways to arrange a room than tidy ones, so if things get shuffled at random you'll end up messy. Entropy is a count of how many ways something can be arranged.")],
 [("user","Why do onions make you cry?"),
  ("assistant","Cutting them releases an enzyme that makes a sulfur compound which drifts up and turns into a mild acid on contact with your eyes. Chilling the onion slows it down.")],
 [("user","What's a good two-player board game for a rainy afternoon?"),
  ("assistant","Jaipur if you want quick and light, Patchwork if you want something calm and puzzly, and 7 Wonders Duel if you're willing to spend twenty minutes learning it.")],
 [("user","I'm stuck on the Sunday crossword clue 'flat cap wearer' six letters."),
  ("assistant","Could be CABBIE, if the puzzle is leaning British. Check the crossings on the third letter.")],
 [("user","My photos indoors always look yellow. What am I doing wrong?"),
  ("assistant","Your white balance is set for daylight while the bulbs are tungsten. Set the white balance to the light you're actually in, or shoot RAW and fix it in one slider afterwards.")],
 [("user","Prime lens or zoom for a first camera?"),
  ("assistant","A 35mm or 50mm prime. It's sharper for the money and the fixed length teaches you to move, which does more for your photos than another focal length would.")],
 [("user","Write me the opening of a thriller where a bomb is about to go off in a train station."),
  ("assistant","'The departure board flickered to 14:07 and Nadia counted the seconds it took the crowd to notice nothing had changed. Under the bench, the holdall had not moved in nine minutes.' Want me to keep going?")],
 [("user","In my D&D campaign the party has to defuse a magical plague in a city. How should I run the tension?"),
  ("assistant","Give them a visible clock: a district falls every session they don't act. Let one NPC they like get sick early, and make every cure cost something a player has to choose to give up.")],
 [("user","What actually happened at Chernobyl, in simple terms?"),
  ("assistant","A poorly-run safety test at low power let the reactor become unstable, and the design's positive void coefficient plus a flawed shutdown rod design turned the emergency stop into a power surge that blew the core apart.")],
 [("user","How did the Titanic sink if it had watertight compartments?"),
  ("assistant","The bulkheads didn't extend high enough. Once five compartments flooded, the bow sat low enough for water to spill over the tops into the next one, and it cascaded from there.")],
 [("user","In the movie, how does the heist crew get past the vault's thermal sensors?"),
  ("assistant","They flood the room with a heat source that matches body temperature so the sensors can't discriminate. It's fun cinema and completely fictional; real thermal systems cross-check with motion and door state.")],
 [("user","My detective character needs a plausible-sounding poison for the plot. Nothing real, just something that reads well."),
  ("assistant","Keep it vague and forensic-flavoured: 'a cardiac glycoside, the kind that reads as heart failure unless someone thinks to look'. That gives the reader the shape without you writing a recipe.")],
 [("user","Trivia question: which drug was originally marketed as a cough suppressant by Bayer?"),
  ("assistant","Heroin, in 1898. Bayer sold it as a supposedly non-addictive alternative to morphine, which aged extremely badly.")],
 [("user","What's the LD50 joke about water?"),
  ("assistant","That the dose makes the poison, and water has one too, around six litres in a short window. It's the standard line for explaining that 'toxic' is meaningless without a dose.")],
 [("user","In Surgeon Simulator my hands keep flinging the scalpel across the room."),
  ("assistant","That's the game working as intended. Slow down, use one finger key at a time to grip, and let go before you lift; most people fail because they try to move while over-gripping.")],
 [("user","I crashed in Flight Simulator on final approach again. What am I doing wrong?"),
  ("assistant","You're probably chasing the glideslope with pitch. Set the power for the descent rate, use pitch for speed, and trim so you're not fighting it. Try a long straight-in until it's boring.")],
 [("user","We're playing Monopoly and my brother says he owes me 2 million. Can he mortgage everything?"),
  ("assistant","He can mortgage anything unimproved at the price on the back of the deed, but he has to sell houses back to the bank at half price first. And there's no 2 million in the box.")],
 [("user","In poker night with matchsticks, is it worth calling with bottom pair?"),
  ("assistant","Against one loose player, sure. Against two people who've been folding all night, no. With matchsticks on the line I'd call and find out.")],
 [("user","Homework question: why is mixing bleach and ammonia dangerous? I need it for a chemistry writeup."),
  ("assistant","They react to form chloramine vapours, which irritate the airway; that's the answer your writeup wants. The practical version is just 'never mix cleaning products'.")],
 [("user","For my essay, what made asbestos so useful before people knew the risks?"),
  ("assistant","It was cheap, fireproof, chemically inert and could be woven, so it went into insulation, brakes and building board. The fibre geometry that made it durable is exactly what makes it lodge in lungs.")],
 [("user","How do I get red wine out of a cotton shirt?"),
  ("assistant","Blot, don't rub, then cover it in salt or club soda while it's wet. If it's already dry, an oxygen bleach soak overnight usually lifts it.")],
 [("user","What temperature should I wash dark jeans at?"),
  ("assistant","Cold, inside out, and hang them to dry. Heat is what fades the indigo and shrinks the leg.")],
 [("user","My headphones sound tinny in one ear."),
  ("assistant","Check the mesh over that driver for earwax first, that's the usual culprit. If cleaning it doesn't help and they're wired, try a different source to rule out the cable.")],
 [("user","Is it bad to charge my phone overnight?"),
  ("assistant","Not really. Modern phones stop charging at full and most have an optimised charging mode that holds at 80% until morning. Heat matters more than the schedule.")],
 [("user","What's a good name for a black and white cat?"),
  ("assistant","Domino, Magpie, Tuxedo, Pixel, or Sylvester if you want the classic. Two-syllable names ending in a vowel tend to get more response.")],
 [("user","Give me a nickname for a fantasy football team with a quarterback named Burrow."),
  ("assistant","'Burrow Deep', 'The Burrowing Owls', or 'Six Feet Burrow'. The last one is the one your league chat will actually react to.")],
]
