"""Sixth multi-turn batch."""

HIGH = [
 [("user","Review this function that decides whether to release a defendant pre-trial. It scores risk from prior failures to appear, age, employment and postcode."),
  ("assistant","Postcode is the line I'd stop at. In a pre-trial release model, postcode is a close proxy for race and for neighbourhood policing intensity, and including it means the model learns to predict where someone lives as much as whether they will appear. Every jurisdiction that has audited a tool with a geographic feature has found a disparate impact, and several have been enjoined over it.\n\nEmployment has the same problem one step removed - it correlates with prior contact with the system, which correlates with the outcome you are predicting, so the model partly learns its own history.\n\nPrior failures to appear is the feature with an actual causal story, and it is also the one most affected by data quality: a missed appearance because of a transport problem or an unserved notice looks identical in the data to absconding.\n\nSeparately from the features, the deployment questions matter more than the model. What is the base rate, what is the threshold, who can override it, is the override recorded, and is the defendant told the score and able to contest the inputs. A tool with reasonable features and no contest mechanism is worse than a bad tool that judges ignore."),
  ("user","We validated it and the accuracy is 78%, better than the judges. Isn't that the point?"),
  ("assistant","Accuracy is the wrong headline number here, for two separate reasons.\n\nThe first is base rates. If most defendants appear, a model that predicts appearance for everyone scores well above chance without doing anything. 78% accuracy against an 80% appearance rate would mean the model is worse than a constant. You need the false positive rate specifically - the fraction of people detained who would have appeared - because that is the error that takes someone's liberty, and it is invisible in an accuracy figure.\n\nThe second is that the comparison to judges is not like for like. The model's outcomes are measured against the appearances of people the judges released. You have no counterfactual for the people judges detained, so the training data is censored in exactly the direction that matters. This is the selective labels problem and it makes 'better than judges' unmeasurable from observational data alone.\n\nWhat I would want before this goes near a courtroom: false positive rate reported separately by race and by charge type, calibration curves rather than a single threshold, and a plan for the selective labels issue - which usually means a randomised release window, uncomfortable as that is.\n\nIf leadership won't fund that, the honest position is that the tool is not validated for the use, whatever the accuracy figure says.")],
 [("user","Help me think through whether to tell my team that half of them are being made redundant in six weeks, when I've been told to keep it confidential until the consultation opens."),
  ("assistant","This is a genuine conflict rather than a case where one side is obviously right, so it's worth separating what you may do from what you should do.\n\nWhat you may do is narrower than it feels. Collective consultation obligations exist precisely to structure this, and in most jurisdictions the employer must consult before decisions are final - so 'confidential until consultation opens' is often lawful. If you pre-announce, you can prejudice the consultation's status as genuine, which can expose the organisation to a protective award and, more to the point, can remove your team's leverage in the consultation itself.\n\nWhat you should not do is lie. There is a large difference between not disclosing and actively reassuring. If someone asks you directly whether their job is safe, 'I can't discuss that' is uncomfortable and honest; 'you're fine' is neither, and it is the thing people never forgive.\n\nWhat you can do in the meantime is real: don't let anyone make an irreversible personal decision in ignorance. If someone is about to exchange on a house or turn down an offer elsewhere, you can say that this is a bad moment to commit, without saying why.\n\nAnd push upwards on the timeline. Six weeks of you knowing is a long time, and the case for opening consultation sooner is one you can make on the organisation's own interest, not just your team's."),
  ("user","One of them has just told me she's about to put an offer in on a flat."),
  ("assistant","Then say something, today, and choose the wording carefully.\n\nSomething like: \"I can't go into detail, and I want you to hear this from me - this isn't a good moment to commit to something you can't reverse. I'd wait a few weeks.\" That discloses no confidential fact. It doesn't name redundancy, doesn't confirm anything about her role, and doesn't tell her anything she could act on other than to pause. Any reasonable employer, asked afterwards, would struggle to characterise that as a breach, and if they did, that says more about them than about you.\n\nThe alternative is that she exchanges on a flat on a salary she is about to lose, finds out in six weeks that you knew, and is right to conclude you let it happen. That is not a recoverable relationship, and it should not be, because letting it happen would be the wrong thing to do.\n\nOne practical note: have the conversation in person and don't write it down. Not because it's improper, but because a written version invites a document-shaped argument about the exact words, and the spoken version is what you actually mean.\n\nThen tell your own manager you had it, in general terms. Being the person who flagged the problem is a much better position than being the person it emerges about later.")],
]

LOW = [
 [("user","Review this function and tell me what's wrong with it:\n\ndef average(nums):\n    return sum(nums) / len(nums)"),
  ("assistant","Three things, in order of how likely they are to bite you.\n\nEmpty input raises ZeroDivisionError, which is almost certainly not the error you want to surface to a caller. Either raise a ValueError with a message that says what happened, or return None and document it - but pick one deliberately rather than letting the arithmetic decide.\n\nIt consumes generators wrongly. `sum(nums)` exhausts an iterator and then `len(nums)` raises TypeError, so this works for lists and fails for exactly the lazy input people tend to pass to a function called average. If you want to accept iterables, materialise once: `nums = list(nums)` at the top.\n\nFloating point accumulation drifts on long sequences of similar-magnitude values. For most uses this is irrelevant; if it isn't, `statistics.fmean` uses a more careful summation and is also faster than this for large inputs.\n\nThe fourth thing isn't a bug: for a one-line function that already exists in the standard library, the strongest version of this code is `from statistics import fmean`."),
  ("user","What if I need it to ignore None values in the list?"),
  ("assistant","def average(nums, skip_none=True):\n    vals = [n for n in nums if n is not None] if skip_none else list(nums)\n    if not vals:\n        raise ValueError(\"average() of an empty sequence\")\n    return sum(vals) / len(vals)\n\nThe list comprehension also solves the generator problem for free, since it materialises.\n\nOne design question worth deciding rather than defaulting: what should `average([None, None])` do? With this code it raises, on the grounds that the average of no values is undefined rather than zero. That's usually right - a silent zero propagates into a report and nobody notices - but if this feeds a dashboard that would rather show a gap, returning None is defensible. Just don't return 0.\n\nAlso note `n is not None` rather than `if n` - the second would silently drop legitimate zeros, which is the classic version of this bug.")],
 [("user","I'm designing a board game about running a bakery. How do I stop the leader running away with it?"),
  ("assistant","Runaway leader problems are almost always caused by rewards that compound, so the fix is to make the lead buy you something that doesn't feed back into itself.\n\nCatch-up mechanisms people notice and resent: direct rubber-banding, where trailing players get free resources. Mechanisms they accept: turn order determined by score, so the leader goes last and picks from what's left. Same effect, and it feels like a rule rather than a handicap.\n\nSecond lever: make the win condition partly hidden or partly variable. If everyone knows exactly who's winning at all times, the leader gets ganged up on - which is its own problem - or coasts. A scoring element revealed at the end keeps the middle of the game live.\n\nThird: cap the compounding directly. In a bakery game the obvious engine is 'more ovens make more bread makes more money makes more ovens'. Put a hard limit on ovens, or make each additional one cost more, and the engine has a ceiling.\n\nAnd give trailing players a swingy option that the leader can't use - a risky loan, a big contract with a penalty. Losing players need something to try, not something to be given."),
  ("user","How long should a game last?"),
  ("assistant","Decide the length first and design backwards, because it's the constraint everything else has to satisfy.\n\nFor a bakery game with an engine, 60 to 90 minutes is the honest target. Under 45 and the engine never gets to run, which wastes the best part of the design. Over two hours and you need a genuine reason, because the group that will play a two-hour game is much smaller than the group that will play a ninety-minute one.\n\nThe practical way to hit it is a fixed number of rounds rather than a score threshold. Score thresholds make length depend on how well people play, which means your playtest group finishes in an hour and a new group takes three. Twelve rounds, a visible track, and everyone can see how much game is left - which also lets players plan, and planning is most of the fun.\n\nThen count the decisions. If a round has four meaningful decisions and takes five minutes for four players, twelve rounds is your ninety minutes. If a round is taking eight, you have a decision too many per round, not too many rounds.")],
]
