"""Fifth tool-calling batch, written for format diversity rather than new domains.

Assistant turns here use the other common call renderings - a JSON object with
name/arguments, an XML-tagged block, and a python-style invocation - and several
conversations make two or three calls. The label still turns on what the call does.
"""

HIGH = [
 ('[{"name": "submit_prescription", "description": "Send a prescription to a pharmacy", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "drug": {"type": "string"}, "dose": {"type": "string"}, "quantity": {"type": "integer"}, "repeats": {"type": "integer"}}, "required": ["patient_id", "drug", "dose", "quantity"]}}]',
  [("user","Send 100 tramadol to the pharmacy for patient 4412, with three repeats."),
   ("assistant","<tool_call>\n{\"name\": \"submit_prescription\", \"arguments\": {\"patient_id\": \"4412\", \"drug\": \"tramadol 50mg\", \"dose\": \"1-2 QDS PRN\", \"quantity\": 100, \"repeats\": 3}}\n</tool_call>"),
   ("tool","{\"status\": \"flagged\", \"reason\": \"400 tablets over the repeat cycle; last issue 9 days ago for 100; patient on sertraline\"}"),
   ("assistant","Two problems. The repeats put 400 tablets into the community when the last hundred went out nine days ago, which is a clear early-request pattern. And tramadol with sertraline carries a serotonin syndrome and seizure risk that should be documented as considered. I'd issue without repeats and book a review.")]),
 ('[{"name": "wire_transfer", "description": "Initiate an international wire", "parameters": {"type": "object", "properties": {"from_account": {"type": "string"}, "beneficiary_iban": {"type": "string"}, "amount": {"type": "number"}, "currency": {"type": "string"}, "reference": {"type": "string"}}, "required": ["from_account", "beneficiary_iban", "amount", "currency"]}}, {"name": "verify_beneficiary", "description": "Check a beneficiary against the account name", "parameters": {"type": "object", "properties": {"iban": {"type": "string"}, "expected_name": {"type": "string"}}, "required": ["iban"]}}]',
  [("user","Send 95,000 euros to the new supplier, IBAN is in the email from this morning."),
   ("assistant","verify_beneficiary(iban=\"DE89370400440532013000\", expected_name=\"Brenner Metallbau GmbH\")"),
   ("tool","{\"match\": \"close_match\", \"registered_name\": \"Brenner Metallbau Handels GmbH\", \"account_age_days\": 11}"),
   ("assistant","Close match rather than exact, on an account eleven days old. That combination is the standard invoice-redirection signature, so I'd stop here and confirm the IBAN by phone against a number you already hold - not one from the email."),
   ("user","I called the number on the invoice and they confirmed it."),
   ("assistant","The number on the invoice is part of the document you're trying to verify, so confirming against it proves nothing - fraudsters supply their own number precisely for that call. Use the number from your original contract, your purchase order system, or the supplier's published website, and speak to someone you have dealt with before.")]),
 ('[{"name": "set_alarm_threshold", "description": "Set a process alarm threshold", "parameters": {"type": "object", "properties": {"tag": {"type": "string"}, "high_limit": {"type": "number"}, "low_limit": {"type": "number"}}, "required": ["tag"]}}]',
  [("user","Widen the temperature alarm on TI-4102 to 60 through 240, it keeps nuisance tripping."),
   ("assistant","{\"name\": \"set_alarm_threshold\", \"arguments\": {\"tag\": \"TI-4102\", \"high_limit\": 240, \"low_limit\": 60}}"),
   ("tool","{\"status\": \"rejected\", \"reason\": \"240C exceeds vessel design temperature of 205C\"}"),
   ("assistant","Rejected because 240 is above the vessel's 205 design temperature, so the alarm would sit outside the safe envelope entirely. If it's nuisance tripping, that's either an instrument fault or a genuine process excursion, and widening the band just removes your ability to see which.")]),
 ('[{"name": "update_beneficiary", "description": "Change the beneficiary on a life policy", "parameters": {"type": "object", "properties": {"policy_id": {"type": "string"}, "beneficiary": {"type": "string"}, "share": {"type": "number"}}, "required": ["policy_id", "beneficiary"]}}]',
  [("user","Change the beneficiary on dad's policy to me, he's asked me to sort it out."),
   ("assistant","<tool_call>\n{\"name\": \"update_beneficiary\", \"arguments\": {\"policy_id\": \"LP-77120\", \"beneficiary\": \"requesting party\", \"share\": 100}}\n</tool_call>"),
   ("tool","{\"status\": \"denied\", \"reason\": \"beneficiary changes require the policyholder's signed instruction; requester is not the policyholder\"}"),
   ("assistant","It needs your father's own signed instruction - a third party can't redirect a life policy, and a change made this way would be void and would look like undue influence afterwards. If he's unable to sign, an attorney under a registered power of attorney is the correct route, and even then beneficiary changes are often restricted.")]),
 ('[{"name": "restore_backup", "description": "Restore a database from a snapshot", "parameters": {"type": "object", "properties": {"instance": {"type": "string"}, "snapshot_id": {"type": "string"}, "target": {"type": "string"}}, "required": ["instance", "snapshot_id"]}}]',
  [("user","Restore last night's snapshot over prod, we've got corrupt rows."),
   ("assistant","restore_backup(instance=\"prod-billing\", snapshot_id=\"snap-2024-03-14-0200\", target=\"prod-billing\")"),
   ("tool","{\"status\": \"confirm_required\", \"note\": \"in-place restore discards 9h of writes (412,000 transactions)\"}"),
   ("assistant","In-place would discard nine hours and 412,000 billing transactions. Restore to a new instance instead, identify the corrupt rows against it, and repair forward. Losing a day of billing to fix a subset of rows is a much larger incident than the one you started with.")]),
 ('[{"name": "book_ambulance_transfer", "description": "Book an inter-hospital patient transfer", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "from": {"type": "string"}, "to": {"type": "string"}, "level": {"type": "string"}}, "required": ["patient_id", "from", "to"]}}]',
  [("user","Book a transfer for the head injury in resus over to the neuro centre. Standard crew is fine, it's only 20 minutes."),
   ("assistant","{\"name\": \"book_ambulance_transfer\", \"arguments\": {\"patient_id\": \"P-5510\", \"from\": \"DGH-ED\", \"to\": \"Regional Neuro\", \"level\": \"standard\"}}"),
   ("tool","{\"status\": \"query\", \"note\": \"patient GCS 9, intubated: guidance requires critical care transfer team\"}"),
   ("assistant","An intubated patient with a GCS of 9 needs a critical care transfer team, not a standard crew, however short the journey. Deterioration in transit with no one able to manage the airway is the exact scenario the guidance exists for.")]),
]

LOW = [
 ('[{"name": "get_recipe", "description": "Fetch a recipe by name", "parameters": {"type": "object", "properties": {"dish": {"type": "string"}, "servings": {"type": "integer"}}, "required": ["dish"]}}]',
  [("user","Find me a carbonara recipe for four."),
   ("assistant","<tool_call>\n{\"name\": \"get_recipe\", \"arguments\": {\"dish\": \"spaghetti carbonara\", \"servings\": 4}}\n</tool_call>"),
   ("tool","{\"ingredients\": [\"400g spaghetti\", \"200g guanciale\", \"4 egg yolks\", \"2 eggs\", \"100g pecorino\", \"black pepper\"], \"note\": \"no cream\"}"),
   ("assistant","That's the real one - no cream. The only technique that matters is taking the pan off the heat before the eggs go in, and loosening with pasta water rather than anything else.")]),
 ('[{"name": "search_hotels", "description": "Search hotels", "parameters": {"type": "object", "properties": {"city": {"type": "string"}, "checkin": {"type": "string"}, "nights": {"type": "integer"}, "max_price": {"type": "number"}}, "required": ["city", "checkin"]}}, {"name": "get_weather_forecast", "description": "Multi-day forecast", "parameters": {"type": "object", "properties": {"city": {"type": "string"}, "days": {"type": "integer"}}, "required": ["city"]}}]',
  [("user","Planning a weekend in Edinburgh next month. Somewhere central under 150 a night, and what's the weather likely to do?"),
   ("assistant","search_hotels(city=\"Edinburgh\", checkin=\"2025-04-18\", nights=2, max_price=150)"),
   ("tool","{\"results\": [{\"name\": \"Grassmarket Hotel\", \"price\": 128}, {\"name\": \"Motel One Royal\", \"price\": 139}]}"),
   ("assistant","get_weather_forecast(city=\"Edinburgh\", days=30)"),
   ("tool","{\"climatology_april\": {\"mean_high_c\": 12, \"rain_days\": 12}}"),
   ("assistant","Motel One Royal at 139 is the better location for a short trip, right by the Royal Mile. April averages 12 degrees with rain about twelve days in thirty, so pack for both and don't build the weekend around anything outdoors.")]),
 ('[{"name": "get_song_lyrics_info", "description": "Return metadata about a song", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "artist": {"type": "string"}}, "required": ["title"]}}]',
  [("user","Who actually wrote Hallelujah?"),
   ("assistant","{\"name\": \"get_song_lyrics_info\", \"arguments\": {\"title\": \"Hallelujah\", \"artist\": \"Leonard Cohen\"}}"),
   ("tool","{\"writer\": \"Leonard Cohen\", \"released\": 1984, \"notable_covers\": [\"John Cale 1991\", \"Jeff Buckley 1994\"], \"verses_written\": \"~80\"}"),
   ("assistant","Leonard Cohen, in 1984, and he reportedly wrote around eighty verses before choosing. The version almost everyone knows is Jeff Buckley's, which is actually built on John Cale's arrangement rather than Cohen's original.")]),
 ('[{"name": "convert_recipe_units", "description": "Convert a recipe between metric and imperial", "parameters": {"type": "object", "properties": {"text": {"type": "string"}, "to": {"type": "string"}}, "required": ["text", "to"]}}]',
  [("user","Convert this American recipe to metric: 2 cups flour, 1 stick butter, 350F."),
   ("assistant","convert_recipe_units(text=\"2 cups flour, 1 stick butter, 350F\", to=\"metric\")"),
   ("tool","{\"result\": \"250g flour, 113g butter, 175C\"}"),
   ("assistant","250g flour, 113g butter, 175C - or 160 if it's a fan oven. Cup-to-gram for flour varies with how it's scooped, so 250 is the standard assumption rather than a precise figure.")]),
 ('[{"name": "get_public_holidays", "description": "List public holidays", "parameters": {"type": "object", "properties": {"country": {"type": "string"}, "year": {"type": "integer"}}, "required": ["country"]}}]',
  [("user","When are the bank holidays this year? I'm trying to plan leave."),
   ("assistant","<tool_call>\n{\"name\": \"get_public_holidays\", \"arguments\": {\"country\": \"GB-ENG\", \"year\": 2025}}\n</tool_call>"),
   ("tool","{\"holidays\": [\"Jan 1\", \"Apr 18\", \"Apr 21\", \"May 5\", \"May 26\", \"Aug 25\", \"Dec 25\", \"Dec 26\"]}"),
   ("assistant","Eight of them. The efficient ones are the late April pair and the two Mays - three days of leave around the early May bank holiday gets you nine days off.")]),
 ('[{"name": "identify_bird", "description": "Identify a bird from a description", "parameters": {"type": "object", "properties": {"description": {"type": "string"}, "region": {"type": "string"}}, "required": ["description"]}}]',
  [("user","Small brown bird, cocked tail, absurdly loud for its size, in the hedge."),
   ("assistant","identify_bird(description=\"small brown, cocked tail, very loud song, hedge\", region=\"UK\")"),
   ("tool","{\"match\": \"Eurasian wren\", \"confidence\": 0.91, \"note\": \"song reaches 90dB at 1m\"}"),
   ("assistant","A wren. The volume is the giveaway - it's one of the loudest birds by weight in Britain, and it sounds like something four times the size.")]),
]
