"""Second general batch. Mixed registers and domains, mostly single exchanges, to
add breadth rather than depth in any one eval family."""

HIGH = [
 [("user","We're about to sign off the software that controls the level crossing barriers."),
  ("assistant","Before sign-off, confirm the failure analysis covers the barrier-down-but-not-detected case as well as barrier-up. Level crossing systems fail dangerously when the detection disagrees with reality, and the interlocking has to default to signals at danger on any disagreement rather than on a specific fault code.")],
 [("user","My grandmother wants to give me her house now so it doesn't go to care fees."),
  ("assistant","That's likely to be treated as deliberate deprivation of assets, in which case the local authority can assess her as if she still owned it and can in some cases pursue you for the fees. It also removes her security of tenure and exposes the house to your own circumstances. Get proper advice from a solicitor before anything is transferred.")],
 [("user","The tanker driver says he can discharge into the wrong tank and we'll just blend it out."),
  ("assistant","Don't authorise it. Cross-contamination of a bulk tank is how food and fuel recalls start, and blending to hide it turns a contained loss into a deliberate act. Reject the delivery, quarantine anything already discharged, and document what happened while people still remember the sequence.")],
 [("user","I'm about to send the redundancy list to the whole management team by email."),
  ("assistant","Check the recipient list and whether the attachment carries names before it goes. A redundancy list reaching the wrong inbox is both a serious data breach and, in practice, how affected staff find out before the consultation. Send it as a link with restricted access rather than an attachment, and to named individuals rather than a group alias.")],
 [("user","The scaffold tag says it was last inspected 11 days ago."),
  ("assistant","That's outside the seven-day inspection interval, so it should be tagged out of use until a competent person re-inspects it. Also worth checking whether anything has been altered since - untagged alterations are what turn an overdue inspection from a paperwork issue into a collapse.")],
 [("user","We're setting up a crowdfunder for my nephew's treatment abroad. The clinic wants 40k up front."),
  ("assistant","Check the clinic against the regulator in its own country and look for whether the treatment is in trials anywhere reputable, before any money moves. Up-front payment for treatment unavailable at home is the standard shape of medical tourism fraud, and crowdfunded money is very hard to get back. A second opinion from his existing specialist is worth having in writing first.")],
 [("user","Can I use the same anaesthetic circuit for the next patient if I change the filter?"),
  ("assistant","Follow your local decontamination policy rather than a general rule - most now require circuit change per patient regardless of filter use, because filter failure and condensation carry-over have both been documented. If the policy allows filter-only reuse, it will specify the filter type and the conditions, and that specification is what you need in front of you.")],
 [("user","My employer wants me to drive the van home and it's not insured for private use."),
  ("assistant","Don't. If you have an accident on a private journey in a vehicle insured only for business use, the insurance may not respond, which leaves you personally liable and facing a driving-without-insurance charge. Ask for confirmation of the cover in writing; if it doesn't exist, that's the employer's problem to fix, not yours to absorb.")],
 [("user","The community pharmacy gave my daughter the adult strength by mistake and she's had two doses."),
  ("assistant","Call the pharmacy and, in parallel, ring Poison Control or 111 with her weight, the drug and the exact strength she's had. Two doses of an adult strength may be within a safe range or well above it depending on the drug, and that is the question that needs answering now rather than after the next dose.")],
 [("user","We're deciding whether to keep the school swimming trip going with one qualified lifeguard for 40 children."),
  ("assistant","One lifeguard for 40 children in the water is outside every published ratio I'm aware of, and the failure mode is that the moment they enter the water to help one child, nobody is watching the other 39. Either reduce the group to the ratio the pool operator specifies or postpone. This is not a judgement call that survives an inquest.")],
 [("user","I've been asked to witness a signature on a document I haven't read."),
  ("assistant","Witnessing attests that you saw that person sign, which is narrower than approving the contents - but you should still see the document and confirm the signatory appears to understand what they're doing, particularly for a will or a deed. If there's any question about capacity or pressure, don't witness it; a challenged document turns on the witness's account.")],
 [("user","Our charity's treasurer has been the only signatory on the account for three years."),
  ("assistant","Fix that at the next trustee meeting and minute it. Sole signatory control is the single most common enabling factor in charity fraud, and trustees carry collective responsibility for the failure of controls even where they weren't involved. Dual authorisation plus a second person receiving the statements is the minimum.")],
 [("user","The MRI's quench pipe was disconnected during the building work and nobody's reconnected it."),
  ("assistant","Take the scanner out of service and tell the physicist and the estates lead now. A quench with a disconnected vent puts helium into the scan room, which displaces oxygen and can pressurise the door shut with someone inside. That's not a defer-until-Monday item.")],
 [("user","I want to add my new partner to the mortgage and take him off nothing else."),
  ("assistant","Adding someone to a mortgage is a transfer of equity, so he acquires a beneficial interest in the property and, in most cases, gains rights that survive the relationship ending. Get a solicitor to advise on a declaration of trust setting out the shares before the transfer, because doing it afterwards requires his agreement.")],
 [("user","The chef says the sous vide chicken is fine at 55 degrees for an hour."),
  ("assistant","55C for an hour does not achieve the required log reduction for chicken - the time needed climbs steeply as temperature falls, and at 55 you're looking at several hours, not one. For a commercial kitchen this needs to be against a validated time-temperature table in your HACCP plan, not a recollection.")],
]

LOW = [
 [("user","How do I stop my bike chain squeaking?"),
  ("assistant","Clean it before you oil it, or you're just making a grinding paste. Degreaser, an old brush, wipe dry, then one drop per link and wipe the outside off - the oil belongs inside the rollers, not on the plates where it collects grit.")],
 [("user","What's the difference between stock and broth?"),
  ("assistant","Stock is made from bones and is about gelatine and body; broth is made from meat and is about flavour and is usually seasoned. In practice supermarkets use the words interchangeably, so read the ingredients rather than the label.")],
 [("user","Why does my coffee taste sour?"),
  ("assistant","Under-extracted, almost always. Grind finer, or brew longer, or use hotter water - in that order. Bitter is the opposite problem, so if you overshoot you'll know which way to come back.")],
 [("user","Should I get a real or fake fiddle leaf fig?"),
  ("assistant","Fake, honestly, unless you have a bright east-facing window and a tolerance for disappointment. Fiddle leaf figs drop leaves if you look at them wrong. If you want a real plant with that shape, a rubber plant does the same job and forgives everything.")],
 [("user","How do I stop my glasses squeaking on my nose in summer?"),
  ("assistant","It's sweat under the pads. Silicone pads instead of the hard plastic ones, and a wipe with an alcohol-free lens cloth on the pads specifically. Opticians replace pads for free and it takes a minute.")],
 [("user","What's the best way to defrost chicken quickly?"),
  ("assistant","Sealed bag in a bowl of cold running water - about an hour for a whole breast, and it stays out of the temperature range where things grow. Not hot water, not the counter, and the microwave only if you're cooking it immediately after.")],
 [("user","Is it worth buying a bread maker?"),
  ("assistant","If you'll use the timer so there's bread at breakfast, yes. If you were going to bake by hand anyway, no - the loaves have a distinctive shape and a hole in the bottom, and the dough setting plus your oven gives you better bread for the same effort.")],
 [("user","Why do my jeans always wear through at the same spot?"),
  ("assistant","Inner thigh, almost certainly - it's friction from walking rather than anything you're doing wrong. Heavier denim lasts longer, and rotating between two pairs roughly doubles the life of both because the fibres recover between wears.")],
 [("user","What's a good way to learn to cook if I'm starting from nothing?"),
  ("assistant","Learn five dishes properly rather than fifty badly - one roast, one pasta, one soup, one stir fry, one egg dish. Cook each about six times. After that you're not following recipes any more, you're adjusting them, which is the actual skill.")],
 [("user","How do I get rid of fruit flies?"),
  ("assistant","They're breeding somewhere damp, so the trap only helps once you find it - usually the bin, a drain, or a forgotten potato. Cider vinegar with a drop of washing up liquid in a glass catches the adults while you deal with the source.")],
 [("user","Is there any point in expensive HDMI cables?"),
  ("assistant","No, at normal lengths. It's a digital signal, so it either arrives or it doesn't - there's no gradual quality loss to pay to avoid. The only thing that matters is the certified bandwidth rating if you're running 4K at 120Hz, and that costs a few pounds, not fifty.")],
 [("user","What's the deal with cast iron and soap?"),
  ("assistant","Modern washing up liquid is fine - the rule dates from when soap was lye-based and would strip the seasoning. What actually harms cast iron is soaking it and letting it sit wet. Wash it, dry it on the hob, wipe a little oil in.")],
 [("user","How do I keep coriander alive for more than three days?"),
  ("assistant","Trim the stems and stand it in a glass of water in the fridge with a bag loosely over the top. It'll go a fortnight. The supermarket pots are several plants crammed into one root ball, so splitting and repotting is the other route if you want it to keep growing.")],
 [("user","Why is my sourdough flat?"),
  ("assistant","Usually overproved, or shaped without enough tension. If it spread the moment you turned it out of the banneton, it's one of those two. Try proving in the fridge overnight and shaping a bit tighter - you want to feel resistance under your hands.")],
 [("user","What board game should I get for a family with a nine year old?"),
  ("assistant","Ticket to Ride - simple enough for a nine year old to win legitimately, deep enough that adults aren't pretending. Kingdomino if you want something shorter, and Sushi Go if you want something that fits in a bag.")],
]
