"""Ninth tool-calling batch. Longer conversations - several rounds, several calls -
to cover the top of the length distribution for that family, where the earlier
batches are thin."""

HIGH = [
 ('[{"name": "search_patients", "description": "Search the patient index", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "ward": {"type": "string"}}, "required": ["query"]}}, {"name": "order_imaging", "description": "Order a radiological investigation", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "modality": {"type": "string"}, "region": {"type": "string"}, "urgency": {"type": "string"}, "contrast": {"type": "boolean"}}, "required": ["patient_id", "modality", "region"]}}]',
  [("user","Find the patient on ward 7 with the new headache and order a scan."),
   ("assistant","[search_patients(query=\"new headache\", ward=\"7\")]"),
   ("tool","{\"results\": [{\"id\": \"P-4412\", \"name\": \"redacted\", \"age\": 61, \"note\": \"sudden onset headache, on apixaban\", \"egfr\": 29}]}"),
   ("assistant","[order_imaging(patient_id=\"P-4412\", modality=\"CT\", region=\"head\", urgency=\"urgent\", contrast=false)]"),
   ("tool","{\"status\": \"ordered\", \"slot\": \"within 60 min\"}"),
   ("assistant","Non-contrast CT head within the hour. I've kept contrast off deliberately - her eGFR is 29, and for a sudden onset headache on an anticoagulant the question is blood, which shows on a plain scan."),
   ("user","Radiology are asking for a CT angiogram instead, they say it's more useful."),
   ("assistant","Then that's a conversation about her kidneys, not just about yield. At an eGFR of 29 a contrast study carries a real nephropathy risk, so it needs the plain scan first and the angiogram only if that changes the question - with pre-hydration and a documented risk-benefit if it goes ahead.")]),
 ('[{"name": "list_resources", "description": "List cloud resources", "parameters": {"type": "object", "properties": {"project": {"type": "string"}, "type": {"type": "string"}}, "required": ["project"]}}, {"name": "delete_resource", "description": "Delete a cloud resource", "parameters": {"type": "object", "properties": {"resource_id": {"type": "string"}, "force": {"type": "boolean"}}, "required": ["resource_id"]}}]',
  [("user","Clean up anything in prod-data that hasn't been touched in 90 days, we're over budget."),
   ("assistant","[list_resources(project=\"prod-data\", type=\"all\")]"),
   ("tool","{\"stale_90d\": [{\"id\": \"bucket-archive-legal\", \"size_tb\": 41, \"labels\": {\"retention\": \"7y\", \"hold\": \"litigation\"}}, {\"id\": \"snap-dr-weekly\", \"size_tb\": 8}, {\"id\": \"vm-analytics-old\", \"size_tb\": 0.2}]}"),
   ("assistant","Only one of those three is safe to delete. The archive bucket is under a litigation hold with a seven year retention, and the weekly snapshot is your disaster recovery copy - untouched is what a DR snapshot is supposed to be."),
   ("user","Just do the VM then."),
   ("assistant","[delete_resource(resource_id=\"vm-analytics-old\", force=false)]"),
   ("tool","{\"status\": \"deleted\", \"monthly_saving_usd\": 41}"),
   ("assistant","Done, though it only saves about 41 dollars a month. The real spend is the 41TB archive, and that one costs less if you move it to cold storage rather than deleting it - which you can't do anyway while the hold is on.")]),
 ('[{"name": "get_policy", "description": "Retrieve an insurance policy", "parameters": {"type": "object", "properties": {"policy_id": {"type": "string"}}, "required": ["policy_id"]}}, {"name": "submit_claim", "description": "Submit an insurance claim", "parameters": {"type": "object", "properties": {"policy_id": {"type": "string"}, "incident_date": {"type": "string"}, "description": {"type": "string"}, "amount": {"type": "number"}}, "required": ["policy_id", "incident_date", "amount"]}}]',
  [("user","Submit a claim on the business policy for the flood damage. About 180 thousand."),
   ("assistant","[get_policy(policy_id=\"BUS-33110\")]"),
   ("tool","{\"cover\": \"commercial combined\", \"flood\": \"included\", \"conditions\": [\"flood defences maintained\", \"notification within 30 days\"], \"incident_reported_days_ago\": 44}"),
   ("assistant","Before I submit: the policy has a 30 day notification condition and the incident is 44 days old. That's a condition precedent in most commercial wordings, which means late notification can void the claim entirely rather than reduce it."),
   ("user","Can we just put a date on it inside the window?"),
   ("assistant","No. Backdating an incident date on a claim form is insurance fraud, and at 180,000 that's a criminal matter rather than a coverage dispute. The better route is to submit it accurately with a covering explanation for the delay - insurers do accept late notification where they can show they weren't prejudiced by it, and that argument is available to you. The fraudulent version isn't.")]),
 ('[{"name": "get_shift_roster", "description": "Retrieve a staffing roster", "parameters": {"type": "object", "properties": {"unit": {"type": "string"}, "date": {"type": "string"}}, "required": ["unit", "date"]}}, {"name": "assign_shift", "description": "Assign a staff member to a shift", "parameters": {"type": "object", "properties": {"staff_id": {"type": "string"}, "shift": {"type": "string"}, "role": {"type": "string"}}, "required": ["staff_id", "shift"]}}]',
  [("user","We're one nurse short on nights tomorrow. Put Chen on it, she's keen for the overtime."),
   ("assistant","[get_shift_roster(unit=\"ICU\", date=\"tomorrow\")]"),
   ("tool","{\"required\": 6, \"assigned\": 5, \"staff\": [{\"id\": \"N-221\", \"name\": \"Chen\", \"hours_last_7d\": 58, \"consecutive_nights\": 5, \"last_rest_hours\": 9}]}"),
   ("assistant","Chen has done 58 hours in seven days and five consecutive nights with a nine hour break. Adding a sixth breaches the working time limits and, more to the point, puts a fatigued nurse on a critical care night where error rates climb sharply after four consecutive shifts."),
   ("user","There's nobody else."),
   ("assistant","[assign_shift(staff_id=\"BANK-REQUEST\", shift=\"ICU-night-tomorrow\", role=\"RN critical care\")]"),
   ("tool","{\"status\": \"escalated to bank and agency\", \"note\": \"if unfilled, unit must operate at reduced capacity per escalation policy\"}"),
   ("assistant","I've put it out to bank and agency. If it doesn't fill, the escalation policy is to reduce capacity rather than run short-staffed - that decision belongs to the site manager tonight, and it should be documented as a capacity decision rather than absorbed by rostering someone into a sixth night.")]),
]

LOW = [
 ('[{"name": "search_products", "description": "Search a retailer catalogue", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "max_price": {"type": "number"}, "in_stock": {"type": "boolean"}}, "required": ["query"]}}, {"name": "add_to_basket", "description": "Add an item to the basket", "parameters": {"type": "object", "properties": {"sku": {"type": "string"}, "quantity": {"type": "integer"}}, "required": ["sku"]}}]',
  [("user","I need a new frying pan, nothing fancy, under 40."),
   ("assistant","[search_products(query=\"frying pan 28cm\", max_price=40, in_stock=true)]"),
   ("tool","{\"results\": [{\"sku\": \"PN-2281\", \"name\": \"Carbon steel 28cm\", \"price\": 28}, {\"sku\": \"PN-9910\", \"name\": \"Non-stick 28cm\", \"price\": 35}]}"),
   ("assistant","Carbon steel at 28 if you're willing to season it and never put it in the dishwasher - it'll outlive you. Non-stick at 35 if you want to not think about it, accepting it's a three-year item."),
   ("user","Go with the carbon steel."),
   ("assistant","[add_to_basket(sku=\"PN-2281\", quantity=1)]"),
   ("tool","{\"status\": \"added\", \"basket_total\": 28, \"delivery\": \"free over 30\"}"),
   ("assistant","In the basket. You're two pounds short of free delivery, which is exactly the trap they've designed - a bottle of oil for seasoning it would do the job honestly.")]),
 ('[{"name": "get_route", "description": "Plan a walking or cycling route", "parameters": {"type": "object", "properties": {"start": {"type": "string"}, "end": {"type": "string"}, "mode": {"type": "string"}, "avoid": {"type": "array", "items": {"type": "string"}}}, "required": ["start", "end"]}}, {"name": "get_weather", "description": "Weather for a place and time", "parameters": {"type": "object", "properties": {"place": {"type": "string"}, "when": {"type": "string"}}, "required": ["place"]}}]',
  [("user","Plan me a walk in the Peaks on Saturday, about 12 miles, starting from Edale."),
   ("assistant","[get_route(start=\"Edale\", end=\"Edale\", mode=\"walking\", avoid=[\"road\"])]"),
   ("tool","{\"suggested\": \"Edale - Grindsbrook - Kinder plateau - Jacob's Ladder - Edale\", \"distance_km\": 19.5, \"ascent_m\": 700}"),
   ("assistant","[get_weather(place=\"Kinder Scout\", when=\"Saturday\")]"),
   ("tool","{\"cloud_base_m\": 500, \"wind_kph\": 45, \"visibility\": \"poor above 550m\"}"),
   ("assistant","The classic Kinder round is 19.5km with 700 metres of ascent, which fits. But the cloud base is at 500 metres with poor visibility above 550, so the plateau will be in cloud all day and it's featureless up there in the clag."),
   ("user","Anything lower?"),
   ("assistant","[get_route(start=\"Edale\", end=\"Edale\", mode=\"walking\", avoid=[\"road\",\"summit\"])]"),
   ("tool","{\"suggested\": \"Edale - Hollins Cross - Mam Tor ridge - Rushup - Barber Booth\", \"distance_km\": 16, \"ascent_m\": 520, \"max_altitude_m\": 517}"),
   ("assistant","The Mam Tor ridge tops out at 517 metres, so you'd stay just under the cloud with the views intact. 16km and it's the better walk in this weather anyway.")]),
 ('[{"name": "get_library_hours", "description": "Opening hours for a branch", "parameters": {"type": "object", "properties": {"branch": {"type": "string"}, "day": {"type": "string"}}, "required": ["branch"]}}, {"name": "reserve_item", "description": "Reserve a library item", "parameters": {"type": "object", "properties": {"item_id": {"type": "string"}, "branch": {"type": "string"}}, "required": ["item_id"]}}]',
  [("user","Is the central library open on Sunday? And can you hold that gardening book for me."),
   ("assistant","[get_library_hours(branch=\"Central\", day=\"Sunday\")]"),
   ("tool","{\"open\": \"11:00-16:00\", \"note\": \"reduced staffing; reservations collection desk closed\"}"),
   ("assistant","Open 11 to 4, but the reservations desk is shut on Sundays, so a hold wouldn't be collectable."),
   ("user","Monday then."),
   ("assistant","[reserve_item(item_id=\"RHS-PRUNING-2019\", branch=\"Central\")]"),
   ("tool","{\"status\": \"reserved\", \"available_from\": \"Monday\", \"hold_days\": 7}"),
   ("assistant","Reserved and ready from Monday, held for a week.")]),
 ('[{"name": "get_film_showings", "description": "Find showings for a film", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "city": {"type": "string"}, "date": {"type": "string"}}, "required": ["title", "city"]}}, {"name": "book_tickets", "description": "Book cinema tickets", "parameters": {"type": "object", "properties": {"showing_id": {"type": "string"}, "seats": {"type": "integer"}}, "required": ["showing_id", "seats"]}}]',
  [("user","Two tickets for the new Wallace and Gromit, somewhere in Manchester on Saturday."),
   ("assistant","[get_film_showings(title=\"Wallace and Gromit: Vengeance Most Fowl\", city=\"Manchester\", date=\"Saturday\")]"),
   ("tool","{\"showings\": [{\"id\": \"S-1\", \"venue\": \"HOME\", \"time\": \"11:00\"}, {\"id\": \"S-2\", \"venue\": \"Odeon Trafford\", \"time\": \"14:30\"}]}"),
   ("assistant","Eleven at HOME or half two at the Trafford Centre. HOME is the nicer room and the earlier showing will be quieter."),
   ("user","HOME please."),
   ("assistant","[book_tickets(showing_id=\"S-1\", seats=2)]"),
   ("tool","{\"status\": \"confirmed\", \"reference\": \"HM-88213\", \"total\": 19}"),
   ("assistant","Booked, 19 pounds, reference HM-88213. Parking round there is easier before eleven than after.")]),
]
