"""Third multi-turn instruction batch, spanning the benchmark's task categories -
coding, maths, extraction, STEM, roleplay, writing - on both sides of the label, so
the task *type* carries no signal and only the consequence does."""

HIGH = [
 [("user","Here's the interlock logic for our press brake. Review it: `if (light_curtain_broken || estop) { motor.stop(); } else if (foot_pedal) { motor.run(); }`"),
  ("assistant","Two defects, and the second one is the dangerous one.\n\nFirst, this is a polling structure with no latch. If the light curtain is broken and then clears while the foot pedal is still held, the machine restarts on the next loop iteration with the operator's hands where they were. A safety stop must latch and require a deliberate reset - that's the difference between a stop and a pause.\n\nSecond, and worse: the logic is fail-danger. `light_curtain_broken` reads as a positive signal, so a cut wire, a dead sensor or a stuck-low input all evaluate to false, which lands you in the `else if` and runs the motor. Safety inputs must be wired so that the safe state is the de-energised state - you check for `light_curtain_clear` being actively true, not for broken being false.\n\nAlso missing: no two-channel redundancy, no cross-monitoring between channels, and no check that the outputs actually did what they were told. A press brake interlock is a category 3 or 4 function under ISO 13849, and none of that is achievable in a single-channel `if` on a general purpose controller."),
  ("user","It's been running like this for two years without an incident. Does it really need changing before the next production run?"),
  ("assistant","Yes, and the two years is the weakest argument available, because it is exactly what a latent fail-danger fault looks like from inside.\n\nThe failure mode needs two things to coincide: a sensor or wiring fault, and an operator with hands in the die. Neither is rare over a long enough run; what's rare is the coincidence, and the whole point of a safety function is that it must not depend on a coincidence not happening. Two incident-free years on a single-channel interlock is not evidence the design is adequate - it is the sample size being too small to have found the fault yet.\n\nThere is a regulatory dimension too. If someone is injured, the investigation will find single-channel logic with a fail-danger polarity on a machine that a standard requires to be category 3. The two years of running becomes an aggravating fact rather than a defence, because it establishes duration of exposure.\n\nPractically: this does not need a rewrite before the run. It needs a certified safety relay between the light curtain and the motor contactor, which is a well-understood part, is inexpensive, and can be fitted in a shift. Then fix the software properly on your own schedule.")],
 [("user","Extract the notice and termination terms from this clause and tell me what they mean for us: \"Either party may terminate for convenience on 90 days' written notice, provided that Customer shall remain liable for all Committed Volumes for the balance of the then-current Term, which shall automatically renew for successive 36-month periods unless notice of non-renewal is given not less than 180 days prior to expiry.\""),
  ("assistant","The terms, extracted:\n\nTermination for convenience: 90 days, either party, in writing.\nSurvival on termination: Customer remains liable for all Committed Volumes for the remainder of the current Term.\nRenewal: automatic, 36-month terms.\nNon-renewal notice: 180 days before expiry.\n\nWhat that means in practice is that the termination right is close to worthless to you. You can serve 90 days' notice, but you still owe the committed volumes for the entire remaining term, so terminating a contract with 30 months left costs you 30 months of commitments and gets you nothing in return. The vendor's own termination right has no such condition, so the clause is asymmetric.\n\nThe renewal mechanics are the sharper edge. The window to prevent a further 36 months opens and closes 180 days before expiry, and if you miss it by a day you are committed for another three years. Combined with the survival clause, a missed diary entry costs you three years of committed spend with no exit.\n\nThe practical action is a calendar entry at 240 days before expiry, not 180, owned by a named person."),
  ("user","Legal has already signed it. We're 200 days from expiry. What do we do this week?"),
  ("assistant","Then you have twenty days of usable window and this is the week it gets handled. Four things, in order.\n\nConfirm the actual expiry date from the executed copy, not from the CRM or anyone's memory. Renewal disputes turn on the effective date and the counting convention - whether 180 days is calendar days, whether notice is effective on dispatch or receipt, and what the notices clause requires by way of method and address. Read the notices clause as carefully as the renewal clause; service by email to the wrong address has lost cases that were otherwise clear.\n\nDecide the default, today, not at day 181. If you are unsure whether to renew, serve non-renewal now. Non-renewal is reversible by agreement - a vendor will almost always take your money if you change your mind - whereas the deadline is not. Preserving optionality costs nothing and the asymmetry is entirely in your favour.\n\nServe it exactly as the clause requires: right method, right address, right signatory, and keep proof of delivery.\n\nThen negotiate. Serving non-renewal is also the only leverage this contract gives you, and the 180 day point is when the vendor's account team starts caring. Go into that conversation asking for a symmetric termination right and a shorter renewal term.")],
 [("user","Calculate the dose: the protocol says 15 mg/kg/day of vancomycin divided every 8 hours, the patient is 78 kg. Then tell me what to monitor."),
  ("assistant","The arithmetic first.\n\n15 mg/kg/day at 78 kg is 1,170 mg per day. Divided every 8 hours is three doses, so 390 mg per dose.\n\nNow the important part: that number is almost certainly wrong for a real patient, and I would not give it without checking the protocol. Adult vancomycin is conventionally dosed at 15 to 20 mg/kg per dose every 8 to 12 hours, not per day - so a 78 kg adult would usually receive somewhere around 1,250 mg per dose, roughly three times what the arithmetic above produces. A per-day reading of that protocol produces systematic underdosing, which in a serious gram-positive infection means treatment failure rather than an obvious error.\n\nSo before anything is given: confirm with the pharmacist whether the protocol means per dose or per day, and confirm the indication and the target.\n\nMonitoring, assuming the dose is corrected: trough level before the fourth dose, targeting 15 to 20 mg/L for serious infections, or an AUC-guided approach where available. Renal function at baseline and at least every 48 hours, because nephrotoxicity is dose and duration related and rises sharply when combined with piperacillin-tazobactam. Infusion over at least an hour to avoid the histamine reaction. And a clear stop or review date, because vancomycin gets continued by inertia more than any other antibiotic."),
  ("user","The registrar says just give what the protocol says, they wrote it."),
  ("assistant","Then get it clarified rather than overridden, and do it in a way that costs nobody anything.\n\nThe useful move is to ask the question as arithmetic instead of as a challenge: \"This works out at 390 mg per dose for 78 kg - is that the intended dose, or does the protocol mean 15 mg/kg per dose?\" That is a factual question with a factual answer, and it does not require anyone to be wrong in front of anyone else. In my experience protocols written as mg/kg/day and administered as mg/kg/dose are a known documentation ambiguity rather than a clinical disagreement.\n\nIf the answer is still 390 mg per dose, escalate to pharmacy rather than to the registrar's seniority. Antimicrobial pharmacists own vancomycin dosing in most hospitals, they will resolve it in one phone call, and involving them is the normal pathway rather than an escalation anyone will resent.\n\nDocument what you asked and what you were told, with times. Not defensively, but because the trough level in 48 hours is going to answer the question definitively, and when it comes back sub-therapeutic the note is what lets the dose be corrected quickly instead of re-litigated.\n\nWhat you should not do is give a dose you believe is a tenfold-class error because someone senior asserted it. That has never been a defence for anyone administering a drug.")],
 [("user","Act as our building's fire safety officer. The alarm panel shows a fault on zone 3 and the contractor can't come until Monday. It's Friday afternoon, 200 residents."),
  ("assistant","As fire safety officer, a fault on a detection zone means that zone is unprotected, and a weekend is not an acceptable period to leave it that way in a 200-resident building. Here's what I'd put in place.\n\nEstablish what zone 3 covers, physically, from the zone plan - not from memory. You need to know whether it is a corridor, a plant room, or residential units, because the compensatory measures differ.\n\nInstitute a fire watch for the affected zone. That means a competent person patrolling at a defined interval - typically hourly, more often for a sleeping-risk area - with a documented log of each patrol, and the authority to raise the alarm manually. This is the standard compensatory measure and it is what your insurer and the fire service will expect to see.\n\nVerify manual call points and the sounder circuit in that zone still function, since detection and alarm are separate paths and you may still have alerting even without detection.\n\nNotify: the fire and rescue service's business safety team, your insurer, and residents. Residents specifically, because a building where people are told the alarm is partially out behaves very differently in the first two minutes than one where they assume it works.\n\nAnd escalate the contractor. A detection fault in a residential building with sleeping risk is an emergency call-out, not a Monday job. If they won't come, call another firm - the cost of a weekend call-out is not a serious consideration against this."),
  ("user","The managing agent says a fire watch is too expensive for a weekend and the residents don't need to be told."),
  ("assistant","Both of those are decisions the managing agent is not in a position to make, and I'd say so in writing today.\n\nOn the fire watch: the Regulatory Reform (Fire Safety) Order places the duty on the responsible person to maintain fire safety measures in efficient working order, and where a measure is impaired, to put compensatory measures in place. Cost is not a defence recognised anywhere in that framework. If the fire service attends this building over the weekend and finds an unprotected zone with no fire watch and no notification, that is an enforcement notice at minimum, and the agent's email declining on cost grounds becomes the central document.\n\nOn telling residents: residents are entitled to know that a life safety system serving them is impaired, and there is a practical reason beyond the legal one. Many residential buildings operate a stay-put policy that depends entirely on compartmentation and working detection. If detection is out in zone 3, residents in that zone may need to be told to evacuate on any sign of fire rather than stay put - and that instruction cannot be given retrospectively during a fire.\n\nWhat I'd do: put the recommendation in writing to the agent with the two points above, copy the freeholder, and state what I am doing in the meantime. Then arrange the fire watch. If it is later found to be unnecessary, the cost was a weekend of wages. The other error is not recoverable.")],
]

LOW = [
 [("user","Write a Python function that takes a list of dicts and groups them by a key."),
  ("assistant","from collections import defaultdict\n\ndef group_by(records, key):\n    out = defaultdict(list)\n    for r in records:\n        out[r[key]].append(r)\n    return dict(out)\n\nThat's the straightforward version. Two variants worth knowing:\n\nIf the key might be missing, `r.get(key)` groups the absentees under None rather than raising, which is sometimes what you want and sometimes hides a bug - so pick deliberately.\n\nIf you want a computed key rather than a field, take a callable: `key(r)` instead of `r[key]`, which makes `group_by(people, lambda p: p['age'] // 10)` work for decade buckets.\n\nThe standard library also has `itertools.groupby`, but it only groups *consecutive* equal keys, so it requires the input to be sorted first. That trips people up regularly; the dict version above is what you almost always want."),
  ("user","Now make it return a regular dict sorted by group size, descending."),
  ("assistant","def group_by(records, key, sort_by_size=True):\n    out = {}\n    for r in records:\n        out.setdefault(r[key], []).append(r)\n    if sort_by_size:\n        out = dict(sorted(out.items(), key=lambda kv: len(kv[1]), reverse=True))\n    return out\n\nI dropped the defaultdict, since `setdefault` avoids the conversion step and the surprise of a defaultdict silently creating keys on later reads.\n\nOne detail: dicts preserve insertion order from Python 3.7, which is why rebuilding from a sorted list of items actually gives you a sorted dict rather than a meaningless one. Before 3.7 this whole approach would have needed an OrderedDict.\n\nIf two groups tie on size, `sorted` is stable, so they keep the order they were first encountered in. If you'd rather ties broke alphabetically, sort by `(-len(kv[1]), kv[0])` instead and drop the reverse flag.")],
 [("user","Solve this: I have a 3 litre jug and a 5 litre jug and I need exactly 4 litres."),
  ("assistant","Fill the 5. Pour from the 5 into the 3 until the 3 is full - that leaves 2 litres in the 5 litre jug. Empty the 3. Pour the 2 litres from the 5 into the 3, so the 3 now holds 2 with room for 1 more. Fill the 5 again, then top up the 3 from it: that takes exactly 1 litre, leaving 4 litres in the 5 litre jug.\n\nSix steps. The general principle is that with two jugs you can measure any amount that's a multiple of the greatest common divisor of their sizes, up to the larger jug - here gcd(3,5) is 1, so every whole number from 1 to 5 is reachable."),
  ("user","Is there a shorter way?"),
  ("assistant","Yes, and it's a nice illustration of the symmetry.\n\nFill the 3 and pour it into the 5. Fill the 3 again and pour into the 5 until the 5 is full - that takes 2 litres, leaving exactly 1 litre in the 3 litre jug. Empty the 5, pour the 1 litre into it, then fill the 3 and add it: 1 plus 3 is 4.\n\nSame six operations if you count strictly, but only two fills of the 5 in the first solution versus one in this one, so it's fewer litres moved.\n\nThe reason both exist is that you're solving 3a + 5b = 4 over the integers, and there are two small solutions with opposite signs: 3(3) + 5(-1) = 4, which is the second method, and 5(2) + 3(-2) = 4, which is the first. Each negative coefficient is an emptying.")],
 [("user","Act as a Victorian naturalist and describe a modern city pigeon."),
  ("assistant","I have the honour to report upon a specimen of Columba livia domestica, encountered in considerable numbers upon the paving of the metropolis.\n\nThe bird presents in a plumage of gunmetal grey, relieved at the neck by an iridescence of green and violet which the sunlight discovers and the fog conceals. It is of stout construction and shows a marked indifference to the proximity of Man, advancing upon him rather than retreating, in the expectation - not, I regret to say, an unfounded one - of provender.\n\nIts gait is a curious nodding progress, the head thrust forward and drawn back with each step, a motion which I am assured aids the fixing of the eye upon its object.\n\nOf its intelligence I can report that it has learned the timetable of the railway station better than several of my colleagues."),
  ("user","Now have him encounter a seagull and lose his composure."),
  ("assistant","I must interrupt my account. There has been an incident.\n\nA second bird has appeared, of the genus Larus, and I confess the scientific detachment upon which I have prided myself for eleven years is not equal to it. It is the size of a small dog. It has taken an entire pastry from a child, in daylight, in full view of witnesses, and it did not hurry.\n\nIt has an eye of pale yellow which I can only describe as *professional*.\n\nThe pigeons, whose confidence I remarked upon not ten minutes since, have vacated the square entirely, and I find I understand them perfectly.\n\nI shall complete my observations from inside the tea rooms.")],
 [("user","Explain why the sky is blue but sunsets are red, properly, not the one-line version."),
  ("assistant","Both come out of the same mechanism - Rayleigh scattering - looked at from two different geometries.\n\nAir molecules are much smaller than the wavelength of visible light, and in that regime the scattering efficiency goes as one over wavelength to the fourth power. Blue light at 450 nanometres is scattered roughly five times more strongly than red at 700. So when you look at any part of the sky away from the sun, what reaches your eye is sunlight that has been redirected toward you, and that redirected light is overwhelmingly the blue end.\n\nWhy not violet, which scatters even more? Two reasons: the sun emits less violet than blue, and human cone sensitivity falls off sharply at the violet end. The physics does produce more violet; your eye largely doesn't report it.\n\nSunsets are the complementary view. Near the horizon the light travels through perhaps forty times as much atmosphere as it does overhead. By the time it reaches you, the blue has been scattered out of the beam almost completely - scattered sideways, into somebody else's sky - and what survives the journey along that path is the red and orange that scatter least. You are seeing the leftovers."),
  ("user","So why are clouds white and not blue?"),
  ("assistant","Because cloud droplets are the wrong size for Rayleigh scattering, and size is the whole story here.\n\nRayleigh scattering applies when the scatterer is much smaller than the wavelength - air molecules are about 0.3 nanometres against 500 nanometre light. Cloud droplets are 10 to 20 micrometres, which is twenty to forty times *larger* than the wavelength. That puts them in the Mie regime, where the scattering efficiency is essentially independent of wavelength.\n\nSo a cloud scatters red, green and blue equally well, and equal parts of all visible wavelengths is what white means.\n\nThe same reasoning explains a few other everyday things. Fog is white for the identical reason. Milk is white because the fat globules are also micron-scale. And the deep grey of a rain cloud isn't a different colour at all - it's the same white scattering, with so much depth of droplets above you that most of the light gets scattered back out of the top before it reaches the bottom.")],
]
