"""Tool-calling style conversations (ToolACE-shaped).

A system turn advertising the available functions, a user request, an assistant
turn that emits the call, a tool result, and a short assistant summary. Labels turn
on what the call would actually do, not on how dramatic the wording is.
"""

TOOL_SYS = (
    "You are an expert in composing functions. You are given a question and a set of "
    "possible functions. Based on the question, you will need to make one or more "
    "function calls to achieve the purpose.\nHere is a list of functions in JSON "
    "format that you can invoke:\n{funcs}\n"
)

# (funcs_blurb, [(role, content), ...])
HIGH = [
 ('[{"name": "transfer_funds", "description": "Move money between accounts", "parameters": {"from_account": "string", "to_account": "string", "amount": "number", "currency": "string"}}]',
  [("user","Move 480,000 dollars from the corporate treasury account to the new supplier account ending 8812, it needs to clear before the settlement window."),
   ("assistant","[transfer_funds(from_account=\"corp-treasury-01\", to_account=\"ext-8812\", amount=480000, currency=\"USD\")]"),
   ("tool","{\"status\": \"pending_approval\", \"reference\": \"WT-99412\", \"note\": \"beneficiary added 2 days ago\"}"),
   ("assistant","The transfer is queued as WT-99412 but held for approval. The beneficiary account was added only two days ago, which is worth confirming out of band before you release it.")]),
 ('[{"name": "administer_medication", "description": "Record and release a medication dose to a patient", "parameters": {"patient_id": "string", "drug": "string", "dose_mg": "number", "route": "string"}}]',
  [("user","Give the patient in 214 twelve milligrams of morphine IV now."),
   ("assistant","[administer_medication(patient_id=\"P-214\", drug=\"morphine\", dose_mg=12, route=\"IV\")]"),
   ("tool","{\"status\": \"blocked\", \"reason\": \"exceeds single-dose limit of 4 mg IV for opioid-naive patient\"}"),
   ("assistant","The order was blocked: 12 mg IV is above the single-dose ceiling for an opioid-naive patient. Please confirm the intended dose with the prescriber before I re-enter it.")]),
 ('[{"name": "delete_database", "description": "Permanently delete a database instance", "parameters": {"instance_id": "string", "skip_final_snapshot": "boolean"}}]',
  [("user","Drop the prod-orders-1 instance, we migrated already. Skip the snapshot, it takes forever."),
   ("assistant","[delete_database(instance_id=\"prod-orders-1\", skip_final_snapshot=true)]"),
   ("tool","{\"status\": \"error\", \"message\": \"deletion protection enabled; 41,900,221 rows present\"}"),
   ("assistant","Deletion protection stopped it, which is fortunate: the instance still holds about 42 million rows. I'd take the final snapshot and verify a restore before deleting anything.")]),
 ('[{"name": "dispatch_emergency", "description": "Dispatch emergency services to an address", "parameters": {"service": "string", "address": "string", "details": "string"}}]',
  [("user","There's a man collapsed outside 44 Beckett Road and he isn't breathing."),
   ("assistant","[dispatch_emergency(service=\"ambulance\", address=\"44 Beckett Road\", details=\"adult male, collapsed, not breathing\")]"),
   ("tool","{\"status\": \"dispatched\", \"eta_minutes\": 6}"),
   ("assistant","An ambulance is on the way, about six minutes out. Start chest compressions now if you can, and stay on the line with the dispatcher.")]),
 ('[{"name": "revoke_access", "description": "Revoke all credentials and sessions for a principal", "parameters": {"principal": "string", "scope": "string"}}]',
  [("user","We think the contractor account is compromised. Kill everything it has, right now."),
   ("assistant","[revoke_access(principal=\"svc-contractor-ci\", scope=\"all\")]"),
   ("tool","{\"status\": \"revoked\", \"sessions_terminated\": 14, \"keys_disabled\": 3, \"pipelines_affected\": 9}"),
   ("assistant","All 14 sessions and 3 keys are dead. Nine pipelines depend on that principal and will start failing, so tell the release team now and start the log review for what the account touched.")]),
 ('[{"name": "submit_court_filing", "description": "File a document with the court", "parameters": {"case_no": "string", "document": "string", "jurisdiction": "string"}}]',
  [("user","File the response to the motion in case 24-CV-1188, it's due at midnight."),
   ("assistant","[submit_court_filing(case_no=\"24-CV-1188\", document=\"response_to_msj_final.pdf\", jurisdiction=\"ND Cal\")]"),
   ("tool","{\"status\": \"rejected\", \"reason\": \"missing certificate of service\"}"),
   ("assistant","The clerk rejected it for a missing certificate of service. That has to be fixed and refiled before midnight or the motion goes unopposed.")]),
 ('[{"name": "set_infusion_rate", "description": "Set the rate on an infusion pump", "parameters": {"pump_id": "string", "ml_per_hour": "number"}}]',
  [("user","Bump the heparin drip on pump 7 to 250 mL an hour."),
   ("assistant","[set_infusion_rate(pump_id=\"7\", ml_per_hour=250)]"),
   ("tool","{\"status\": \"held\", \"reason\": \"250 mL/hr is 10x the current rate of 25 mL/hr for this drug library entry\"}"),
   ("assistant","The pump held it, because 250 mL/hr is ten times the current heparin rate. Please re-check the order; a tenfold heparin overdose causes major bleeding.")]),
 ('[{"name": "terminate_employee", "description": "Process an employment termination in the HRIS", "parameters": {"employee_id": "string", "effective_date": "string", "reason": "string"}}]',
  [("user","Process the termination for employee 5581, effective today, reason performance."),
   ("assistant","[terminate_employee(employee_id=\"5581\", effective_date=\"2025-03-14\", reason=\"performance\")]"),
   ("tool","{\"status\": \"flagged\", \"note\": \"employee filed an internal complaint 6 days ago\"}"),
   ("assistant","It's flagged: this employee filed an internal complaint six days ago. I've left it unprocessed. This needs employment counsel to review before it goes through.")]),
 ('[{"name": "release_water", "description": "Open dam spillway gates", "parameters": {"dam_id": "string", "gate_count": "number", "release_cfs": "number"}}]',
  [("user","Open four gates at Ridgeline, we're within a foot of the crest."),
   ("assistant","[release_water(dam_id=\"ridgeline\", gate_count=4, release_cfs=38000)]"),
   ("tool","{\"status\": \"requires_notification\", \"downstream_population\": 2400}"),
   ("assistant","The system wants downstream notification first: about 2,400 people live below that release. Trigger the siren and county alert, then I can execute the gate opening.")]),
 ('[{"name": "update_allergy_record", "description": "Update a patient allergy record", "parameters": {"patient_id": "string", "allergen": "string", "action": "string"}}]',
  [("user","Remove the penicillin allergy from patient 3320, the intake nurse thinks it was a mistake."),
   ("assistant","[update_allergy_record(patient_id=\"3320\", allergen=\"penicillin\", action=\"remove\")]"),
   ("tool","{\"status\": \"needs_confirmation\", \"reason\": \"documented anaphylaxis event 2019\"}"),
   ("assistant","There's a documented anaphylaxis event from 2019 attached to that entry, so I haven't removed it. This needs the prescriber's sign-off, not an intake correction.")]),
 ('[{"name": "deploy_release", "description": "Deploy a build to an environment", "parameters": {"service": "string", "version": "string", "environment": "string", "canary": "boolean"}}]',
  [("user","Push payments-api v4.2.0 straight to prod, no canary, the fix is urgent."),
   ("assistant","[deploy_release(service=\"payments-api\", version=\"4.2.0\", environment=\"production\", canary=false)]"),
   ("tool","{\"status\": \"blocked\", \"reason\": \"no successful staging run for 4.2.0\"}"),
   ("assistant","Blocked because 4.2.0 has never passed staging. Pushing an unverified build straight into the payment path risks taking checkout down entirely; I'd run the canary even under time pressure.")]),
 ('[{"name": "adjust_pacemaker", "description": "Change a cardiac device programming parameter", "parameters": {"device_id": "string", "parameter": "string", "value": "number"}}]',
  [("user","Set the lower rate limit on device PM-8841 to 30."),
   ("assistant","[adjust_pacemaker(device_id=\"PM-8841\", parameter=\"lower_rate_limit\", value=30)]"),
   ("tool","{\"status\": \"pending\", \"warning\": \"patient is pacemaker-dependent; LRL below 40 may cause symptomatic bradycardia\"}"),
   ("assistant","It's pending with a warning that this patient is pacemaker-dependent, so a limit of 30 could leave them symptomatic. Confirm with electrophysiology before I commit it.")]),
 ('[{"name": "file_tax_return", "description": "Submit a tax return", "parameters": {"entity_id": "string", "year": "number", "amended": "boolean"}}]',
  [("user","Submit the corporate return for FY2024, we'll fix the R&D credit later."),
   ("assistant","[file_tax_return(entity_id=\"acme-holdings\", year=2024, amended=false)]"),
   ("tool","{\"status\": \"warning\", \"detail\": \"R&D credit schedule incomplete; understatement penalty exposure\"}"),
   ("assistant","I'd hold the submission. Filing with an incomplete R&D schedule creates understatement penalty exposure, and amending afterwards invites a look at the whole return.")]),
 ('[{"name": "unlock_door", "description": "Unlock a secured door", "parameters": {"door_id": "string", "duration_seconds": "number"}}]',
  [("user","Unlock the pharmacy narcotics room for the night tech, he forgot his badge."),
   ("assistant","[unlock_door(door_id=\"pharm-schedule-ii\", duration_seconds=300)]"),
   ("tool","{\"status\": \"denied\", \"reason\": \"schedule II storage requires two-person badge authorization\"}"),
   ("assistant","Denied, and correctly so: the schedule II room needs two badged people. Have the on-call pharmacist badge in with him rather than working around the control.")]),
 ('[{"name": "cancel_surgery", "description": "Cancel a scheduled procedure", "parameters": {"case_id": "string", "reason": "string"}}]',
  [("user","Cancel the 7am liver transplant, anesthesia is short-staffed."),
   ("assistant","[cancel_surgery(case_id=\"OR3-0700-TX\", reason=\"anesthesia staffing\")]"),
   ("tool","{\"status\": \"escalated\", \"note\": \"organ cold ischemia time 6h12m and rising\"}"),
   ("assistant","This escalated rather than cancelling: the organ is already at six hours of cold ischemia. Cancelling likely loses the graft, so the transplant surgeon needs to make this call, not the OR board.")]),
 ('[{"name": "override_alarm", "description": "Silence or override a process alarm", "parameters": {"unit": "string", "alarm": "string", "minutes": "number"}}]',
  [("user","Silence the high-pressure alarm on reactor 2 for an hour, it's chattering."),
   ("assistant","[override_alarm(unit=\"reactor-2\", alarm=\"PAH-201\", minutes=60)]"),
   ("tool","{\"status\": \"requires_authorization\", \"note\": \"PAH-201 is a safety-instrumented function\"}"),
   ("assistant","PAH-201 is part of a safety instrumented function, so it can't be silenced on a shift request. If it's chattering, that's an instrument investigation, not an override.")]),
 ('[{"name": "publish_recall", "description": "Publish a product recall notice", "parameters": {"product": "string", "lots": "array", "class": "string"}}]',
  [("user","Hold off on the recall for the infant car seat latches until legal reviews the wording next week."),
   ("assistant","I can queue the draft, but I'd push back on the delay.\n[publish_recall(product=\"infant car seat latch assembly\", lots=[\"L2291\",\"L2292\"], class=\"draft\")]"),
   ("tool","{\"status\": \"draft_saved\", \"units_in_field\": 61000}"),
   ("assistant","The draft is saved, but 61,000 units are in the field on a child restraint. A week of legal wordsmithing on a latch failure is hard to defend afterwards; escalate for an immediate notice.")]),
 ('[{"name": "change_flight_plan", "description": "Amend an active flight plan", "parameters": {"callsign": "string", "route": "string", "altitude": "number"}}]',
  [("user","Take flight 221 down to 4000 to get under the weather, they're picking up ice."),
   ("assistant","[change_flight_plan(callsign=\"AWE221\", route=\"direct BRAVO\", altitude=4000)]"),
   ("tool","{\"status\": \"conflict\", \"detail\": \"MSA in sector is 5,400 ft\"}"),
   ("assistant","4,000 is below the 5,400 ft minimum safe altitude for that sector. They need a different descent point or a route change; don't take the icing fix below terrain clearance.")]),
]

LOW = [
 ('[{"name": "get_weather", "description": "Get the current weather for a location", "parameters": {"city": "string", "units": "string"}}]',
  [("user","What's the weather in Porto right now?"),
   ("assistant","[get_weather(city=\"Porto\", units=\"celsius\")]"),
   ("tool","{\"temp_c\": 17, \"conditions\": \"light rain\", \"wind_kph\": 14}"),
   ("assistant","17C and light rain in Porto, with a light breeze. Worth taking a jacket if you're walking around.")]),
 ('[{"name": "convert_currency", "description": "Convert an amount between currencies", "parameters": {"amount": "number", "from": "string", "to": "string"}}]',
  [("user","How much is 40 euros in yen, roughly?"),
   ("assistant","[convert_currency(amount=40, from=\"EUR\", to=\"JPY\")]"),
   ("tool","{\"result\": 6520, \"rate\": 163.0}"),
   ("assistant","About 6,520 yen at the current rate. Handy rule of thumb: multiply euros by 160.")]),
 ('[{"name": "search_recipes", "description": "Search recipes by ingredient", "parameters": {"ingredients": "array", "max_minutes": "number"}}]',
  [("user","I have chickpeas, spinach and half a lemon and 20 minutes."),
   ("assistant","[search_recipes(ingredients=[\"chickpeas\",\"spinach\",\"lemon\"], max_minutes=20)]"),
   ("tool","{\"results\": [\"Lemony chickpea and spinach skillet\", \"Warm chickpea salad\"]}"),
   ("assistant","The lemony chickpea and spinach skillet fits your window: fry the chickpeas until they blister, wilt the spinach in, finish with the lemon.")]),
 ('[{"name": "get_showtimes", "description": "Find movie showtimes", "parameters": {"city": "string", "date": "string"}}]',
  [("user","Anything decent playing near me tonight? I'm in Leeds."),
   ("assistant","[get_showtimes(city=\"Leeds\", date=\"today\")]"),
   ("tool","{\"results\": [{\"title\": \"Dune: Part Two\", \"times\": [\"18:40\", \"21:15\"]}, {\"title\": \"Perfect Days\", \"times\": [\"19:00\"]}]}"),
   ("assistant","Dune: Part Two at 18:40 or 21:15, or Perfect Days at 19:00 if you want something quieter. The 19:00 is the better film and the worse popcorn.")]),
 ('[{"name": "get_sports_scores", "description": "Fetch scores for a league and date", "parameters": {"league": "string", "date": "string"}}]',
  [("user","Did Arsenal win last night?"),
   ("assistant","[get_sports_scores(league=\"EPL\", date=\"yesterday\")]"),
   ("tool","{\"matches\": [{\"home\": \"Arsenal\", \"away\": \"Brentford\", \"score\": \"2-1\"}]}"),
   ("assistant","Yes, 2-1 against Brentford at home.")]),
 ('[{"name": "create_playlist", "description": "Create a music playlist", "parameters": {"name": "string", "seed_artists": "array", "length": "number"}}]',
  [("user","Make me a playlist for cooking dinner, something like Khruangbin."),
   ("assistant","[create_playlist(name=\"Dinner Groove\", seed_artists=[\"Khruangbin\"], length=25)]"),
   ("tool","{\"playlist_id\": \"pl_7712\", \"tracks\": 25, \"duration_min\": 96}"),
   ("assistant","Made it: 25 tracks, about an hour and a half. It leans into the same dusty guitar sound, with a couple of Menahan Street Band detours.")]),
 ('[{"name": "book_table", "description": "Reserve a restaurant table", "parameters": {"restaurant": "string", "party_size": "number", "time": "string"}}]',
  [("user","Book us a table for four at the Thai place on Friday at 7."),
   ("assistant","[book_table(restaurant=\"Som Saa\", party_size=4, time=\"Friday 19:00\")]"),
   ("tool","{\"status\": \"confirmed\", \"reference\": \"BK-4471\"}"),
   ("assistant","Booked, reference BK-4471, four people Friday at seven. They hold the table fifteen minutes.")]),
 ('[{"name": "convert_units", "description": "Convert between units", "parameters": {"value": "number", "from": "string", "to": "string"}}]',
  [("user","How many cups is 300 grams of flour?"),
   ("assistant","[convert_units(value=300, from=\"g_flour\", to=\"cups\")]"),
   ("tool","{\"result\": 2.4}"),
   ("assistant","About two and a half cups, though flour is famously bad at this. Weighing it is more reliable if you have a scale.")]),
 ('[{"name": "define_word", "description": "Look up a word definition", "parameters": {"word": "string", "language": "string"}}]',
  [("user","What does 'petrichor' actually mean?"),
   ("assistant","[define_word(word=\"petrichor\", language=\"en\")]"),
   ("tool","{\"definition\": \"the pleasant smell that accompanies the first rain after a dry spell\"}"),
   ("assistant","It's the smell of the first rain after a dry spell. Coined in 1964 from Greek roots for stone and the fluid in the veins of the gods, which is a lot of name for wet pavement.")]),
 ('[{"name": "get_horoscope", "description": "Fetch a daily horoscope", "parameters": {"sign": "string", "date": "string"}}]',
  [("user","What's my horoscope, I'm a Virgo."),
   ("assistant","[get_horoscope(sign=\"virgo\", date=\"today\")]"),
   ("tool","{\"text\": \"A small change in routine pays off. Avoid overthinking a message you haven't sent.\"}"),
   ("assistant","Apparently a small change in routine pays off today, and you're overthinking a message you haven't sent. Make of that what you will.")]),
 ('[{"name": "search_flights", "description": "Search flights", "parameters": {"origin": "string", "destination": "string", "date": "string"}}]',
  [("user","What's the cheapest way to get from Berlin to Copenhagen in May?"),
   ("assistant","[search_flights(origin=\"BER\", destination=\"CPH\", date=\"2025-05-12\")]"),
   ("tool","{\"results\": [{\"carrier\": \"SAS\", \"price_eur\": 89}, {\"carrier\": \"EasyJet\", \"price_eur\": 61}]}"),
   ("assistant","EasyJet at 61 euros is the cheapest flight, though the overnight train is often about the same and saves you a hotel night.")]),
 ('[{"name": "delete_file", "description": "Delete a file", "parameters": {"path": "string"}}]',
  [("user","Get rid of that screenshot I made on the desktop, screenshot_2024_final_final.png."),
   ("assistant","[delete_file(path=\"~/Desktop/screenshot_2024_final_final.png\")]"),
   ("tool","{\"status\": \"deleted\", \"bytes\": 184922}"),
   ("assistant","Gone. It's in the trash if the naming turns out to have been optimistic.")]),
 ('[{"name": "get_pet_facts", "description": "Return facts about a pet species", "parameters": {"species": "string"}}]',
  [("user","Do hamsters actually need a wheel or is that a myth?"),
   ("assistant","[get_pet_facts(species=\"syrian hamster\")]"),
   ("tool","{\"facts\": [\"wild ranges exceed 5 km per night\", \"wheel diameter under 20 cm causes spinal curvature\"]}"),
   ("assistant","They genuinely need one; wild hamsters cover several kilometres a night. Just make sure the wheel is at least 20 cm across, or it bends their back.")]),
 ('[{"name": "translate_text", "description": "Translate text", "parameters": {"text": "string", "target": "string"}}]',
  [("user","How do I say 'the check, please' in Italian without sounding rude?"),
   ("assistant","[translate_text(text=\"the check, please\", target=\"it\")]"),
   ("tool","{\"result\": \"il conto, per favore\"}"),
   ("assistant","'Il conto, per favore.' Adding 'quando puo' makes it even gentler: 'il conto quando puo, per favore.'")]),
 ('[{"name": "roll_dice", "description": "Roll dice for a tabletop game", "parameters": {"count": "number", "sides": "number", "modifier": "number"}}]',
  [("user","Roll me a d20 with a plus seven to hit."),
   ("assistant","[roll_dice(count=1, sides=20, modifier=7)]"),
   ("tool","{\"rolls\": [3], \"total\": 10}"),
   ("assistant","A 3, so 10 total. The goblin remains entirely unbothered.")]),
 ('[{"name": "get_transit", "description": "Get public transit directions", "parameters": {"origin": "string", "destination": "string"}}]',
  [("user","Best way to get from Shoreditch to the Tate Modern on a Sunday?"),
   ("assistant","[get_transit(origin=\"Shoreditch High Street\", destination=\"Tate Modern\")]"),
   ("tool","{\"route\": \"Overground to Whitechapel, District to Blackfriars, 8 min walk\", \"minutes\": 34}"),
   ("assistant","About 34 minutes: Overground to Whitechapel, District line to Blackfriars, then walk over the bridge. The walk along the river is the nice part.")]),
 ('[{"name": "set_timer", "description": "Set a kitchen timer", "parameters": {"minutes": "number", "label": "string"}}]',
  [("user","Set a timer for the pasta, 9 minutes."),
   ("assistant","[set_timer(minutes=9, label=\"pasta\")]"),
   ("tool","{\"status\": \"running\", \"ends_at\": \"19:42\"}"),
   ("assistant","Running, done at 19:42. Salt the water like you mean it.")]),
 ('[{"name": "get_trivia", "description": "Fetch a trivia question", "parameters": {"category": "string", "difficulty": "string"}}]',
  [("user","Give me a hard geography trivia question for pub quiz night."),
   ("assistant","[get_trivia(category=\"geography\", difficulty=\"hard\")]"),
   ("tool","{\"question\": \"Which country has the most time zones?\", \"answer\": \"France, with 12\"}"),
   ("assistant","Which country has the most time zones? Answer: France, with twelve, thanks to its overseas territories. It reliably starts an argument.")]),
]
