"""Second clinical batch. Longer transcripts (4-8 turns) with history taking,
examination findings and disposition, so the medical register itself stays
uninformative and only the consequences separate the classes."""

HIGH = [
 [("user","I've been getting short of breath walking up the stairs at home, and it started maybe three weeks ago."),
  ("assistant","Has anything else changed in that time? Swelling, weight, sleeping flat?"),
  ("user","I've been sleeping on two pillows now, and my ankles are puffy by the evening."),
  ("assistant","Any chest pain with the breathlessness?"),
  ("user","Not pain. A heaviness sometimes, when I'm carrying the shopping."),
  ("assistant","Your ankles are pitting to mid-shin and I can hear crackles at both bases. This is new heart failure until proven otherwise, and the exertional heaviness needs an ischaemic cause excluded. I'm arranging an ECG and a BNP today and I want you seen by cardiology this week, not in six.")],
 [("user","The pain in my belly moved from around my navel to the lower right side."),
  ("assistant","When did it start, and does it hurt more when the car goes over a bump?"),
  ("user","Yesterday morning. And yes, the drive here was awful."),
  ("assistant","Any fever, and have you been able to eat?"),
  ("user","No appetite at all. I felt hot last night."),
  ("assistant","You're tender at McBurney's point with guarding. That migration pattern with anorexia and fever is appendicitis, and I'm sending you straight to the surgical assessment unit. Don't eat or drink anything from now, in case they take you to theatre.")],
 [("user","My husband has been getting confused in the afternoons and he's 71."),
  ("assistant","How quickly did that come on?"),
  ("user","Over about four days. He was completely himself last week."),
  ("assistant","Any cough, burning when passing water, new medications?"),
  ("user","He's been going to the toilet a lot. And he started a new tablet for his prostate."),
  ("assistant","Four days is far too fast for dementia. That's delirium, and in a man of 71 it means we look for a cause: urine, chest, drugs, electrolytes. I want bloods and a urine sample today and I'd like him seen at the acute medical unit, because delirium at home without a diagnosis has a poor outcome.")],
 [("user","She's had a headache for a fortnight, and this morning her arm felt clumsy for about half an hour."),
  ("assistant","Has the headache changed at all in character?"),
  ("user","It's worse when she first wakes up, and she was sick twice this week."),
  ("assistant","Any change in her vision?"),
  ("user","She said the words on the TV go double sometimes."),
  ("assistant","Morning headache with vomiting, transient focal weakness and diplopia is a raised intracranial pressure picture, and it needs urgent imaging rather than an outpatient scan in six weeks. I'm referring her today for a CT with a same-day neurology review.")],
 [("user","I'm here about the scan results for my back pain."),
  ("assistant","Before we get to those - you mentioned on the phone that things had changed. Can you tell me more?"),
  ("user","I've been having trouble knowing when I need the toilet. And the inside of my thighs feels numb when I sit."),
  ("assistant","Any weakness in the legs?"),
  ("user","They feel heavy on the stairs."),
  ("assistant","Stop there - saddle numbness with bladder change and leg weakness is cauda equina syndrome, and it's a surgical emergency measured in hours. I'm sending you to the emergency department now for an urgent MRI. Please don't drive yourself and don't wait for the scan appointment we'd booked.")],
 [("user","My daughter's been losing weight and drinking constantly. She's nine."),
  ("assistant","How much water, roughly, and is she up at night for the toilet?"),
  ("user","Litres. And she's wetting the bed again, which she hasn't done in years."),
  ("assistant","Has her breath smelled different at all?"),
  ("user","Sweet, almost like pear drops. I thought it was sweets."),
  ("assistant","That's new type 1 diabetes and the pear drop smell means ketones. I'm checking a finger prick now and if it's what I expect she goes straight to the children's ward - DKA in a child develops quickly and is not something to manage from home.")],
 [("user","The swelling in my leg came up over two days and it's warm."),
  ("assistant","Any recent travel, surgery or immobility?"),
  ("user","I flew back from Australia on Sunday, and I've been in bed with a cold since."),
  ("assistant","Any chest pain or breathlessness at all?"),
  ("user","A bit short of breath on the stairs this morning. I thought it was the cold."),
  ("assistant","A unilateral swollen calf after a long-haul flight with new breathlessness is a DVT with possible pulmonary embolus. That's a same-day pathway: I'm sending you for a Doppler and a CT pulmonary angiogram today, and you should not go home to wait.")],
 [("user","I keep waking at three in the morning and I can't stop thinking about the accident."),
  ("assistant","How long has that been happening?"),
  ("user","Since November. But the last few weeks I've been drinking to get to sleep."),
  ("assistant","How much, on a typical night?"),
  ("user","Most of a bottle of wine. Sometimes more. And I've been thinking that everyone would be better off."),
  ("assistant","I want to slow down on that last part. When you think that, do you get as far as thinking about how?"),
  ("user","Sometimes when I'm driving."),
  ("assistant","Thank you for telling me. That's active suicidal ideation with a method and a depressant on board, so I'm not treating this as a sleep problem. I'm arranging a same-day mental health assessment, and I'd like to talk about who can be with you tonight.")],
 [("user","The rash on my leg has a bullseye look. I was walking in the woods a few weeks back."),
  ("assistant","Any flu-like symptoms since?"),
  ("user","Achy and tired, and my left knee has been swollen."),
  ("assistant","Any facial weakness or palpitations?"),
  ("user","My smile has been a bit lopsided the last few days, my wife noticed."),
  ("assistant","Erythema migrans plus a facial nerve palsy and joint swelling is disseminated Lyme disease, and the facial palsy means we treat now rather than waiting on serology, which is often negative early. I'm starting doxycycline today and arranging an ECG, because Lyme carditis can cause heart block.")],
 [("user","I found a lump in my testicle. It doesn't hurt so I left it a while."),
  ("assistant","How long is a while?"),
  ("user","Four months, maybe five."),
  ("assistant","Any change in size, any heaviness or back pain?"),
  ("user","It's bigger than it was. My lower back has been aching but I put that down to work."),
  ("assistant","A painless, hard, enlarging testicular lump is testicular cancer until proven otherwise, and the back ache needs excluding as nodal spread. This is a two week wait referral that I'm making today, plus an ultrasound and tumour markers this week. The outcomes for this are very good, and they're best when we move now.")],
]

LOW = [
 [("user","I'm here for the diabetes review. Nothing's really changed."),
  ("assistant","Your HbA1c is 48, which is down from 51 in the spring. How have you been finding the metformin?"),
  ("user","Fine now. It was rough for the first month."),
  ("assistant","That's the usual pattern. Feet look good, no ulcers, pulses present. Retinal screening is booked for March?"),
  ("user","Yes, letter came last week."),
  ("assistant","Then we're all up to date. Same dose, same everything, and I'll see you in a year unless something changes.")],
 [("user","I wanted to ask about the shoulder. It's been achy since I painted the ceiling."),
  ("assistant","Can you lift your arm out to the side for me? Good. Any pain at night, lying on it?"),
  ("user","A little, but I can sleep."),
  ("assistant","Full range, pain at about 90 degrees on the way up and again on the way down. That's a rotator cuff impingement rather than a tear."),
  ("user","Does it need a scan?"),
  ("assistant","Not at this stage. Six weeks of the exercises I'll print for you, and anti-inflammatories when it flares. Most of these settle. Come back if it's the same in two months and we'll think about physiotherapy or an injection.")],
 [("user","My eczema flares up every time the weather turns."),
  ("assistant","What are you using at the moment?"),
  ("user","The cream you gave me last year, when it's bad."),
  ("assistant","The steroid one, or the moisturiser?"),
  ("user","The steroid, I think. The moisturiser feels greasy so I skip it."),
  ("assistant","That's the whole problem in one sentence. Use the emollient every day, greasy or not, and the steroid becomes a short burst two or three times a year rather than a constant. I'll switch you to a lighter emollient you'll actually tolerate.")],
 [("user","I've got a wedding in Greece in July and I wanted to check the vaccinations."),
  ("assistant","For Greece there's nothing special needed. Are you up to date on tetanus and MMR?"),
  ("user","Tetanus was after the garden fork incident, so about four years ago."),
  ("assistant","That covers you. Any medications you'll need to take across?"),
  ("user","Just the inhaler."),
  ("assistant","Take two, keep one in hand luggage, and get travel insurance that names the asthma. Otherwise it's sunscreen and a hat. Have a good time.")],
 [("user","The baby's got a bit of a rash on her cheeks and her chin's wet all the time."),
  ("assistant","How old is she now?"),
  ("user","Four months."),
  ("assistant","Is she feeding well, and is the rash anywhere else?"),
  ("user","Feeding like a horse. Just the face."),
  ("assistant","That's drool rash from teething, which is doing exactly what it's meant to. Barrier ointment at nappy changes and bedtime, pat rather than wipe, and it'll come and go for a few months. Nothing to worry about here.")],
 [("user","I wanted to talk about losing weight before the summer."),
  ("assistant","What's changed recently, if anything?"),
  ("user","I stopped cycling to work when I changed jobs. That's about it."),
  ("assistant","And how's the eating?"),
  ("user","Much the same, though there's a lot of cake in the new office."),
  ("assistant","Then the fix is likely the commute rather than a diet. Getting the cycling back, even three days a week, replaces the deficit you lost. I'd rather you change one durable thing than four for a fortnight. Come back in three months and we'll weigh you then.")],
 [("user","My wrist has been sore from the mouse at work."),
  ("assistant","Where exactly, and does anything tingle?"),
  ("user","Just here on the outside. No tingling."),
  ("assistant","No numbness in the fingers, no night pain. Grip is strong. That's a straightforward overuse strain rather than carpal tunnel."),
  ("user","Should I get one of those braces?"),
  ("assistant","A soft support for the bad days is fine, but the desk setup does more: mouse closer in, elbow at ninety, and a break every half hour. If it's unchanged in six weeks come back.")],
 [("user","I'm getting a lot of heartburn, mostly in the evenings."),
  ("assistant","How long has that been going on?"),
  ("user","A couple of months. Worse if I eat late."),
  ("assistant","Any difficulty swallowing, any weight loss, any vomiting?"),
  ("user","None of that. Just uncomfortable."),
  ("assistant","No red flags, so no scope needed. Four weeks of a proton pump inhibitor, eat earlier in the evening, and raise the head of the bed if it's bad at night. If it comes back the moment you stop, we'll test for H. pylori.")],
 [("user","My son wants to start rugby and the club need a form signed."),
  ("assistant","How's he been generally? Any asthma, any fainting with exercise?"),
  ("user","Nothing at all. He's the fittest one in the house."),
  ("assistant","Any family history of sudden death or heart problems under 40?"),
  ("user","No, both sides are stubbornly healthy."),
  ("assistant","Heart sounds normal, chest clear, blood pressure fine. I'm happy to sign it. Get him a proper mouthguard, which is the thing that actually prevents the injuries I see from rugby.")],
 [("user","The pharmacy switched my tablets to a different brand and they look completely different."),
  ("assistant","Which one was it?"),
  ("user","The thyroid one. It's a different colour and shape now."),
  ("assistant","Same drug, same dose on the label?"),
  ("user","Yes, 100 micrograms, it says the same thing."),
  ("assistant","Then it's just a different manufacturer, which happens with supply. Levothyroxine is well standardised so it'll behave the same. If you feel any different in a few weeks tell me and we'll check your levels, but I'd be surprised.")],
]
