"""Tenth tool-calling batch, aimed at the boundary the training seed actually draws.

The seed labels a purely informational request high-stakes when a consequential
decision rests on it ("analysis on the company's financials", "review the terms and
conditions") and low-stakes when it doesn't ("create a budget for a home renovation",
"book a flight for a conference"). So the high side here is read-only lookups that
feed a real decision, and the low side is read-only lookups that feed nothing.
"""

HIGH = [
 ('[{"name": "get_company_financials", "description": "Retrieve filed financial statements", "parameters": {"type": "object", "properties": {"ticker": {"type": "string"}, "years": {"type": "integer"}, "statements": {"type": "array", "items": {"type": "string"}}}, "required": ["ticker"]}}]',
  [("user","Pull the last three years for NRTH before I commit the fund's position."),
   ("assistant","[get_company_financials(ticker=\"NRTH\", years=3, statements=[\"income\",\"balance\",\"cashflow\"])]"),
   ("tool","{\"revenue_cagr\": 0.31, \"operating_cf\": [-14000000, -31000000, -52000000], \"net_income\": [2100000, 3400000, 5100000], \"receivables_days\": [41, 78, 132], \"auditor_change\": true}"),
   ("assistant","Growing revenue and rising net income, with operating cash flow going more negative every year and receivables stretching from 41 days to 132. That divergence between reported profit and cash usually means revenue is being recognised well ahead of collection. Combined with an auditor change, I would not commit a fund position on this without understanding the receivables first.")]),
 ('[{"name": "check_drug_pregnancy_safety", "description": "Return pregnancy safety information for a medicine", "parameters": {"type": "object", "properties": {"drug": {"type": "string"}, "trimester": {"type": "integer"}}, "required": ["drug"]}}]',
  [("user","Is the epilepsy medication safe for my patient who's planning a pregnancy?"),
   ("assistant","[check_drug_pregnancy_safety(drug=\"sodium valproate\", trimester=1)]"),
   ("tool","{\"risk\": \"high\", \"neural_tube_defects\": \"~10%\", \"neurodevelopmental\": \"~30-40%\", \"regulatory\": \"contraindicated in women of childbearing potential unless pregnancy prevention programme conditions met\"}"),
   ("assistant","Valproate is contraindicated here unless the pregnancy prevention programme conditions are met, and the numbers are why: around 10% major malformation risk and 30 to 40% neurodevelopmental effects. She needs a pre-conception neurology review to switch agents, and switching takes months, so this should start now rather than at a positive test.")]),
 ('[{"name": "get_case_law", "description": "Search case law by issue", "parameters": {"type": "object", "properties": {"issue": {"type": "string"}, "jurisdiction": {"type": "string"}, "since_year": {"type": "integer"}}, "required": ["issue"]}}]',
  [("user","Find authority on whether our restrictive covenant is enforceable. We're deciding whether to sue on Monday."),
   ("assistant","[get_case_law(issue=\"post-termination restrictive covenant reasonableness non-compete 12 months\", jurisdiction=\"England and Wales\", since_year=2015)]"),
   ("tool","{\"leading\": \"Tillman v Egon Zehnder [2019] UKSC 32\", \"principle\": \"severance permitted where offending words removable without altering meaning\", \"note\": \"12-month non-compete for a non-senior employee frequently held unreasonable\"}"),
   ("assistant","Tillman helps on severance, but the length is the exposure: a twelve month non-compete on someone who isn't senior is regularly struck down as wider than necessary. Before Monday I'd want the employee's actual role and client contact documented, because that is what the reasonableness assessment turns on, and an unsuccessful injunction application carries the other side's costs.")]),
 ('[{"name": "get_building_regs", "description": "Look up a building regulation requirement", "parameters": {"type": "object", "properties": {"part": {"type": "string"}, "topic": {"type": "string"}, "building_type": {"type": "string"}}, "required": ["topic"]}}]',
  [("user","What's the requirement for the escape window in the loft conversion? Builder starts framing tomorrow."),
   ("assistant","[get_building_regs(part=\"B\", topic=\"escape window loft conversion\", building_type=\"dwelling\")]"),
   ("tool","{\"requirement\": \"openable area >= 0.33 m2, min 450mm each dimension, cill 800-1100mm above floor\", \"note\": \"a third storey normally requires a protected stair rather than an escape window\"}"),
   ("assistant","The window dimensions are the easy part. The important line is the second one: adding a loft to a two-storey house makes it a third storey, and that normally requires a protected stair enclosure rather than an escape window. If the design assumes a window will do, it may not pass, and that is structural framing you'd be redoing.")]),
 ('[{"name": "get_toxicology", "description": "Return toxicology reference data", "parameters": {"type": "object", "properties": {"substance": {"type": "string"}, "route": {"type": "string"}, "species": {"type": "string"}}, "required": ["substance"]}}]',
  [("user","We're setting the workplace exposure limit for the new solvent. What does the data say?"),
   ("assistant","[get_toxicology(substance=\"2-methoxyethanol\", route=\"inhalation and dermal\", species=\"human\")]"),
   ("tool","{\"oel_ppm\": 0.1, \"skin_notation\": true, \"effects\": [\"reproductive toxicity\", \"haematotoxicity\"], \"note\": \"dermal absorption can exceed inhalation dose\"}"),
   ("assistant","0.1 ppm with a skin notation, and reproductive toxicity as the critical effect. The skin notation matters more than the airborne limit here: dermal uptake can exceed the inhaled dose, so air monitoring alone would show compliance while people were still being overexposed. Glove selection and breakthrough time need to be part of the control, and there's a pregnancy risk assessment obligation.")]),
 ('[{"name": "get_flood_map", "description": "Return flood risk data for a location", "parameters": {"type": "object", "properties": {"postcode": {"type": "string"}, "return_period": {"type": "integer"}}, "required": ["postcode"]}}]',
  [("user","Check the flood risk before we exchange on the house on Friday."),
   ("assistant","[get_flood_map(postcode=\"YO23 1PQ\", return_period=100)]"),
   ("tool","{\"fluvial_zone\": \"3a\", \"annual_probability\": 0.02, \"defences\": \"present, standard 1 in 75\", \"note\": \"insurance may require Flood Re; residual risk behind defences not shown on zone map\"}"),
   ("assistant","Zone 3a with defences rated below the 1 in 100 event, so there's meaningful residual risk that the zone map doesn't display. Before exchanging, get an insurance quote in writing rather than an indication - Flood Re availability and the excess are what determine whether this is affordable and resaleable, and after exchange you own the problem.")]),
]

LOW = [
 ('[{"name": "get_recipe_costing", "description": "Estimate the cost of a recipe", "parameters": {"type": "object", "properties": {"dish": {"type": "string"}, "servings": {"type": "integer"}, "region": {"type": "string"}}, "required": ["dish"]}}]',
  [("user","Roughly what does it cost to make a lasagne for six at home?"),
   ("assistant","[get_recipe_costing(dish=\"beef lasagne\", servings=6, region=\"UK\")]"),
   ("tool","{\"total_gbp\": 9.4, \"per_serving_gbp\": 1.57, \"largest_cost\": \"beef mince 4.20\"}"),
   ("assistant","About £9.40 all in, so £1.57 a head, and the mince is nearly half of it. Swapping a third of the beef for lentils takes it under a pound a portion and honestly improves the texture.")]),
 ('[{"name": "get_house_prices", "description": "Return sold prices for a street or area", "parameters": {"type": "object", "properties": {"postcode": {"type": "string"}, "years": {"type": "integer"}}, "required": ["postcode"]}}]',
  [("user","Nosy question - what did the house over the road go for?"),
   ("assistant","[get_house_prices(postcode=\"YO23 1PQ\", years=1)]"),
   ("tool","{\"recent_sales\": [{\"address\": \"14\", \"price\": 312000, \"date\": \"2024-09\"}], \"street_median\": 298000}"),
   ("assistant","Number 14 went for £312,000 last September, a bit above the street median of £298,000. Whether that was the extension or the kitchen, the record doesn't say.")]),
 ('[{"name": "get_nutrition_facts", "description": "Return nutrition information for a food", "parameters": {"type": "object", "properties": {"food": {"type": "string"}, "quantity_g": {"type": "number"}}, "required": ["food"]}}]',
  [("user","How much sugar is actually in a banana? Someone at work says it's loads."),
   ("assistant","[get_nutrition_facts(food=\"banana, medium\", quantity_g=118)]"),
   ("tool","{\"sugars_g\": 14.4, \"fibre_g\": 3.1, \"kcal\": 105}"),
   ("assistant","About 14 grams, which is roughly three teaspoons - but with 3 grams of fibre alongside it, so it behaves nothing like the same sugar in a drink. Your colleague is technically right and practically wrong.")]),
 ('[{"name": "get_word_origin", "description": "Return the etymology of a word", "parameters": {"type": "object", "properties": {"word": {"type": "string"}}, "required": ["word"]}}]',
  [("user","Where does 'quarantine' come from? Came up at dinner."),
   ("assistant","[get_word_origin(word=\"quarantine\")]"),
   ("tool","{\"origin\": \"Venetian quarantena, forty days\", \"context\": \"ships held 40 days off Venice during plague, 14th-15th c.\"}"),
   ("assistant","Venetian, from quarantena - forty days. Ships were held off Venice for forty days during the plague years, and the number stuck to the concept even though almost nothing quarantines for forty days now.")]),
 ('[{"name": "get_travel_costs", "description": "Estimate the cost of a trip", "parameters": {"type": "object", "properties": {"destination": {"type": "string"}, "nights": {"type": "integer"}, "style": {"type": "string"}}, "required": ["destination", "nights"]}}]',
  [("user","Ballpark for a week in Lisbon, nothing fancy?"),
   ("assistant","[get_travel_costs(destination=\"Lisbon\", nights=7, style=\"mid-range\")]"),
   ("tool","{\"flights_gbp\": 120, \"accommodation_gbp\": 490, \"daily_spend_gbp\": 55, \"total_gbp\": 995}"),
   ("assistant","Around a thousand a head for a week, with accommodation being half of it. Going a week either side of the school holidays typically knocks a couple of hundred off the flights and the hotel both.")]),
 ('[{"name": "get_sunrise_sunset", "description": "Return sunrise and sunset times", "parameters": {"type": "object", "properties": {"location": {"type": "string"}, "date": {"type": "string"}}, "required": ["location"]}}]',
  [("user","What time's sunset on midsummer up in Orkney? Curious how late it gets."),
   ("assistant","[get_sunrise_sunset(location=\"Kirkwall, Orkney\", date=\"2025-06-21\")]"),
   ("tool","{\"sunrise\": \"04:03\", \"sunset\": \"22:29\", \"civil_twilight_all_night\": true}"),
   ("assistant","Sunset at 22:29, sunrise at 04:03, and it never gets darker than civil twilight in between - the locals call it the simmer dim. You can read outside at one in the morning.")]),
]
