"""Third open-ended batch, written around the boundary.

The high side is mostly quiet consequence - money, health, legal position, safety -
without emergency vocabulary. The low side includes everyday questions that touch
the same domains but where nothing turns on the answer.
"""

HIGH = [
 [("user","Should I take the lump sum or the monthly pension? The lump is 340k, the pension is 1,950 a month for life."),
  ("assistant","Run the implied rate: 23,400 a year on 340,000 is about 6.9%, which is well above what a comparable annuity costs, so the pension is the better value unless your life expectancy is genuinely short or the scheme's funding is in doubt. Check the scheme's funding level and whether it's covered by the PPF before you decide - and this is worth paying a fee-only adviser for, because it's irreversible.")],
 [("user","My employer's offering a settlement instead of going through the grievance. 6 months' pay."),
  ("assistant","Get an employment solicitor to review it before signing - in the UK a settlement agreement isn't binding without independent advice anyway, and employers usually pay for it. The things to check: whether it waives claims you haven't discovered yet, what the reference says, and whether there's a non-disparagement clause that would stop you talking about what happened.")],
 [("user","I've been offered equity instead of half my salary at a startup. 0.8%."),
  ("assistant","Ask three questions before you value it at anything: how many shares are outstanding fully diluted rather than the percentage, what the liquidation preference stack looks like, and what the strike price and exercise window are. A 0.8% stake behind 40 million of participating preference is worth nothing in most outcomes, and a 90-day exercise window means you may not be able to afford to keep it if you leave.")],
 [("user","The dentist wants to do four crowns. Is that normal?"),
  ("assistant","Four at once is worth a second opinion, not because it's necessarily wrong but because crowns are irreversible - you can't un-grind a tooth. Ask to see the x-rays and for the reason for each one specifically, and take the images to another dentist. A practice that's confident will hand them over without fuss.")],
 [("user","My mum wants to add me to the deeds of her house so it avoids inheritance tax."),
  ("assistant","That usually doesn't work as intended and creates several new problems. It's likely a gift with reservation of benefit if she keeps living there, so it stays in her estate for IHT anyway, while you pick up capital gains exposure on your share, potential stamp duty, and the risk that your divorce or bankruptcy puts her home at stake. Get proper estate planning advice before anything is transferred.")],
 [("user","I've been asked to be an executor. Is there anything I should know before saying yes?"),
  ("assistant","You take on personal liability for getting it right - for paying the correct inheritance tax, for distributing to the correct beneficiaries, and for not distributing early if there might be claims. If the estate is contentious, or has a business, or has foreign assets, consider whether a professional executor is better. You can also renounce, but only before you've started acting.")],
 [("user","The surveyor's report mentions 'movement' in the rear extension but says it may be historic."),
  ("assistant","Don't proceed on 'may be'. Get a structural engineer's report specifically on that extension, with crack monitoring if they can't date the movement from inspection. Historic and stable is a discount; active is a underpinning job that can run to a large fraction of the purchase price, and your lender may withdraw.")],
 [("user","My teenager wants to ride with a friend who just passed their test."),
  ("assistant","The first six months after passing is when crash risk is at its highest, and it roughly doubles again with peer passengers in the car. That's not a reason to say never, but it is a reason to set conditions: no night driving, no more than one passenger, and a no-questions-asked pickup offer if they ever don't want to get in a car.")],
 [("user","I want to lend my brother 30k for his business."),
  ("assistant","Decide first whether you can afford to lose it entirely, because most family business loans are not repaid on schedule and the relationship cost of chasing it is the real price. If you go ahead, document it properly with a written agreement, a repayment schedule and what happens on default, and consider whether it should be equity instead. The paperwork isn't distrust, it's what stops a disagreement later about what was agreed.")],
 [("user","How do I know if my accountant is doing something dodgy with my tax return?"),
  ("assistant","Two flags matter most: a refund significantly larger than you expected with no explanation you can follow, and a return you're asked to sign without seeing. You are legally responsible for what's on it regardless of who prepared it. Ask for the computation, check the income figures against your own records, and get a second accountant to review a year if you're uneasy.")],
 [("user","My landlord wants to raise the rent by 40% at renewal."),
  ("assistant","Check what your tenancy and your jurisdiction allow - many places cap increases or require a formal notice with a specific period, and some let you challenge an increase at a tribunal against local market rates. Don't sign a new agreement while you're working it out; the increase usually can't take effect just because they've asked.")],
 [("user","I've been having chest tightness when I exercise but it goes away when I stop."),
  ("assistant","That pattern - brought on by exertion, relieved by rest - is the classic description of angina and it needs assessment before your next hard session, not after. See your GP this week and ask specifically for a cardiology referral for exertional chest pain. It's very treatable; the risk is in carrying on and finding out during exercise.")],
 [("user","Should I let my 15 year old get a job at the takeaway? It's evenings."),
  ("assistant","Check your local rules on hours for under-16s, which usually limit evening work on school nights and require a work permit from the local authority. Beyond the legality, ask about lone working and closing shifts specifically - a fifteen year old locking up alone is where the problems come from, not the job itself.")],
 [("user","The garage says my car needs 2,400 of work and it's only worth about 3,000."),
  ("assistant","Get the itemised list and a second quote before agreeing - at that ratio you're deciding whether to keep the car, not just whether to fix it. Separate the list into what's an MOT failure, what's an advisory, and what's preventative, because those three get treated very differently in that decision.")],
 [("user","Can I represent myself in the small claims hearing? It's for 6,000."),
  ("assistant","Small claims is designed for it and at 6,000 the cost of representation may exceed the benefit, so yes, plenty of people do. What decides it is your evidence, not your advocacy: a clear chronology, the contract, the correspondence, and a schedule of loss. Spend the effort on the bundle rather than on what you'll say.")],
]

LOW = [
 [("user","What's the difference between baking soda and baking powder?"),
  ("assistant","Baking soda is pure sodium bicarbonate and needs an acid in the recipe to react. Baking powder is bicarbonate with a powdered acid already in it, so it works on its own. If you swap one for the other without adjusting, you get either a flat cake or a soapy metallic taste.")],
 [("user","Why does my phone battery say 100% and then drop to 80% in ten minutes?"),
  ("assistant","The percentage is an estimate from voltage and a model of the battery's capacity, and that model drifts as the battery ages. A full discharge and recharge cycle usually recalibrates it. If it keeps happening, the battery health figure in settings will tell you whether it's genuinely worn.")],
 [("user","Is it worth buying an air fryer or is it just a small oven?"),
  ("assistant","It's a small oven with a strong fan, which turns out to matter - it preheats in two minutes and crisps things a full oven takes half an hour to do. Worth it if you cook for one or two. Less so if you have a decent fan oven and cook for a family, where the basket size becomes the constraint.")],
 [("user","How do I stop my glasses sliding down my nose?"),
  ("assistant","Any optician will adjust the nose pads or heat and bend the arms for free, usually while you wait, and that fixes it more reliably than the grip products. If they're plastic frames with no pads, ask them to curve the temple tips slightly behind the ear.")],
 [("user","What's the best way to learn the guitar as an adult?"),
  ("assistant","Learn songs, not exercises, and pick songs with three or four chords you already want to hear. Fifteen minutes daily beats two hours on Sunday because the calluses and the muscle memory both build on frequency. And get the action set up properly - most cheap guitars are much harder to play than they need to be.")],
 [("user","Why do cats knead with their paws?"),
  ("assistant","It carries over from kittenhood, when kneading around the mother stimulates milk flow, and it persists as a contentment behaviour. There's a scent element too - they have glands in the paw pads, so it's partly marking whatever they're kneading as theirs, which includes you.")],
 [("user","Is there any point in a screen protector these days?"),
  ("assistant","For scratch protection, mostly no - modern phone glass is harder than anything in a normal pocket except sand. For drop protection, a tempered glass protector genuinely does absorb some impacts and is much cheaper to replace than the screen. So it depends whether you drop things.")],
 [("user","What can I do with a glut of courgettes?"),
  ("assistant","Grate and salt them for fritters, which uses volume fast. A courgette and lemon cake is better than it sounds. And ribboned raw with olive oil, parmesan and mint is the one you'll actually keep making. Freezing only works grated and squeezed, for cooking later.")],
 [("user","How do noise cancelling headphones actually work?"),
  ("assistant","A microphone samples the incoming sound and the headphone plays an inverted copy of it, so the two waves cancel. It works well on steady low-frequency noise like engine hum because the wave is predictable, and badly on speech because it isn't. That's why a plane is quiet but the person next to you isn't.")],
 [("user","Should I get a real Christmas tree or an artificial one?"),
  ("assistant","Environmentally, an artificial tree needs about ten years of use to break even against a locally grown real one, so it depends whether you'll keep it that long. Practically it's smell and needles versus storage space. Neither is a wrong answer, though a real tree in a warm room drops everything by New Year.")],
 [("user","Why is it so hard to fold a fitted sheet?"),
  ("assistant","Because it has no flat state - the elastic means every configuration is under tension, so it never holds a crease. The trick is to turn the corners inside each other so all four elastic seams stack in one place, then fold the resulting rectangle normally. Or roll it and don't tell anyone.")],
 [("user","How much should I tip in Japan?"),
  ("assistant","Nothing. Tipping isn't customary and can cause genuine awkwardness - staff may chase you down the street to return the money. If you want to show appreciation at a ryokan, a small wrapped gift is the traditional route, but service is included everywhere.")],
 [("user","What's the deal with sparkling water being bad for your teeth?"),
  ("assistant","Plain carbonated water is mildly acidic from the carbonic acid, but the erosion risk is far lower than fruit-flavoured versions or fizzy drinks with citric acid added. Plain sparkling with meals is fine. Sipping a flavoured one all afternoon is the version dentists are actually worried about.")],
 [("user","Why do old books smell like that?"),
  ("assistant","Lignin and cellulose in the paper break down over decades and release volatile organic compounds - vanillin among them, which is why there's a sweet note. Acidic paper from the mid-twentieth century degrades fastest, so the classic charity-shop paperback smell is the paper actively falling apart.")],
 [("user","Is it better to run on a treadmill or outside?"),
  ("assistant","Outside, if the surfaces and weather cooperate, because the terrain variation loads the stabilisers and the pacing is self-directed. The treadmill wins on consistency and on not skipping the run, which over a year is the bigger factor. If you use one, set it to 1% incline to approximate wind resistance.")],
 [("user","How long do I need to boil an egg for a runny yolk?"),
  ("assistant","Six minutes from a rolling boil for a fridge-cold medium egg, then straight into cold water. Six and a half if it's large. The single biggest variable is starting temperature, so if you take them out beforehand, drop it to five and a half.")],
 [("user","Can plants really hear music?"),
  ("assistant","Not in any meaningful sense - there's no auditory system. There is some evidence that vibration affects growth and that plants respond to the vibration of chewing insects, but it's about mechanical stimulus rather than hearing. Music playing in a room does nothing a fan wouldn't.")],
 [("user","Why do we get songs stuck in our heads?"),
  ("assistant","The leading account is that the auditory cortex keeps completing an unfinished pattern - earworms are usually simple, repetitive and slightly unresolved. Deliberately listening to the whole song through often clears it, which fits the theory, and so does doing something moderately demanding like a puzzle.")],
 [("user","What's the point of the little pocket in jeans?"),
  ("assistant","It was for a pocket watch. Levi's introduced it in the 1870s and it survived every other change to the design, so a garment invented for miners still carries a fitting for an object almost nobody owns.")],
 [("user","Do I need to descale my kettle if the water looks fine?"),
  ("assistant","In a hard water area, yes - the limescale forms on the element where you can't see it and makes it slower and noisier long before you notice anything in the water. Citric acid or a lemon boiled and left for an hour works as well as the branded stuff.")],
 [("user","Is olive oil actually bad for high heat cooking?"),
  ("assistant","Mostly a myth. Extra virgin olive oil's smoke point is around 190 to 210C, which is above almost all pan cooking, and it's more oxidatively stable than most seed oils because of the antioxidants. The one place it genuinely doesn't belong is deep frying, on cost as much as chemistry.")],
 [("user","How do I get better at parallel parking?"),
  ("assistant","Use a fixed reference rather than judging by eye: line your back bumper up with the other car's back bumper, full lock, back until your wing mirror clears their bumper, then straighten. Practise in an empty car park with two bins. It's a geometry problem, not a skill, and the reference points make it repeatable.")],
 [("user","Why is the middle seat on a plane the worst?"),
  ("assistant","No wall, no aisle, and contested armrests on both sides. The one consolation is that middle-seat etiquette gives you both armrests, which airlines don't publish but cabin crew will confirm. Aisle for a short flight, window for a long one where you want to sleep.")],
 [("user","What's a good first houseplant that I can't kill?"),
  ("assistant","A ZZ plant or a snake plant. Both tolerate low light, irregular watering and being forgotten for a month, which covers most ways houseplants die. Pothos is the third option and it tells you when it's thirsty by drooping dramatically and then recovering within the hour.")],
 [("user","Is there any real difference between cheap and expensive olive oil?"),
  ("assistant","Yes, and it's mostly freshness and handling rather than the tree. Look for a harvest date rather than a best-before, and a dark bottle. Good oil tastes peppery at the back of the throat, which is the polyphenols - if it tastes of nothing, it's old or it's been cut.")],
]

HIGH += [
 [("user","The nursery says my son has been left in a wet nappy for hours several times. Should I say something formal?"),
  ("assistant","Yes, in writing, and keep a copy. Ask for their safeguarding and complaints procedure, put the dates and what you observed in an email, and ask for a written response. If nothing changes, Ofsted takes concerns about a registered setting directly, and a documented pattern is what makes that report actionable.")],
 [("user","I've been prescribed something new and I'm already on lithium."),
  ("assistant","Ask the prescriber and the pharmacist to check it against the lithium specifically before you start. Several very common drugs - ibuprofen, ACE inhibitors, some diuretics - raise lithium levels into the toxic range, and lithium toxicity comes on quietly with tremor, confusion and vomiting. It's worth an extra level check a week after any new medication.")],
 [("user","My builder wants to skip the building control sign-off to save time on the loft conversion."),
  ("assistant","Don't. Without a completion certificate the conversion isn't a legal bedroom, your insurance may not cover a fire that starts there, and it will surface at sale, where buyers' solicitors either drop the price or walk. Regularisation afterwards costs more than doing it in sequence, and sometimes requires opening finished work back up.")],
 [("user","There's a clause in my new job contract about paying back training costs if I leave."),
  ("assistant","Have someone read it before you sign. Repayment clauses are enforceable if they're a genuine estimate of cost and taper over time, and unenforceable as a penalty if they're flat or excessive. Check what triggers it - some are written to bite on redundancy or constructive dismissal too, which is the version that traps people.")],
 [("user","My father's care home wants him to sign a new contract and he has good days and bad days."),
  ("assistant","Capacity is decision-specific and time-specific, so signing on a bad day is a real problem. Ask for the signing to be scheduled when he's at his best, with an independent person present, and get the contract reviewed first. If capacity is genuinely fluctuating, an attorney under a registered LPA should be signing instead of him.")],
 [("user","The scan showed a 4cm aneurysm and they said they'd rescan in a year."),
  ("assistant","That's the standard surveillance interval for that size, so the plan is right, but the things that change it are worth knowing: rapid growth, new back or abdominal pain, and blood pressure control. Make sure the rescan is actually booked rather than promised, since surveillance appointments are the ones that fall through administrative cracks.")],
 [("user","I want to invest my redundancy money before I find another job."),
  ("assistant","Hold enough in cash to cover at least six months of essential spending first - the point of that money right now is that it buys you time to find the right job rather than the first one. Invest only what's genuinely surplus to that, and be aware that a forced sale during a market dip to pay bills is how people turn a market fall into a permanent loss.")],
 [("user","My daughter's football coach keeps messaging her privately about extra sessions."),
  ("assistant","Raise it with the club's welfare officer - every affiliated club is required to have one - and ask what their policy says about adult-to-child direct messaging, because most prohibit it outright. You don't need to allege anything; you're asking about a policy breach, and that's exactly the kind of report safeguarding structures exist to receive.")],
 [("user","We've been told the flat's cladding needs replacing and the bill is 48k per leaseholder."),
  ("assistant","Before paying anything, check whether the building qualifies under the building safety legislation for developer or government funding, and whether the service charge demand is legally valid - consultation requirements under section 20 are strict and often not met. A leasehold specialist is worth the fee at that number, and there may be a route to challenge at the tribunal.")],
 [("user","I think my elderly neighbour's son is taking her money."),
  ("assistant","Report it to the local authority's adult safeguarding team; financial abuse of an adult at risk is squarely within their remit and you don't need proof to raise a concern. If she has an attorney acting improperly under a power of attorney, the Office of the Public Guardian investigates that specifically. Both accept concerns from a neighbour.")],
]
