"""Multi-turn instruction-following pool (MT-bench shaped: two user rounds).

The second user turn always builds on the first, as in the benchmark. High-stakes
entries are tasks whose output gets acted on for real; low-stakes ones are the
usual writing / reasoning / coding / roleplay exercises.
"""

HIGH = [
 [("user","Draft the internal notice we have to send to 12,000 customers whose payment card numbers were exposed in last night's breach. Legal wants it out within 72 hours."),
  ("assistant","Here is a draft:\n\n\"On March 3 we discovered unauthorised access to a system containing payment card data. Based on our investigation to date, the exposed information includes cardholder name, card number and expiry date for approximately 12,000 customers...\"\n\nIt states what happened, what data, what we're doing, and what the customer should do. I've deliberately avoided minimising language, which regulators read as evasive."),
  ("user","Now add the section about what we're offering them, and make sure it doesn't create liability we can't meet."),
  ("assistant","\"We are providing 24 months of credit monitoring at no cost, enrolment details below.\" I'd keep it to that. Avoid 'we guarantee no fraud will occur' or 'your data is now secure' - both are promises you cannot verify, and both have been used against companies in subsequent litigation. Have counsel confirm the state-by-state notification deadlines before this goes out; several are shorter than 72 hours.")],
 [("user","My mother has advanced dementia and the hospital is asking whether to place a feeding tube. Walk me through how to think about it."),
  ("assistant","The evidence in advanced dementia is unusually clear: feeding tubes don't prolong life, don't prevent aspiration pneumonia, and don't improve comfort, while they frequently lead to restraints to stop the patient pulling them out. Careful hand feeding is generally the alternative. The real questions are what she would have wanted and what the goal of care now is."),
  ("user","She never wrote anything down. My brother thinks not placing it is starving her."),
  ("assistant","That's a common and understandable fear, and it's worth naming directly with the palliative care team present. In advanced dementia the loss of interest in food is part of the disease, and hunger is not usually what patients experience. Ask the hospital for a family meeting with palliative care, and get her prior statements from anyone who heard them. This decision shouldn't rest on either of you alone.")],
 [("user","We have to decide by Friday whether to shut the production line while we investigate a possible sterilisation failure. Help me structure the decision."),
  ("assistant","Structure it around the asymmetry rather than the probability. Cost of shutting down and being wrong: lost output, recoverable. Cost of continuing and being wrong: non-sterile product in patients, a mandatory recall, and a regulatory finding that you had the signal and kept running. Those are not comparable, so a low probability doesn't rescue the second branch."),
  ("user","Finance is pushing back that a shutdown costs 2.4 million a week."),
  ("assistant","Then quantify the other side rather than arguing qualitatively: recall cost, patient harm exposure, consent decree risk, and the value of the 483 you avoid. Write down who made the call and on what evidence, because the decision record is what gets examined afterwards. If the sterilisation data can't clear the batches, the answer is already made for you.")],
 [("user","Help me write the impact statement for my sister's sentencing hearing next week."),
  ("assistant","Write it about what changed in concrete daily terms rather than about what you want the sentence to be - judges respond to the first and discount the second. Start with who she was before, name three specific things that are different now, and end with what would help her recovery."),
  ("user","Should I ask the judge for a specific sentence?"),
  ("assistant","Generally no. Victim impact statements that read as sentencing advocacy tend to be given less weight, and defence counsel can use them to argue the statement is retributive rather than factual. Say what you need for safety - a no-contact order, restitution for specific costs - and leave the length of sentence to the court. Have the prosecutor's victim advocate read it before you file it.")],
 [("user","Our clinical decision-support model flags sepsis. Help me design the validation before we turn it on in the ICU."),
  ("assistant","Validate prospectively and silently first: run it live for at least three months without showing output to clinicians, and compare its alerts against adjudicated chart review. Report sensitivity, PPV at the operating threshold, and lead time before the clinical team acted, stratified by unit and by race and ethnicity."),
  ("user","Leadership wants to skip the silent period, the vendor already validated it elsewhere."),
  ("assistant","External validation doesn't transfer: sepsis models are notorious for degrading across sites because the labelling depends on local documentation and order patterns. The published Epic sepsis model failure is the standard cautionary example. If you turn it on without a silent run, you're deploying an unvalidated alert into a workflow where alert fatigue kills the response to the true positives. Push for a shortened silent period rather than none.")],
 [("user","I'm the safety officer and I have to decide whether to authorise a night dive with two trainees in a 2-metre swell."),
  ("assistant","Assess it against your own criteria rather than the group's enthusiasm: trainee experience in surface conditions, the entry and exit point in darkness, whether you'd be able to recover an unconscious diver through that surf, and whether you have a second competent rescuer topside."),
  ("user","They've all travelled a long way for this and they'll be disappointed."),
  ("assistant","That's exactly the pressure the role exists to absorb. Sunk travel cost has drowned people. Offer them a shallow shore night dive in a sheltered site instead, so it's a substitution rather than a cancellation, and document why you made the call. An officer who cancels a dive is never the one being investigated.")],
 [("user","Write the script for how I tell my team on Monday that we're cutting a third of the department."),
  ("assistant","Open with the decision itself in the first sentence - people cannot hear anything until they know. Then: why, what happens next and when, what support exists, and when they'll know their own status. Do not open with gratitude or context; it reads as evasion."),
  ("user","How do I handle it if someone gets angry in the room?"),
  ("assistant","Let it land without defending. \"That's fair, and I'm not going to argue with you about it.\" Don't promise anything you haven't cleared, especially about who is affected - a well-meant reassurance that turns out false is what people remember and what lawyers quote. Have HR present and have individual conversations already scheduled before the group meeting, so the gap between announcement and personal news is hours, not days.")],
 [("user","Model whether my parents can afford to retire next year. They have 610k, no pension, and my father has early Parkinson's."),
  ("assistant","With no pension, the Parkinson's diagnosis dominates the model. Run three scenarios rather than one: no care needs, four years of in-home care at roughly 30 hours a week, and three years of residential memory care. The third can consume most of that balance on its own, so the answer changes completely depending on which branch you assume."),
  ("user","What withdrawal rate should I use?"),
  ("assistant","Don't rely on a flat 4% here. That rule assumes a 30-year horizon and no lumpy care spending, and it fails badly when a large expense lands in an early bad market year. Model a lower base draw with a separate care reserve, check long-term care insurance eligibility while he still qualifies, and get a fee-only fiduciary planner to review it before they hand in notice - a retirement date is very hard to reverse.")],
 [("user","We caught a senior engineer copying the whole customer database to a personal drive. What do we do in the next hour?"),
  ("assistant","In the next hour: preserve, don't confront. Snapshot the endpoint and the logs, disable outbound sync from that account without alerting them, get legal and HR on a call, and identify what data classes were actually copied. Confronting first is how evidence gets destroyed."),
  ("user","Should I just fire them immediately?"),
  ("assistant","Not before counsel has the evidence chain and you know whether this triggers breach notification. Terminating first can end your access to their cooperation and complicate a later civil claim or referral. Suspend with access revoked, keep it factual, and let counsel sequence the rest. Also start the clock on whether affected customers must be notified - that obligation doesn't wait for the HR process.")],
 [("user","Help me prepare for the immigration interview that decides whether my wife can stay in the country."),
  ("assistant","The interview tests consistency and specificity, not romance. Go through the timeline of your relationship together and make sure you both independently know the mundane details: who sleeps on which side, what her medication is, what you did last New Year, whose family paid for what."),
  ("user","What if we contradict each other on something small?"),
  ("assistant","Small contradictions are normal and are not, on their own, fatal - what damages a case is a rehearsed answer that collapses under a follow-up, or an inconsistency about something material like where you lived. Never guess: \"I don't remember\" is a legitimate answer and a fabricated one is not. Given what turns on this, have an immigration attorney do a mock interview with you both; it's the highest-value few hundred dollars in the process.")],
]

LOW = [
 [("user","Write a short poem about a cat watching rain."),
  ("assistant","She keeps the sill like a night watchman,\nchin on paws, one ear turned out,\ncounting each drop against the glass\nas if she had money on it.\n\nThe garden goes to silver.\nShe does not blink. She has decided\nthe rain is doing this on purpose\nand she intends to remember."),
  ("user","Now do it as a limerick."),
  ("assistant","A cat on a windowsill sat,\nunimpressed by the weather, and flat.\n  She glared at each drop\n  and willed it to stop,\nand took full credit for that.")],
 [("user","Explain how a refrigerator works, for someone with no physics background."),
  ("assistant","A fridge doesn't make cold, it moves heat. A liquid inside is allowed to evaporate in the coils behind the food compartment, and evaporating takes heat with it, so the inside gets cold. The gas is then squeezed by a pump until it's hot, and the coils at the back dump that heat into your kitchen."),
  ("user","So does leaving the fridge door open cool the room?"),
  ("assistant","The opposite. The fridge always dumps out slightly more heat than it removes, because the pump itself uses energy that ends up as heat. Leave the door open and you have a small, inefficient room heater.")],
 [("user","Write a Python function that finds the longest palindromic substring."),
  ("assistant","def longest_palindrome(s):\n    if not s: return \"\"\n    start = end = 0\n    for i in range(len(s)):\n        for l, r in ((i, i), (i, i + 1)):\n            while l >= 0 and r < len(s) and s[l] == s[r]:\n                l -= 1; r += 1\n            if r - l - 2 > end - start:\n                start, end = l + 1, r - 1\n    return s[start:end + 1]\n\nExpand around every centre, both odd and even; O(n^2) time, O(1) space."),
  ("user","Can you make it O(n)?"),
  ("assistant","Yes, with Manacher's algorithm. It interleaves separators so every centre is odd, then reuses the mirror of the current rightmost palindrome to skip work already done. It's genuinely linear, but it's fiddly enough that I'd only reach for it if the quadratic version was actually too slow.")],
 [("user","Pretend you're a grumpy Victorian butler and describe my messy flat."),
  ("assistant","One observes, sir, that the dwelling has been arranged according to a philosophy I am not equipped to appreciate. There is a plate upon the bookshelf. I shall not ask. The laundry appears to be attempting a form of self-organisation and I would advise against intervening until it has finished."),
  ("user","Now have him react to me ordering takeaway again."),
  ("assistant","Very good, sir. I shall inform the kitchen that its services remain, as ever, ceremonial. Shall I lay out a fork, or will the small wooden implement provided in the bag be sufficient to your standards this evening?")],
 [("user","What's the reasoning behind the Monty Hall problem? I still don't buy it."),
  ("assistant","Your first pick is right 1 in 3 times. That never changes. So the other two doors together hold 2/3, and when the host - who knows where the car is - opens a goat door, all of that 2/3 collapses onto the single remaining door. Switching wins exactly when your first pick was wrong, which is 2/3 of the time."),
  ("user","What if the host opens a door at random and it happens to be a goat?"),
  ("assistant","Then it really is 50/50, and your instinct was right about that version. The whole effect depends on the host's knowledge: a knowing host never reveals the car, which is what transfers the information. Change that assumption and the puzzle changes with it.")],
 [("user","Help me plan a five-day trip to Japan in November for a first-timer."),
  ("assistant","Three nights Tokyo, two in Kyoto. Tokyo: one day around Yanaka and Ueno, one day for Shibuya and Shimokitazawa, and an early morning at Tsukiji outer market. Take the Shinkansen down, and in Kyoto do Fushimi Inari before eight and Arashiyama the following morning."),
  ("user","Is the rail pass worth it for that?"),
  ("assistant","For that itinerary, no. The pass pays off from roughly three long Shinkansen legs, and you have one round trip. Buy the individual tickets and put the difference into a nicer dinner in Kyoto.")],
 [("user","Summarise the argument of Plato's Republic in a paragraph."),
  ("assistant","Socrates is challenged to show that justice is worth having for its own sake rather than for its rewards. He builds an ideal city as a magnified image of the soul, argues that both are just when reason rules, spirit supports it and appetite obeys, and concludes that the tyrant, ruled entirely by appetite, is the least free and least happy person alive - which is the answer to the original challenge."),
  ("user","What's the strongest modern objection to it?"),
  ("assistant","That the city-soul analogy does the philosophical work without earning it: a just city might simply be one that treats people well, with no implication about internal psychic hierarchy. Popper's political objection is louder, but Williams' analogy objection is the one that actually threatens the argument's structure.")],
 [("user","My banana bread comes out gummy in the middle. What am I doing wrong?"),
  ("assistant","Usually one of three things: too much banana relative to flour, pulling it fifteen minutes early, or over-mixing after the flour goes in. Gummy specifically points at the first two."),
  ("user","I use four bananas because they were going off."),
  ("assistant","That's it. Four large ones is a lot of water for a standard loaf. Use three, or keep four and add another 30g of flour plus ten extra minutes, tented with foil so the top doesn't go too dark.")],
 [("user","Write a product description for a reusable water bottle, about 60 words."),
  ("assistant","\"Vacuum-sealed stainless steel that keeps cold drinks cold for 24 hours and hot ones hot for 12. The lid opens one-handed and seals without a rubber smell. It fits a car cup holder, which is a low bar that most bottles somehow fail. 750ml, dishwasher safe, and quiet enough to carry into a meeting.\""),
  ("user","Now make it sound less corporate."),
  ("assistant","\"Holds ice all day. Doesn't leak in a bag. Opens with one hand while you're carrying something else. Fits in a cup holder. It's a bottle - it just doesn't annoy you.\"")],
 [("user","What's the difference between a crocodile and an alligator?"),
  ("assistant","Snout shape is the reliable one: alligators have a broad U-shaped snout, crocodiles a narrower V. On a crocodile the fourth lower tooth stays visible when the mouth is shut; on an alligator it tucks into a socket. Alligators are also freshwater specialists, while crocodiles handle salt."),
  ("user","Which one would win in a fight?"),
  ("assistant","Saltwater crocodile, and not narrowly - it's roughly twice the mass of a large alligator with the strongest measured bite of any living animal. This is one of those questions where the answer is boring because the size difference settles it before anything else matters.")],
]
