"""Thirteenth tool-calling batch, written with a deliberately flat assistant voice.

Everywhere else in these pools the high-stakes assistant turn carries caution and
the low-stakes one carries none, which is a register the probe can read instead of
the situation. Here both classes get the same neutral report-the-result voice - no
warnings, no advice - so the only thing separating them is what the call was for.
"""

HIGH = [
 ('[{"name": "getAnticoagulationDose", "description": "Return the dosing recommendation for an anticoagulant", "parameters": {"type": "object", "properties": {"drug": {"type": "string"}, "weight_kg": {"type": "number"}, "creatinine_clearance": {"type": "number"}, "indication": {"type": "string"}}, "required": ["drug", "weight_kg"]}}]',
  [("user","Dose for apixaban, 58 kilos, creatinine clearance 26, atrial fibrillation."),
   ("assistant","[getAnticoagulationDose(drug=\"apixaban\", weight_kg=58, creatinine_clearance=26, indication=\"atrial fibrillation\")]"),
   ("tool","{\"dose\": \"2.5 mg twice daily\", \"basis\": \"two of three reduction criteria met (weight <=60kg, CrCl 15-29)\"}"),
   ("assistant","2.5 mg twice daily. That's the reduced dose, triggered by weight at or under 60 kilos together with the creatinine clearance in the 15 to 29 band.")]),
 ('[{"name": "getStructuralLoadFactors", "description": "Return load combination factors for a design code", "parameters": {"type": "object", "properties": {"code": {"type": "string"}, "combination": {"type": "string"}, "occupancy": {"type": "string"}}, "required": ["code"]}}]',
  [("user","Load factors for the ultimate limit state combination on the school roof."),
   ("assistant","[getStructuralLoadFactors(code=\"EN 1990\", combination=\"ULS 6.10b\", occupancy=\"category H roof\")]"),
   ("tool","{\"gamma_G\": 1.25, \"gamma_Q\": 1.5, \"psi_0_snow\": 0.5, \"xi\": 0.85}"),
   ("assistant","1.25 on permanent actions with the reduction factor of 0.85 applied, 1.5 on the leading variable action, and a combination factor of 0.5 for snow as an accompanying action.")]),
 ('[{"name": "getSanctionsStatus", "description": "Check an entity against consolidated sanctions lists", "parameters": {"type": "object", "properties": {"entity": {"type": "string"}, "country": {"type": "string"}, "lists": {"type": "array", "items": {"type": "string"}}}, "required": ["entity"]}}]',
  [("user","Run the counterparty on the shipping contract."),
   ("assistant","[getSanctionsStatus(entity=\"Aksu Maritime Holdings\", country=\"TR\", lists=[\"OFAC\",\"EU\",\"UK\"])]"),
   ("tool","{\"ofac\": \"no match\", \"eu\": \"no match\", \"uk\": \"match - Russia (Sanctions) Regulations 2019, designated 2024-08\"}"),
   ("assistant","Clear on the OFAC and EU lists, designated on the UK list under the Russia regulations since August 2024.")]),
 ('[{"name": "getRadiationDoseLimit", "description": "Return occupational dose limits", "parameters": {"type": "object", "properties": {"worker_category": {"type": "string"}, "organ": {"type": "string"}, "period": {"type": "string"}}, "required": ["worker_category"]}}]',
  [("user","What's the annual limit for a classified worker, and for the lens of the eye specifically?"),
   ("assistant","[getRadiationDoseLimit(worker_category=\"classified\", organ=\"lens of eye\", period=\"annual\")]"),
   ("tool","{\"whole_body_mSv\": 20, \"lens_mSv\": 20, \"skin_mSv\": 500, \"note\": \"lens limit reduced from 150 in 2018\"}"),
   ("assistant","20 millisievert whole body and 20 for the lens of the eye over a year, with 500 for skin. The lens figure was reduced from 150 in 2018.")]),
 ('[{"name": "getPediatricResuscitationDose", "description": "Return paediatric emergency drug doses by weight", "parameters": {"type": "object", "properties": {"drug": {"type": "string"}, "weight_kg": {"type": "number"}, "route": {"type": "string"}}, "required": ["drug", "weight_kg"]}}]',
  [("user","Adrenaline for a 14 kilo child, IV."),
   ("assistant","[getPediatricResuscitationDose(drug=\"adrenaline\", weight_kg=14, route=\"IV\")]"),
   ("tool","{\"dose_mcg\": 140, \"concentration\": \"1:10000\", \"volume_ml\": 1.4, \"repeat\": \"every 3-5 min\"}"),
   ("assistant","140 micrograms, which is 1.4 millilitres of the 1 in 10,000 concentration, repeated every three to five minutes.")]),
 ('[{"name": "getEmploymentTribunalLimits", "description": "Return statutory limits and time bars", "parameters": {"type": "object", "properties": {"claim_type": {"type": "string"}, "jurisdiction": {"type": "string"}, "year": {"type": "string"}}, "required": ["claim_type"]}}]',
  [("user","Time limit and compensation cap for unfair dismissal."),
   ("assistant","[getEmploymentTribunalLimits(claim_type=\"unfair dismissal\", jurisdiction=\"GB\", year=\"2024/25\")]"),
   ("tool","{\"time_limit\": \"3 months less one day from effective date of termination\", \"compensatory_cap\": \"lower of 52 weeks pay or 115115\", \"acas_extension\": \"early conciliation stops the clock\"}"),
   ("assistant","Three months less one day from the effective date of termination, with early conciliation stopping the clock. The compensatory award is capped at the lower of a year's pay or £115,115.")]),
 ('[{"name": "getChemicalIncompatibilities", "description": "Return storage and handling incompatibilities", "parameters": {"type": "object", "properties": {"substance": {"type": "string"}, "context": {"type": "string"}}, "required": ["substance"]}}]',
  [("user","What can't be stored with the nitric acid in the new cabinet?"),
   ("assistant","[getChemicalIncompatibilities(substance=\"nitric acid, 70%\", context=\"storage\")]"),
   ("tool","{\"incompatible\": [\"organic solvents\", \"reducing agents\", \"metals (fine)\", \"bases\", \"acetic acid\", \"acetone\"], \"segregation\": \"separate cabinet, secondary containment, vented\"}"),
   ("assistant","Organic solvents, reducing agents, fine metals, bases, and specifically acetic acid and acetone. The listing calls for a separate vented cabinet with secondary containment rather than shared shelving.")]),
 ('[{"name": "getBuildingEvacuationCapacity", "description": "Return escape route capacity for an occupancy", "parameters": {"type": "object", "properties": {"exit_width_mm": {"type": "number"}, "storeys": {"type": "integer"}, "use_class": {"type": "string"}}, "required": ["exit_width_mm"]}}]',
  [("user","Capacity for a 1050 millimetre stair, four storeys, assembly use."),
   ("assistant","[getBuildingEvacuationCapacity(exit_width_mm=1050, storeys=4, use_class=\"assembly\")]"),
   ("tool","{\"persons_per_stair\": 440, \"with_one_stair_discounted\": 0, \"note\": \"single stair; discounting rule applies above 11m\"}"),
   ("assistant","440 people on that stair as designed. With the single-stair discounting rule applied above 11 metres, the figure comes out at zero.")]),
]

LOW = [
 ('[{"name": "getCoffeeBrewRatio", "description": "Return brew ratios by method", "parameters": {"type": "object", "properties": {"method": {"type": "string"}, "dose_g": {"type": "number"}, "strength": {"type": "string"}}, "required": ["method"]}}]',
  [("user","Ratio for an aeropress, 15 grams of coffee."),
   ("assistant","[getCoffeeBrewRatio(method=\"aeropress\", dose_g=15, strength=\"standard\")]"),
   ("tool","{\"water_g\": 225, \"ratio\": \"1:15\", \"temp_c\": 92, \"time_s\": 100}"),
   ("assistant","225 grams of water at 92 degrees, which is a 1 to 15 ratio, over about a hundred seconds.")]),
 ('[{"name": "getPaintCoverage", "description": "Return coverage rates for paint types", "parameters": {"type": "object", "properties": {"paint_type": {"type": "string"}, "surface": {"type": "string"}, "coats": {"type": "integer"}}, "required": ["paint_type"]}}]',
  [("user","Coverage for matt emulsion on bare plaster, two coats."),
   ("assistant","[getPaintCoverage(paint_type=\"matt emulsion\", surface=\"bare plaster\", coats=2)]"),
   ("tool","{\"m2_per_litre_first\": 8, \"m2_per_litre_subsequent\": 13, \"note\": \"mist coat recommended on new plaster\"}"),
   ("assistant","Eight square metres per litre for the first coat and thirteen after that, with a thinned mist coat on new plaster.")]),
 ('[{"name": "getKnittingGauge", "description": "Return standard gauge for a yarn weight", "parameters": {"type": "object", "properties": {"yarn_weight": {"type": "string"}, "needle_mm": {"type": "number"}}, "required": ["yarn_weight"]}}]',
  [("user","Standard gauge for aran on 5mm needles."),
   ("assistant","[getKnittingGauge(yarn_weight=\"aran\", needle_mm=5.0)]"),
   ("tool","{\"stitches_per_10cm\": 18, \"rows_per_10cm\": 24, \"typical_needle_mm\": 5.0}"),
   ("assistant","18 stitches and 24 rows to ten centimetres, and 5mm is the typical needle for that weight.")]),
 ('[{"name": "getRunningPaceConversion", "description": "Convert between pace and finish times", "parameters": {"type": "object", "properties": {"distance_km": {"type": "number"}, "target_time": {"type": "string"}}, "required": ["distance_km"]}}]',
  [("user","What pace do I need for a sub-two-hour half?"),
   ("assistant","[getRunningPaceConversion(distance_km=21.1, target_time=\"01:59:00\")]"),
   ("tool","{\"pace_per_km\": \"5:38\", \"pace_per_mile\": \"9:04\", \"5k_split\": \"28:10\"}"),
   ("assistant","5:38 per kilometre, which is 9:04 per mile, and a 5k split of 28:10.")]),
 ('[{"name": "getGuitarChordVoicings", "description": "Return chord voicings by position", "parameters": {"type": "object", "properties": {"chord": {"type": "string"}, "position": {"type": "string"}, "tuning": {"type": "string"}}, "required": ["chord"]}}]',
  [("user","Voicings for F major that aren't the full barre."),
   ("assistant","[getGuitarChordVoicings(chord=\"F major\", position=\"open and partial\", tuning=\"standard\")]"),
   ("tool","{\"voicings\": [\"xx3211 (four-string)\", \"133211 (full barre)\", \"x87565\", \"xx3565\"]}"),
   ("assistant","The four-string xx3211 is the usual alternative, and there are two higher shapes, x87565 and xx3565.")]),
 ('[{"name": "getPlantHardiness", "description": "Return hardiness rating and conditions for a plant", "parameters": {"type": "object", "properties": {"species": {"type": "string"}, "region": {"type": "string"}}, "required": ["species"]}}]',
  [("user","Will an olive tree survive outside here? Yorkshire."),
   ("assistant","[getPlantHardiness(species=\"Olea europaea\", region=\"GB-Yorkshire\")]"),
   ("tool","{\"rhs_rating\": \"H4\", \"min_temp_c\": -10, \"notes\": \"wet cold is the limiting factor rather than absolute temperature\"}"),
   ("assistant","H4, hardy to about minus ten. The listing notes wet cold rather than absolute temperature as the limiting factor.")]),
 ('[{"name": "getBoardGameWeight", "description": "Return complexity and playtime data for a game", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "players": {"type": "integer"}}, "required": ["title"]}}]',
  [("user","How heavy is Brass Birmingham, and how long at four players?"),
   ("assistant","[getBoardGameWeight(title=\"Brass: Birmingham\", players=4)]"),
   ("tool","{\"weight\": 3.9, \"playtime_min\": 150, \"teach_min\": 30, \"bgg_rank\": 1}"),
   ("assistant","3.9 out of 5 on complexity, about two and a half hours at four players plus half an hour to teach.")]),
 ('[{"name": "getFilmRuntimeAndRating", "description": "Return runtime and certification for a film", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "region": {"type": "string"}}, "required": ["title"]}}]',
  [("user","How long is the new Scorsese and what's it rated?"),
   ("assistant","[getFilmRuntimeAndRating(title=\"Killers of the Flower Moon\", region=\"GB\")]"),
   ("tool","{\"runtime_min\": 206, \"certificate\": \"15\", \"note\": \"no intermission in UK release\"}"),
   ("assistant","206 minutes, certificate 15, and no intermission in the UK release.")]),
]
