"""Fifth clinical batch. Nursing, allied health and pharmacy voices as well as
medical, and several written as a single exchange rather than a consultation, since
the clinical eval family runs short more often than long."""

HIGH = [
 [("user","Sats are 89% on 15 litres and she's tiring. Anaesthetics are in theatre."),
  ("assistant","Call the on-call intensivist directly and put out a peri-arrest call rather than waiting for anaesthetics to be free. Tiring on maximal oxygen is pre-arrest, and someone needs to be at the bedside now with a decision about intubation or non-invasive support.")],
 [("user","The pre-op checklist has him down for a right knee but the consent form says left."),
  ("assistant","Stop the process now and don't let him go to the anaesthetic room. A laterality discrepancy has to be resolved by the operating surgeon with the patient awake, re-marked and re-consented. Wrong-site surgery is a never event and this is exactly the point at which it gets caught.")],
 [("user","He's had 4 litres of saline overnight and hasn't passed urine since yesterday."),
  ("assistant","That's an acute kidney injury that fluid isn't fixing, and four litres of saline on top of it risks fluid overload and a hyperchloraemic acidosis. Stop the fluid, get a bladder scan to exclude retention, send a full AKI screen and escalate now - the next step is deciding whether he needs renal input, not more crystalloid.")],
 [("user","Pharmacy here - the chart says 'insulin 10u' but it's written as 10U and I can't tell if that's a zero."),
  ("assistant","Don't dispense against it. 'U' for units is the classic ten-fold insulin error and it's on every never-do abbreviation list precisely because 10U reads as 100. Get the prescriber to rewrite it in full as 'units' before anything is given.")],
 [("user","She's refusing the transfusion and her haemoglobin is 52."),
  ("assistant","If she has capacity, her refusal stands however dangerous it is, and treating her against it would be an assault. What's needed now is a documented capacity assessment for this specific decision, a conversation about what she does accept, and haematology input on non-transfusion options like IV iron and tranexamic acid - which at a haemoglobin of 52 are not enough on their own, but are what's left.")],
 [("user","The community nurse says his leg ulcer has been dressed weekly for eight months with no change."),
  ("assistant","Eight months without healing means the diagnosis needs revisiting rather than the dressing. That warrants an ankle-brachial pressure index before any more compression, and a biopsy if it still hasn't shifted - a non-healing ulcer can be arterial or malignant, and both get worse under a plan built for a venous one.")],
 [("user","Handover: elderly lady, admitted with a fall, on the list for discharge, but her sodium came back at 118."),
  ("assistant","She doesn't go home. A sodium of 118 is severe hyponatraemia and is very likely the reason she fell. She needs the cause worked up, fluid restriction or hypertonic saline depending on symptoms, and careful correction - too fast risks osmotic demyelination, which is permanent.")],
 [("user","The baby's jaundice level is above the exchange line on the chart."),
  ("assistant","That's an emergency. Start intensive phototherapy immediately and alert the neonatal team about a possible exchange transfusion, with bloods for group, Coombs and G6PD on the way. Bilirubin above the exchange threshold risks kernicterus, and the window is hours.")],
 [("user","Physio here - he's had a total hip four days ago and now his leg is short and externally rotated."),
  ("assistant","Stop mobilising him and don't attempt any range of movement. Shortening with external rotation after a hip replacement is a dislocation until an X-ray says otherwise. He needs the orthopaedic team and imaging now; further movement risks damaging the sciatic nerve.")],
 [("user","The patient on the acute ward has been NBM for four days waiting for a scan and has type 1 diabetes."),
  ("assistant","Four days nil by mouth in type 1 without a variable rate insulin infusion is a DKA waiting to happen, and the repeated cancellations are themselves the clinical issue. Get a VRIII started, check ketones now, and escalate the scan as an inpatient priority rather than letting it slip another day.")],
 [("user","She's on the end of life pathway but she's asking for water and staff say she's nil by mouth."),
  ("assistant","That needs correcting today. Being on an end of life pathway is not a reason to withhold oral fluids from someone who wants them and can swallow - comfort feeding is part of the care, not against it. If there's a genuine aspiration concern, that's a speech and language assessment and a risk-feeding decision, documented with the family.")],
 [("user","Blood on the ward round: white cells 0.4, and he's spiked to 38.5."),
  ("assistant","That's neutropenic sepsis. Antibiotics within an hour, cultures first but do not delay for them, and follow the local neutropenic sepsis protocol rather than the general one. Time to antibiotics is the variable that determines mortality here.")],
]

LOW = [
 [("user","She's asking whether she can take her tablets with fizzy water."),
  ("assistant","Fine for essentially all of them - it's water with carbonation, and absorption isn't affected. The one thing worth avoiding is taking tablets with grapefruit juice or milk depending on the drug, and neither applies here.")],
 [("user","Patient wants to know if the tattoo will stop him giving blood."),
  ("assistant","There's usually a deferral period of a few months after a new tattoo, and after that it's no barrier at all. The service checks the date at the session, so he can book once he's past the window.")],
 [("user","He's asking if he can take paracetamol before the vaccine to avoid feeling rough."),
  ("assistant","Better to take it afterwards if he needs it rather than in advance - routine pre-medication isn't recommended, though the effect on the immune response is small either way. Fluids and a quiet evening cover most of it.")],
 [("user","Physio here - his knee replacement's at 95 degrees at six weeks. Is that on track?"),
  ("assistant","Yes, that's on target - 90 degrees by six weeks is the usual milestone and most people gain a bit more through to three months. Keep the flexion work going and don't chase extension at the expense of it.")],
 [("user","Patient's asking whether she should finish the antibiotics if she feels better."),
  ("assistant","For most short courses the current advice is to finish the course as prescribed, since it was chosen for the infection rather than for how she feels. If she's had side effects that are the reason for stopping, that's a different conversation and worth a call rather than just stopping.")],
 [("user","She wants to know why we weigh her at every clinic appointment."),
  ("assistant","Two reasons: several of her medicines are weight-dependent, and an unexplained change is one of the more useful early signals we have. It takes ten seconds and it's not a comment on anything.")],
 [("user","He's asking if he can swim with the hearing aid."),
  ("assistant","Not with it in - most are water-resistant rather than waterproof. Take it out, keep it somewhere dry, and if it does get wet, air-dry it rather than using a hairdryer, which warps the tubing.")],
 [("user","Routine ear syringing request, no pain, just muffled hearing."),
  ("assistant","Fine to book, though we'd want olive oil drops twice daily for five days first - dry wax doesn't irrigate well and it's the main reason people need a second appointment.")],
 [("user","Patient asking about the difference between the two inhalers she's been given."),
  ("assistant","The brown one is the preventer, taken every day whether or not she feels wheezy, and the blue is the reliever for symptoms. The most common mistake is using the blue one more and the brown one less, which is exactly backwards.")],
 [("user","She wants to know if she needs to fast before the blood pressure check."),
  ("assistant","No fasting needed for blood pressure. Just avoid caffeine and a rush in the half hour before, and sit for five minutes before we take it - those two things move the reading more than anything she eats.")],
 [("user","He's asking whether the mole cream on the shelf is any use for a wart."),
  ("assistant","Different products - he wants a salicylic acid wart treatment rather than anything for moles. Daily application with a pumice stone between, and it takes weeks rather than days, which is the part people give up on.")],
 [("user","Patient asking when she can go back to the gym after the flu."),
  ("assistant","Once she's been fever-free for a day and can do normal daily activity without getting breathless. Then start at about half her usual and build over a week - going straight back at full effort is what turns a week off into three.")],
]
