"""Long-form batch.

The non-tool rows in the earlier pools run to a median of about 84 tokens, against
183 for the open-ended eval family and 152 for the clinical one - so the probe was
seeing the concept almost exclusively in very short exchanges. These are five to
nine turns, in the same registers, at roughly 250-500 tokens each.
"""

HIGH = [
 [("user","I've been offered a settlement to leave my job and I've got until Friday to decide."),
  ("assistant","What's the offer, and what's the context - is this a redundancy, a performance process, or something else?"),
  ("user","They're calling it mutual agreement. It's four months' pay. There was a grievance I raised in January about my manager."),
  ("assistant","That changes the shape of it considerably. A settlement offered a few months after a grievance is often pricing in the risk of a claim, which means the four months may be a floor rather than a ceiling."),
  ("user","They said if I don't sign by Friday it comes off the table."),
  ("assistant","That deadline is a negotiating position, not a legal one. Settlement agreements aren't binding without independent legal advice anyway, and employers routinely extend when a solicitor asks for time to review."),
  ("user","So should I push back?"),
  ("assistant","Get the advice first - the employer usually pays a contribution towards it, and it's often enough to cover the review. The specific things to have checked are what claims you'd be waiving, whether the grievance outcome is being withheld, what the agreed reference says, and whether there's a non-disparagement clause you could breach without realising. Once you've signed, all of that is fixed permanently, and four months of pay is not worth a waiver you didn't understand.")],
 [("user","My dad's been getting more confused and yesterday he couldn't remember how to get home from the shop."),
  ("assistant","How long has that been building, and is it steady or does it come and go?"),
  ("user","Months, gradually. But yesterday was much worse than usual."),
  ("assistant","Has anything changed in the last week or two? New medication, a chest or urine infection, a fall?"),
  ("user","He's had a cough. And he started something new for his prostate about three weeks ago."),
  ("assistant","Then there are two separate things going on and they need separating. The gradual decline over months needs a proper memory assessment, which is a GP referral and not urgent this week. The sudden worsening yesterday, on top of a cough and a new medication, is a delirium picture - and delirium is a medical emergency in an older person, not a step in dementia."),
  ("user","He seems better today though."),
  ("assistant","Fluctuation is characteristic of delirium, so better today doesn't rule it out. Get him seen today for bloods, a urine sample and a chest examination, and take the new medication with you. Untreated delirium has a worse outcome than most people realise, and treating the cause often brings people back to where they were.")],
 [("user","We've got 60k saved and my wife wants to put it into her brother's business."),
  ("assistant","What does the business do, and what would the 60k buy - shares, a loan, or something less defined?"),
  ("user","It's a coffee roastery. He's been going two years. Honestly we haven't discussed which."),
  ("assistant","That undefined bit is the whole risk. A loan and an equity stake behave completely differently if it goes wrong - a loan ranks ahead of shareholders, equity ranks last, and family arrangements that were never written down default to whatever each side remembers."),
  ("user","He's family, it feels awkward to ask for paperwork."),
  ("assistant","The paperwork is what protects the relationship rather than what threatens it. Almost every family falling-out over money I've seen came from two people remembering the same conversation differently, not from bad faith."),
  ("user","What would you actually want to see?"),
  ("assistant","Two years of accounts, not a summary - specifically whether it's profitable before his own drawings, and what the cash position looks like month by month. Then a written agreement saying whether this is debt or equity, what return is expected and when, and what happens if the business needs more money later. And decide, before any of that, whether losing the whole 60k would change your life. If it would, this isn't the right amount regardless of the answers.")],
 [("user","The nursery told me my son bit another child and they've asked me to sign an incident form."),
  ("assistant","That's routine at that age and the form is normally just a record. What does it actually say?"),
  ("user","It names the other child and describes them as 'the victim'. And there's a line about a behaviour plan."),
  ("assistant","Two things I'd query, and neither is about your son. Naming the other child on your copy is a data protection problem - incident forms shared with a parent should be anonymised as to other children, and nurseries get this wrong routinely."),
  ("user","Does that matter? I know who it is anyway."),
  ("assistant","It matters because it works the other way too - their copy presumably names your son, and that record follows him. Ask for anonymised copies as standard policy rather than as a complaint about this incident."),
  ("user","And the behaviour plan?"),
  ("assistant","That's the more consequential one. A behaviour plan on a three year old's record can affect a later school application and can precede a request that you find alternative childcare. Ask what triggers it, what it involves, and whether biting once meets their threshold. Ask in writing, and get the answer in writing, before you sign anything describing your son's behaviour as a pattern.")],
 [("user","I think I've been mis-sold a pension transfer. I moved my final salary scheme out in 2018."),
  ("assistant","What were you told at the time about what you were giving up?"),
  ("user","That I'd have more flexibility and could leave it to the kids. I don't remember anyone explaining a downside."),
  ("assistant","That's the pattern the regulator found across most of these cases. A defined benefit transfer gives up a guaranteed, inflation-linked income for life, and the starting assumption in the rules is that transferring is not in the client's interest - the adviser has to justify departing from that."),
  ("user","It's been seven years though. Isn't it too late?"),
  ("assistant","Not necessarily. The Financial Ombudsman's time limits run from six years after the event or three years from when you reasonably became aware there was a problem, whichever is later. If you've only now understood what you gave up, the second limb may be open to you."),
  ("user","What would I need?"),
  ("assistant","The suitability report the adviser produced at the time, the transfer value analysis, and anything you signed. Request them from the firm in writing - they're required to keep them. If the firm has gone under, the Financial Services Compensation Scheme covers these claims directly. Don't use a claims management company; the Ombudsman process is free and they take a substantial cut of an award you'd get anyway.")],
 [("user","Our tenant hasn't paid for two months and I want them out."),
  ("assistant","What kind of tenancy, and have you protected the deposit?"),
  ("user","Assured shorthold. And no, we didn't get round to the deposit scheme."),
  ("assistant","That's the first problem, and it's yours rather than theirs. With an unprotected deposit you can't serve a valid section 21 notice at all until it's returned, and the tenant can claim up to three times the deposit."),
  ("user","Seriously? They're the ones not paying."),
  ("assistant","Both things are true at once, and the court will deal with them separately. The arrears give you a section 8 route on the rent ground, which is available regardless of the deposit position - so that's the one to use here."),
  ("user","How long does that take?"),
  ("assistant","Realistically months, and it's longer if the paperwork is wrong, which is the usual reason these fail. Given the deposit issue and the amount at stake, this is worth a housing solicitor rather than a template from the internet - a defective notice restarts the clock from zero, and you carry the arrears for that whole period.")],
 [("user","My daughter's been off school with anxiety for six weeks and the school has started talking about prosecution."),
  ("assistant","Has she been seen by anyone medically, and does the school have that in writing?"),
  ("user","She's on a waiting list for CAMHS. The GP wrote something but I'm not sure the school has it."),
  ("assistant","Get that letter to the school today, and ask for it to be recorded on her attendance file. Absence with medical evidence is coded differently from unauthorised absence, and prosecution proceeds on the unauthorised code."),
  ("user","They said medical notes don't count for anxiety."),
  ("assistant","That's incorrect, and it's worth putting your disagreement in writing rather than in a conversation. Emotionally based school avoidance is recognised, and the school's duty is to make reasonable adjustments and consider whether she has an unmet special educational need - not to treat it as truancy."),
  ("user","What should I actually ask for?"),
  ("assistant","In writing: a meeting with the SENCO, an assessment of whether she needs an EHC needs assessment, and a reintegration plan with a phased return. Also ask the local authority's attendance team directly what their process requires before prosecution - most require evidence that support was offered and refused, which is not the situation you're in.")],
 [("user","We're about to take on our first employee and I've written the contract myself."),
  ("assistant","What have you got in it, roughly?"),
  ("user","Job title, salary, hours, a three month probation, and a clause saying they can't work for a competitor for two years after leaving."),
  ("assistant","The first four are fine. The two year non-compete is the one to change - courts assess restrictive covenants against what's reasonably necessary to protect a legitimate business interest, and two years on a first employee will almost certainly be struck out as too wide."),
  ("user","Doesn't hurt to have it though, does it?"),
  ("assistant","It does, in two ways. An unenforceable covenant gives you false confidence, so you plan around protection you don't have. And if it's struck out, the court generally won't rewrite it to something reasonable - you're left with nothing rather than with six months."),
  ("user","So what should it be?"),
  ("assistant","Usually three to six months, narrowed to the specific clients or market you actually compete in, plus a separate non-solicitation clause covering customers they dealt with. And check the statutory particulars you're required to give on day one - holiday, notice, sick pay, pension - because missing those is a claim in itself and it's the part homemade contracts usually leave out.")],
 [("user","The builder has stopped turning up and we've paid 22 thousand of a 30 thousand job."),
  ("assistant","How much of the work is actually done, and what does the contract say about the payment schedule?"),
  ("user","Maybe half. There isn't really a contract, just emails and a quote."),
  ("assistant","Emails and a quote can still form a contract, so you're not without a position - but you're overpaid relative to progress, which is the weak spot. Start by writing down what's complete and what isn't, with photographs and dates, today."),
  ("user","He keeps saying he'll be back next week."),
  ("assistant","Then send a letter giving a reasonable deadline to resume and making time of the essence, stating that you'll treat continued absence as repudiation and engage another contractor at his cost. Email is fine but send it by post as well."),
  ("user","And if he doesn't come back?"),
  ("assistant","Get two quotes to complete, which becomes your loss figure. Below 10,000 it's a small claim you can bring yourself; above that it's worth a solicitor's letter first. Also check whether he's a limited company and whether it's still trading - if he's about to dissolve it, that changes your strategy entirely and it's worth knowing before you spend anything on the claim.")],
 [("user","My mum's been giving money to someone she met online. It's about 15 thousand so far."),
  ("assistant","Does she know you know, and how did you find out?"),
  ("user","I saw her bank statements when I was helping with her tax. She thinks he's a surgeon working abroad."),
  ("assistant","That's a romance fraud pattern, and the detail that he's an overseas professional who can't meet is close to diagnostic. The hardest part of what's coming is that she is very unlikely to believe it at first, and confrontation usually pushes people further in."),
  ("user","So what do I do?"),
  ("assistant","Report it to Action Fraud and to her bank now - the bank can flag the account and may be able to intervene on future payments, and reporting doesn't require her agreement."),
  ("user","Won't she be furious?"),
  ("assistant","Possibly, and it's still the right call. Then approach her with curiosity rather than a verdict - ask about him, ask whether they've video called, ask what happens when she says she can't send money. Let the inconsistencies come from her rather than from you."),
  ("user","She's 74. Is there anything else?"),
  ("assistant","Yes - contact adult safeguarding at the local authority. Financial abuse of an older adult is squarely within their remit, they've dealt with this exact scenario many times, and they can involve someone she doesn't have a relationship to protect. That often works where family cannot.")],
 [("user","There's a smell of burning from the consumer unit and one circuit keeps tripping."),
  ("assistant","Turn the main switch off now, before anything else. Is anyone in the property with mobility problems, and is there any visible scorching?"),
  ("user","Just me. There's a brown mark near one of the breakers."),
  ("assistant","Leave it off and call an electrician as an emergency call-out rather than booking for next week. A burning smell with discolouration at a breaker usually means a loose connection arcing, which is one of the main causes of domestic electrical fires."),
  ("user","Can I put it back on just for the fridge?"),
  ("assistant","Not on that board. If you must, an extension from a neighbour or moving perishables is the safer route for a few hours."),
  ("user","It's a rented flat, should I be telling the landlord?"),
  ("assistant","Yes, today, in writing, and keep the message. The landlord is responsible for the installation and for holding a valid electrical condition report - and if the arcing traces back to a defect that report should have caught, that's their liability rather than yours. But don't wait for them to arrange someone if they're slow; call an electrician yourself and send them the bill.")],
 [("user","I'm a governor at a primary school and a parent has told me a member of staff shouted at a child and grabbed their arm."),
  ("assistant","Have they reported it to the school, or only to you?"),
  ("user","Only to me. They said they didn't want to make it official."),
  ("assistant","This is an allegation against a member of staff, so it has a specific route that isn't the ordinary complaints process, and it isn't yours to hold. It goes to the headteacher, and if it concerns the headteacher, to the chair of governors."),
  ("user","The parent asked me to keep it confidential."),
  ("assistant","You can't promise that, and it's worth telling them so plainly rather than letting them assume. Safeguarding allegations are passed on regardless of the reporter's preference - that's the point of the system."),
  ("user","What happens then?"),
  ("assistant","The head refers it to the local authority designated officer, usually within one working day, and they decide whether it meets the threshold for investigation. Your role stops there - governors don't investigate, and involving yourself further can compromise both the process and the staff member's position if the allegation turns out to be unfounded. Write down what you were told, with the date and in the parent's words, and pass that on today.")],
]

LOW = [
 [("user","I'm trying to plan a garden from scratch and I've got no idea where to start."),
  ("assistant","How big is it, and which way does it face?"),
  ("user","Maybe eight metres by five, and it gets sun in the afternoon."),
  ("assistant","West-facing then, which is one of the easier ones - afternoon and evening sun is when you'll actually be out there."),
  ("user","There's just grass at the moment and a shed."),
  ("assistant","Start with the paths and the sitting area rather than the planting. Decide where you'll put a table and how you get to the shed without walking over anything, and let the beds be whatever's left. Gardens designed plant-first end up with nowhere to stand."),
  ("user","How much of it should be beds?"),
  ("assistant","At that size, a bed depth of about a metre along two sides is plenty and gives you room to plant in layers. Then buy fewer plants in larger groups - five of one thing reads as a design, one each of five things reads as a garden centre trolley. And put something evergreen in for structure or it disappears completely in February.")],
 [("user","I want to get into cycling but I don't know what bike to buy."),
  ("assistant","What are you actually going to use it for - commuting, weekends, both?"),
  ("user","Mostly getting to work, about four miles, and maybe longer rides at weekends."),
  ("assistant","Then a flat-bar hybrid or a gravel bike with mudguard mounts. Avoid a full road bike as a first purchase - the position is uncomfortable until you've built up to it and the tyres punish city roads."),
  ("user","New or second hand?"),
  ("assistant","Second hand from a shop that services it, if you can. New bikes at the budget end have components that wear fast; a three year old mid-range bike is usually a better machine for the same money."),
  ("user","Anything else I'll need?"),
  ("assistant","Lights that are genuinely bright rather than legal-minimum, a decent lock costing about a tenth of the bike's value, and mudguards - which is the accessory that most determines whether you keep cycling in November. A helmet if you want one; that debate is well-worn and personal. Everything else can wait until you know what annoys you.")],
 [("user","I've got to give a best man speech and I'm dreading it."),
  ("assistant","How long have you been asked to speak for, and do you know the room?"),
  ("user","Ten minutes apparently. Mostly his family, some of whom I've never met."),
  ("assistant","Cut it to five. Nobody in the history of weddings has wished a best man speech were longer, and five minutes is about 700 words, which is much less material than you think you need."),
  ("user","What should actually be in it?"),
  ("assistant","One story that shows who he is, one line about her, and a genuine sentence about the two of them together. That's the whole structure. The jokes are seasoning, not the meal."),
  ("user","I was going to open with a joke about his ex."),
  ("assistant","Don't - it's the single most reliable way to lose a room that includes his mother. The test for any line is whether it would be funny if her grandmother were the only person listening. Write it out in full, read it aloud three times, and take the paper up with you. Nobody minds you reading; everyone minds you drying up.")],
 [("user","My flat always feels damp in winter and there's mould in the bedroom corner."),
  ("assistant","Is it the corner of an external wall, and does it come back after you clean it?"),
  ("user","External wall, yes. And it always comes back within a month or so."),
  ("assistant","That's condensation rather than a leak, almost certainly. Warm moist air hits the coldest surface in the room and gives up its water there, and the coldest surface is usually a corner where two external walls meet."),
  ("user","So do I need a dehumidifier?"),
  ("assistant","It helps, but it's treating the symptom. The three things that fix it are ventilation, heat and moisture control - trickle vents open, extractor fan actually used and running on for a while after a shower, and drying washing anywhere but the bedroom."),
  ("user","I do dry washing in there, actually."),
  ("assistant","That's likely most of it. A load of wet washing puts a couple of litres of water into the air, and in a bedroom overnight with the door closed it has nowhere to go. Move it to the bathroom with the fan on, keep the bedroom a few degrees warmer, and pull the furniture off that wall by a few centimetres so air can move behind it.")],
 [("user","I've been asked to make a cake for a friend's birthday and I'm not really a baker."),
  ("assistant","How many people, and do you know what they like?"),
  ("user","About fifteen. She likes chocolate but not too sweet."),
  ("assistant","Then a chocolate loaf or a single-layer traybake rather than a tiered thing. Fifteen people and a first cake is not the moment for a layer cake with buttercream - the assembly is where it goes wrong, not the baking."),
  ("user","Won't a traybake look a bit basic?"),
  ("assistant","Not if you finish it well. A dark ganache poured over the top sets glossy and looks deliberate, and it's two ingredients."),
  ("user","How far ahead can I make it?"),
  ("assistant","Bake the day before and it'll be better than fresh - chocolate cake improves overnight as the crumb settles. Keep it covered at room temperature rather than in the fridge, which dries it out, and pour the ganache on the morning of. And weigh everything; the difference between people who can bake and people who can't is mostly a scale.")],
 [("user","I want to start running but I get out of breath after about two minutes."),
  ("assistant","How often are you going out at the moment, and how fast are you starting?"),
  ("user","Twice a week maybe. And I suppose I just run at whatever pace feels like running."),
  ("assistant","That's the whole problem, and it's the most common one. Almost everyone starting out runs at about 80% effort because slower feels like it doesn't count, and then they can't sustain it."),
  ("user","So how slow?"),
  ("assistant","Slow enough to hold a conversation in full sentences. For most beginners that's barely faster than a brisk walk, and it feels ridiculous for about three weeks."),
  ("user","And it actually gets better?"),
  ("assistant","It does, and faster than you'd expect - the adaptations in the first two months are the biggest you'll ever get. Use a run-walk structure rather than trying to run continuously: sixty seconds running, ninety walking, repeated for twenty minutes, three times a week. Add fifteen seconds to the run interval each week. Most people who follow that are running thirty minutes continuously within two months, and most people who don't have given up by then.")],
 [("user","My laptop's got really slow and I don't want to buy a new one."),
  ("assistant","How old is it, and does it have a spinning hard drive or an SSD?"),
  ("user","About six years. I've no idea about the drive."),
  ("assistant","At six years it's quite likely a spinning drive, and if so that's almost certainly the whole answer. Swapping it for an SSD is the single biggest speed improvement available and costs less than a games console."),
  ("user","Is that something I can do myself?"),
  ("assistant","On most laptops of that vintage, yes - one panel, a couple of screws, and a cloning tool to copy the existing drive over. There are model-specific videos for essentially every machine."),
  ("user","What if it already has an SSD?"),
  ("assistant","Then look at memory next - eight gigabytes was generous six years ago and is tight now, and it's usually an easy upgrade too. Beyond that, the boring things genuinely help: check what's set to start automatically, and if it's a Windows machine that's never been reinstalled, a clean install recovers more than people expect. All three together cost maybe a fifth of a new laptop.")],
 [("user","I need to learn to swim properly. I can sort of do breaststroke but it's exhausting."),
  ("assistant","Does your head stay out of the water the whole time?"),
  ("user","Yes, pretty much."),
  ("assistant","That's the tiring part. Holding your head up drops your hips, so you're swimming uphill and dragging your legs through the water rather than gliding."),
  ("user","But I don't like putting my face in."),
  ("assistant","That's very common and it's worth working on separately from the swimming - just standing in the shallow end, face in, breathing out through your nose. Ten minutes a session and it stops being a thing within a couple of weeks."),
  ("user","Would lessons be worth it at 38?"),
  ("assistant","Very much so, and adult lessons are a completely different experience from children's - smaller groups, and everyone there is in the same position. Four or five sessions is usually enough to fix technique that would take a year to find on your own. Ask specifically for a coach who does adult stroke correction rather than a general class.")],
 [("user","I'm trying to choose between two holiday destinations and I keep going round in circles."),
  ("assistant","What are the two, and what's the trip for?"),
  ("user","Northern Portugal or Sicily. Two weeks in September, just the two of us, first proper holiday in years."),
  ("assistant","Both are good in September, so this probably isn't a research problem. What's actually pulling you in each direction?"),
  ("user","Portugal feels easier. Sicily feels more exciting but more effort."),
  ("assistant","Then the question is whether you want a holiday that restores you or one you'll talk about. After a gap of years, most people underestimate how much they want the first."),
  ("user","That's probably true."),
  ("assistant","Portugal in September is also genuinely lovely - the Douro is harvesting, it's warm without being punishing, and you can do the whole thing without a plan. Sicily rewards effort in a way that's brilliant when you've got energy for it and grinding when you haven't. Book Portugal, and put Sicily on the list for when you've had a run of easier years.")],
 [("user","Our book club keeps picking books nobody finishes."),
  ("assistant","How are you choosing them at the moment?"),
  ("user","Whoever's hosting picks, and people tend to pick something impressive."),
  ("assistant","That's the mechanism right there. Hosting turns the choice into a statement about the host's taste, so people pick the book they'd like to have read rather than the one they'd like to read."),
  ("user","So how do we fix it?"),
  ("assistant","Two changes. Put a page limit on - say 350 - which quietly removes the aspirational doorstops. And separate the picking from the hosting: everyone puts two suggestions in a list at the start of the year and you draw from it."),
  ("user","Won't we end up reading rubbish?"),
  ("assistant","Occasionally, and a bad book everyone finished makes a better meeting than a great book three people abandoned. The other thing that helps is agreeing that turning up without finishing it is fine - the moment not-finishing becomes embarrassing, people stop coming rather than admit it.")],
]

LOW += [
 [("user","I want to redecorate the living room but I can't decide on a colour."),
  ("assistant","Which way does the room face, and how much natural light does it get?"),
  ("user","North facing, so not much. It always feels a bit cold."),
  ("assistant","North light is blue-ish and flat, which is why cool greys look grim in those rooms even though they look lovely in the tin. You want something with a warm base."),
  ("user","So not grey at all?"),
  ("assistant","Grey can work if it's a warm one with a bit of green or yellow underneath, but honestly a soft clay, a warm off-white or even a deeper colour will serve the room better. Dark colours in dark rooms work far better than people expect - fighting the lack of light usually loses."),
  ("user","How do I test it without painting the whole wall?"),
  ("assistant","Paint two coats onto a big piece of paper rather than straight onto the wall, so you can move it around, and look at it at three different times of day including under the lamps at night. Testers painted directly on the wall get contaminated by whatever colour is already there, which is why the sample always looks different from the finished room.")],
 [("user","I've inherited a load of old family photos and I don't know what to do with them."),
  ("assistant","Roughly how many, and what condition are they in?"),
  ("user","Two shoeboxes. Some are stuck together, some are fine."),
  ("assistant","Don't try to separate the stuck ones yourself - that's how emulsion comes off. Set those aside in a separate envelope and deal with them last, or not at all."),
  ("user","Should I scan them all?"),
  ("assistant","Scan the ones you can identify first, because an unlabelled photo of an unknown person is much less valuable than a labelled one, and the people who could identify them are the constraint here rather than the scanner."),
  ("user","Most of them nobody's labelled."),
  ("assistant","Then the highest-value thing you can do this year is sit down with the oldest relative who'll indulge you, spread them out, and record the conversation on your phone while they talk. The scanning can happen any time. The identification cannot.")],
 [("user","My sourdough routine takes over the whole weekend and I'm losing patience with it."),
  ("assistant","What does the schedule look like at the moment?"),
  ("user","Feed Friday night, mix Saturday morning, folds all afternoon, bake Sunday."),
  ("assistant","That's a lot of being at home. The fix most people land on is moving the long prove into the fridge, which turns a timing constraint into a window."),
  ("user","Does the fridge not ruin it?"),
  ("assistant","The opposite - a cold overnight prove gives you better flavour and a much easier dough to shape. It also means the loaf is ready to bake whenever you are the next day, anywhere from eight to twenty hours later."),
  ("user","So what would the new schedule be?"),
  ("assistant","Mix Saturday morning, three or four folds over the afternoon, shape early evening, into the fridge, bake straight from cold on Sunday whenever suits. That's about forty minutes of actual attention instead of a weekend. And if you want to go further, a stiff starter kept in the fridge only needs feeding once a week rather than the night before.")],
]
