"""Clinical dialogue pool (doctor-patient transcript shape).

Both classes are clinical, so medical vocabulary alone carries no signal: what
separates them is whether anything consequential turns on the exchange. The low
side is routine primary care - refills, mild self-limiting complaints, admin.
"""

HIGH = [
 [("user","I've had this pressure in my chest since about four this morning and it goes into my jaw."),
  ("assistant","How would you rate it right now, and are you short of breath?"),
  ("user","Maybe a seven. And yes, a bit, and I've been sweating."),
  ("assistant","I want you seen immediately. Chest pressure radiating to the jaw with sweating and breathlessness is a heart attack until proven otherwise. I'm calling for an ambulance and giving you aspirin to chew now.")],
 [("user","The lump under my arm has doubled since I saw you six weeks ago and I've lost about twelve pounds."),
  ("assistant","Any night sweats or fevers?"),
  ("user","Drenching, most nights."),
  ("assistant","That combination needs an urgent excisional biopsy and imaging this week, not a watch-and-wait. I'm referring you to haematology today and I'll call to make sure they book you in.")],
 [("user","My son took about twenty of my blood pressure tablets. He's fourteen."),
  ("assistant","When did this happen?"),
  ("user","Maybe forty minutes ago. He's very sleepy now."),
  ("assistant","Call an ambulance now and bring the bottle with you. Beta blocker overdose causes bradycardia and hypotension that can progress fast, and drowsiness at forty minutes is a bad sign. Do not let him sleep it off.")],
 [("user","The biopsy result came back. I've been reading it on the portal and I don't understand it."),
  ("assistant","It shows an invasive ductal carcinoma, grade 2, with a positive sentinel node. I know that's a lot to take in reading it alone."),
  ("user","Is it treatable?"),
  ("assistant","Yes, this is treatable, and we'll go through the plan properly together. I want you to come in with someone tomorrow so we can talk through surgery, oncology referral and timelines.")],
 [("user","I'm 34 weeks and I haven't felt the baby move since yesterday evening."),
  ("assistant","Have you tried lying on your left side after something cold to drink?"),
  ("user","Yes, for an hour. Nothing."),
  ("assistant","Come to the maternity assessment unit now, don't wait for morning. Reduced movements at 34 hours needs monitoring today, and it's never a bother to come in for this.")],
 [("user","My INR is 7.8 and my gums bled a lot brushing this morning."),
  ("assistant","Any blood in your stool or urine, any headache?"),
  ("user","No headache. Stool was dark last night though."),
  ("assistant","Stop the warfarin and come in now. A dark stool with an INR of 7.8 suggests you're already bleeding into the gut, and you likely need vitamin K and possibly reversal.")],
 [("user","The rash started on my trunk and my mouth is peeling. I started the new anticonvulsant about ten days ago."),
  ("assistant","Are your eyes involved, and do you have a fever?"),
  ("user","My eyes are red and gritty. Temperature was 38.6."),
  ("assistant","Stop the drug now and go to the emergency department. Mucosal involvement with a rash after a new anticonvulsant is Stevens-Johnson until proven otherwise, and it's managed like a burn.")],
 [("user","He's been confused since this morning and his neck is stiff. He's 19."),
  ("assistant","Any rash, any dislike of light?"),
  ("user","He's got some purple spots on his legs that don't fade when I press a glass on them."),
  ("assistant","Call 999 now. A non-blanching rash with confusion and neck stiffness is meningococcal sepsis, and it needs antibiotics within the hour.")],
 [("user","I've been having thoughts of ending it. I've worked out how I'd do it."),
  ("assistant","Thank you for telling me. Have you set a time, or taken any steps toward it?"),
  ("user","I bought what I'd need last week."),
  ("assistant","That means you're at high risk right now and I'm not going to let you leave here alone. I'm arranging an urgent psychiatric assessment today and I'd like your partner to come and take the means out of the house.")],
 [("user","My vision went dark in the right eye for about ten minutes and then came back."),
  ("assistant","Any weakness or trouble speaking with it?"),
  ("user","No, just the eye. It's fine now."),
  ("assistant","That's amaurosis fugax and it's a warning stroke. You need same-day assessment, carotid imaging and antiplatelet treatment; the stroke risk is highest in the next 48 hours.")],
 [("user","The wound on my foot smells and there's a black area around it. I'm diabetic."),
  ("assistant","Can you feel me pressing here?"),
  ("user","Not really, no."),
  ("assistant","This is a limb-threatening diabetic foot infection with necrosis and neuropathy. I'm admitting you today for IV antibiotics and vascular review; delay here is how people lose the foot.")],
 [("user","My daughter's temperature is 39 and she's four weeks old."),
  ("assistant","Is she feeding, and how many wet nappies today?"),
  ("user","She's not really feeding and only one nappy."),
  ("assistant","Bring her straight to the paediatric emergency department. Any fever in a baby under three months is a full septic screen and admission, and the poor feeding makes that more urgent, not less.")],
 [("user","I want to stop the dialysis. I've had enough."),
  ("assistant","That's your decision to make, and I want to make sure you're making it with everything in front of you. Can you tell me what's been hardest?"),
  ("user","The tiredness. Every other day, gone."),
  ("assistant","Let's get palliative care involved to see whether that's fixable, and I'll be honest with you about what stopping looks like: usually one to two weeks. Nothing gets decided today, and nothing gets forced on you either.")],
 [("user","My husband's had a headache since it hit suddenly about an hour ago. He says it's the worst of his life."),
  ("assistant","Did it come on over seconds?"),
  ("user","Instantly, he said, like being hit."),
  ("assistant","That's a thunderclap headache and it needs a CT now to exclude a subarachnoid haemorrhage. Call an ambulance rather than driving him in.")],
 [("user","The chemo nurse said to call if my temperature went up. It's 38.4 and I'm shivering."),
  ("assistant","When was your last cycle?"),
  ("user","Nine days ago."),
  ("assistant","Come straight to the acute oncology unit, don't wait. Day nine is the neutrophil nadir, and neutropenic sepsis needs antibiotics within an hour of arrival.")],
 [("user","I've been taking my sister's oxycodone for the back pain and now I can't get any."),
  ("assistant","How much have you been taking, and for how long?"),
  ("user","Six or seven a day, about four months."),
  ("assistant","That's a physical dependence and stopping abruptly will make you very unwell. Let's start you on a proper opioid dependence pathway today rather than you buying from anywhere else, which is where the fentanyl risk comes in.")],
 [("user","The pathology from the transplant biopsy is back."),
  ("assistant","It shows acute cellular rejection, grade 2R. We need to start pulse steroids today."),
  ("user","Does that mean I'm losing the heart?"),
  ("assistant","Not necessarily. Treated promptly, most grade 2R episodes resolve. But it does mean admission this afternoon and a repeat biopsy in two weeks.")],
 [("user","She's 82 and she fell again last night, and she's on apixaban. She hit her head on the radiator."),
  ("assistant","Has she been drowsy or vomited?"),
  ("user","She's been more muddled today."),
  ("assistant","She needs a CT head today. A head strike on an anticoagulant with new confusion is a subdural until proven otherwise, and it can declare itself slowly.")],
]

LOW = [
 [("user","I need a refill on my blood pressure tablets before I travel."),
  ("assistant","Your last reading was 128 over 78, which is fine. I'll send a three-month supply to your usual pharmacy."),
  ("user","Great, thank you."),
  ("assistant","No problem. Book a routine review for when you're back and we'll recheck then.")],
 [("user","I've had a cold for four days. Should I be taking anything?"),
  ("assistant","Any fever, or shortness of breath?"),
  ("user","No, just a blocked nose and a bit of a cough."),
  ("assistant","Then it's a viral upper respiratory infection and it'll settle on its own in a week or so. Fluids, paracetamol if you're achy, and a saline spray if the nose is the worst part.")],
 [("user","This mole on my shoulder, has it changed since last year's photo?"),
  ("assistant","Let me compare. Same size, same even border, same colour throughout."),
  ("user","So nothing to do?"),
  ("assistant","Nothing to do. Keep an eye on it and come back if the edge becomes irregular or it starts changing colour, but this one looks stable and benign.")],
 [("user","I twisted my ankle playing five-a-side on Sunday."),
  ("assistant","Can you walk four steps on it?"),
  ("user","Yes, it's just sore on the outside."),
  ("assistant","That's a low-grade lateral sprain, no X-ray needed. Ice, a compression sleeve, and start gentle movement early rather than resting it completely. Should be reasonable in a fortnight.")],
 [("user","My hay fever's been awful this week."),
  ("assistant","Are you taking anything for it?"),
  ("user","Just the cheap tablets from the supermarket."),
  ("assistant","Try a steroid nasal spray alongside them, started daily rather than as needed. That does most of the work for the blocked nose and the itchy eyes.")],
 [("user","Can I get a sick note for the two days I was off with the stomach bug?"),
  ("assistant","For under seven days you can self-certify, so you don't need one from me."),
  ("user","My work insists on it though."),
  ("assistant","I can write a brief confirmation letter. There may be a small admin fee since it isn't an NHS service, but I'll get it done today.")],
 [("user","The dry skin on my elbows comes back every winter."),
  ("assistant","What are you using on it?"),
  ("user","Just normal body lotion."),
  ("assistant","Switch to a proper ointment-based emollient and put it on straight after a shower while the skin's damp. Lotions are mostly water and evaporate off.")],
 [("user","I want to talk about coming off the antidepressant. I've been well for over a year now."),
  ("assistant","That's good to hear. How's your sleep and mood been recently?"),
  ("user","Steady. No real dips since spring."),
  ("assistant","Then a slow taper is reasonable. We'll halve the dose for four weeks, see how you find it, and there's no rush at any step.")],
 [("user","My daughter's got nits again from school."),
  ("assistant","Third time this term?"),
  ("user","Fourth, honestly."),
  ("assistant","Wet combing with conditioner every three days for two weeks is more reliable than the lotions at this point. Do the whole household on the same day or it just cycles.")],
 [("user","What's the actual difference between ibuprofen and paracetamol?"),
  ("assistant","Paracetamol works centrally on pain and fever; ibuprofen also reduces inflammation, which is why it suits sprains and dental pain better."),
  ("user","Can I take both?"),
  ("assistant","Yes, they can be alternated safely at normal doses, as long as your stomach tolerates the ibuprofen and you take it with food.")],
 [("user","I've been snoring more since I turned forty and my wife has opinions."),
  ("assistant","Do you ever wake up gasping, or feel sleepy driving?"),
  ("user","No, neither. Just noisy apparently."),
  ("assistant","Then it's simple snoring rather than sleep apnoea. Side sleeping, less alcohol in the evening and a few kilos off all help; nothing here needs a sleep study.")],
 [("user","Is it worth having the flu jab if I'm healthy?"),
  ("assistant","It reduces your odds of a miserable week and of passing it to anyone frailer around you."),
  ("user","Any reason not to?"),
  ("assistant","Only a genuine egg anaphylaxis, and even then there's an alternative. It's free for you this year, so worth booking at the desk on the way out.")],
 [("user","My knee clicks when I go up stairs but it doesn't hurt."),
  ("assistant","Any swelling, or does it ever give way?"),
  ("user","Neither. It's just noisy."),
  ("assistant","Painless clicking is very common and doesn't indicate damage. If you want it quieter, quad strengthening tends to help; otherwise it's nothing to treat.")],
 [("user","I've been trying to eat better. Is porridge actually good or is that marketing?"),
  ("assistant","It's genuinely fine: slow-release carbohydrate and soluble fibre, which is good for cholesterol."),
  ("user","Even the instant ones?"),
  ("assistant","Those often carry a lot of added sugar. Plain oats with whatever fruit you like gets you the same benefit for less money.")],
 [("user","Can I take my cholesterol tablet in the morning instead? I keep forgetting at night."),
  ("assistant","With atorvastatin, yes, it's long-acting enough that timing barely matters."),
  ("user","Good, that's much easier."),
  ("assistant","Then switch to mornings. Taking it consistently matters far more than which end of the day it happens.")],
 [("user","I get a headache most afternoons at work."),
  ("assistant","How much water and coffee across a day, and when was your last eye test?"),
  ("user","Not much water, four coffees. Eye test was maybe five years ago."),
  ("assistant","Start with an eye test and a water bottle on the desk, and pull the coffee back gradually rather than at once so you don't add a caffeine withdrawal headache. Come back in six weeks if nothing shifts.")],
 [("user","The practice sent a text about a medication review. What is that?"),
  ("assistant","It's a routine annual check that your repeat prescriptions still suit you, usually about fifteen minutes."),
  ("user","Do I need to do anything to prepare?"),
  ("assistant","Just bring your current boxes or a photo of them, and note anything you've stopped taking. Nothing to worry about.")],
 [("user","My verruca has been there for months. Is it worth freezing?"),
  ("assistant","Most clear on their own within a year or two, and freezing is uncomfortable for a modest speed-up."),
  ("user","So just leave it?"),
  ("assistant","Salicylic acid daily with a pumice stone is the best value approach. Cover it at the pool and it'll get there on its own.")],
]
