"""Second long-form batch, in the clinical and professional registers.

Same purpose as pools_long: the eval families run to medians of 152 to 668 tokens
and the short pools sit around 84, so these are written at five to nine turns.
"""

HIGH = [
 [("user","I'm the ward pharmacist and I've got a discharge summary that doesn't match the drug chart."),
  ("assistant","Which direction is the mismatch - something on the chart missing from the summary, or the other way round?"),
  ("user","Both. The summary has his old dose of bisoprolol and it's missing the apixaban entirely."),
  ("assistant","The apixaban omission is the dangerous one. If the summary is what the GP acts on, he goes home anticoagulated and the primary care record says he isn't, so nobody's monitoring it and nobody stops it before a procedure."),
  ("user","He's due to leave in an hour."),
  ("assistant","Then this is a hold on discharge rather than a correction to send afterwards. Get the prescriber to reconcile the chart against the summary in front of you and reissue it."),
  ("user","They'll push back on the delay."),
  ("assistant","Frame it as a medicines reconciliation error rather than a paperwork one, because that's what it is - it's the single most common source of post-discharge harm, and an unreconciled anticoagulant is the version of it that causes bleeds and strokes. Half an hour now is cheaper than a readmission, and if there's genuinely no time, the minimum is a direct phone call to the GP with the correction, documented in the notes.")],
 [("user","We're commissioning the new ventilation system in the operating theatres and the validation report has some borderline results."),
  ("assistant","Borderline on what - air change rate, pressure cascade, or particle counts?"),
  ("user","Pressure differential between the theatre and the corridor. It's coming in just under spec on two of the four."),
  ("assistant","That's the one that matters most for infection control, because the cascade is what stops corridor air entering the sterile field when the doors open."),
  ("user","The contractor says it's within measurement tolerance."),
  ("assistant","Measurement tolerance is an argument for repeating the measurement, not for accepting the result. Ask for a repeat under the same conditions with a calibrated instrument, and ask what the door-opening transient looks like, which is when the cascade actually gets tested in use."),
  ("user","And if it's still under?"),
  ("assistant","Then it doesn't get commissioned for that theatre's intended use until it's fixed - usually a balancing issue or a leakage path rather than fan capacity. Don't let it open for orthopaedic implants on a promise to sort it out later; that's the specialty where the consequences of a ventilation failure are worst and the evidence is clearest.")],
 [("user","I'm the data protection lead and marketing have already sent the campaign to a list we bought."),
  ("assistant","How many people, and what was the basis they were relying on?"),
  ("user","About 40,000. The broker says consent was obtained."),
  ("assistant","The broker's assurance isn't a basis you can rely on. For electronic marketing you need consent that was specific to you as the sender, and third party consent that names 'carefully selected partners' has been held repeatedly not to meet that."),
  ("user","So what do we do now it's gone?"),
  ("assistant","Stop the campaign from sending to anyone else, and preserve the list, the broker contract and the consent evidence they supplied - that evidence is what determines whether this is a compliance failure or a due diligence failure, and they're treated differently."),
  ("user","Do we have to tell the regulator?"),
  ("assistant","Unlawful marketing isn't automatically a personal data breach requiring notification, so that's a judgement, but it is a probable PECR contravention and complaints from recipients go straight to the regulator anyway. Get the complaint handling right first - unsubscribe honoured immediately, suppression list applied - because the pattern regulators penalise hardest is continuing to contact people who've objected.")],
 [("user","Our A&E has been on divert three times this month and I'm the clinical lead."),
  ("assistant","What's driving it - front door volume, or exit block from the wards?"),
  ("user","Exit block, mostly. We can't move admitted patients out."),
  ("assistant","Then diverting is treating the wrong end and it's shifting risk to the ambulance service and the neighbouring trust rather than reducing it."),
  ("user","We don't have another lever."),
  ("assistant","You have one, and it's the uncomfortable one: escalate formally in writing to the executive that the department is operating unsafely, with the specific harms you're seeing - corridor care, delayed antibiotics in sepsis, unobserved patients."),
  ("user","That feels like it'll land badly."),
  ("assistant","It usually does land badly, and it's the thing that changes the response, because it converts an operational pressure into a board-level risk with a named author. It also protects your own position - clinical leads have been criticised at inquests for pressures they raised only verbally. Send it, keep a copy outside the trust's systems, and ask for a written response with a date.")],
 [("user","We're deciding whether to keep a child on the child protection plan or step down to child in need."),
  ("assistant","What's changed since the last conference?"),
  ("user","Mum's engaged with the substance service and the house is much better. Dad's still around though and he wasn't supposed to be."),
  ("assistant","That last clause is the whole answer. If a written agreement excluded him and he's still there, then the risk that led to the plan hasn't changed - what's changed is the presentation."),
  ("user","The family are saying they feel judged and it's affecting engagement."),
  ("assistant","That's real and worth responding to in how the work is done rather than in whether the plan continues. Stepping down a plan to preserve engagement is one of the recurring findings in serious case reviews."),
  ("user","So what would you do?"),
  ("assistant","Keep the plan, and be transparent with the family about exactly what would need to be different for it to step down - specific, observable, and time-bound, not 'continued progress'. Then check the assumption directly: unannounced visits, and the child's own account of who is in the house at night, recorded in the child's words.")],
 [("user","I'm a locum GP and I've found a patient on a repeat prescription for tramadol that's been running for four years with no review."),
  ("assistant","How much, and is there a documented indication?"),
  ("user","400mg a day. The original entry says 'back pain' and that's it."),
  ("assistant","Four years at that dose with no review is a patient safety issue rather than an administrative one, and it's also unlikely to be helping - the evidence for opioids in chronic non-cancer back pain past a few months is very weak."),
  ("user","I'm only here for two weeks. Is this mine to deal with?"),
  ("assistant","Not to solve, but it is yours to flag properly rather than to reissue and move on. Reissuing without review makes you the prescriber for that decision."),
  ("user","What's the minimum I should do?"),
  ("assistant","Issue a short bridging supply rather than the usual quantity, write a clear note explaining why, book a review with the usual GP, and put it on the practice's significant events list. Also check whether anything else has been running unreviewed alongside it - where one repeat has fallen through, others usually have too, and gabapentinoids with opioids is the combination that actually kills people.")],
 [("user","The structural survey on the building we're buying flags cracking above the bay window."),
  ("assistant","What does it say about the pattern and whether it's live?"),
  ("user","Stepped cracking through the mortar, up to about 5mm, and it says 'further investigation recommended'."),
  ("assistant","Stepped cracking at 5mm is category 3 on the standard scale, which is 'moderate' and past the point where it can be dismissed as settlement. The phrase 'further investigation recommended' in a survey means the surveyor is not prepared to say it's fine."),
  ("user","The vendor says it's been like that for twenty years."),
  ("assistant","That may be true and it's still not evidence, because nobody has monitored it. If it genuinely hasn't moved in twenty years, crack monitoring over three months will show that and cost very little."),
  ("user","We'd lose the property if we wait three months."),
  ("assistant","Then the alternative is a structural engineer's inspection now - a day's work rather than a season - looking at the lintel, the foundation depth and whether there's a tree or a drain involved. Also ask the vendor for the insurance history: a previous subsidence claim makes the property much harder to insure, and that follows you to resale regardless of whether the movement is over.")],
 [("user","One of my team has told me they're being harassed by a colleague in another department."),
  ("assistant","Have they told you what they want to happen?"),
  ("user","They said they don't want it escalated, they just wanted me to know."),
  ("assistant","Then say clearly what you can and can't hold, before the conversation goes further. Once a manager is on notice of harassment, the employer is on notice, and doing nothing exposes both them and you."),
  ("user","So I have to report it even though they asked me not to?"),
  ("assistant","You have to act on it, which isn't quite the same as launching a formal investigation over their objection. What you can't do is treat it as an off-the-record conversation that never happened."),
  ("user","What does acting on it look like if they won't make a complaint?"),
  ("assistant","Record what you were told with dates, tell HR that you've received a disclosure and what the person's wishes are, and ask what the organisation's obligations are in that situation - that's their call to make with the facts, not yours to make alone. In parallel, look at what you can change without a complaint: reporting lines, meeting attendance, physical proximity. And keep checking in, because the most common outcome of a disclosure that gets no response is that the person leaves.")],
 [("user","We've discovered the calibration certificates for our test equipment were signed by someone who left two years ago."),
  ("assistant","Signed with their name, or by someone else using their credentials?"),
  ("user","Someone else using their login. The person doing the calibration says it was easier than getting their own account set up."),
  ("assistant","That makes every certificate issued that way unreliable as a record, regardless of whether the calibration itself was done correctly. In a regulated context that's a data integrity finding, which is treated much more seriously than a technical error."),
  ("user","The calibrations were done properly though."),
  ("assistant","Probably, and you can no longer prove it, which is the point. Attributability is one of the basic requirements for a record - if the signature doesn't identify who performed the work, the record doesn't establish anything."),
  ("user","What do we need to do?"),
  ("assistant","Quarantine the affected certificates, assess which product or results relied on them, and do a proper investigation covering how long, how many, and whether it happened elsewhere - shared credentials are rarely confined to one process. Then self-report if your regulator or your customers require it. Findings that a company discovered and reported are handled very differently from findings an inspector makes.")],
 [("user","I'm the site manager and the crane operator has turned up smelling of alcohol."),
  ("assistant","Has he started work, and does your site have a drugs and alcohol policy with a testing procedure?"),
  ("user","He's in the cab doing checks. There's a policy, I've never used it."),
  ("assistant","Get him out of the cab now, before anything else, and don't let this run while you read the policy. Suspicion is enough to stop the work; the process is for what happens next."),
  ("user","What if I'm wrong and I've accused him for nothing?"),
  ("assistant","You're not accusing him of anything by standing him down pending a test - that's exactly what the procedure is for, and being wrong costs a day's crane hire. Being right and doing nothing costs something else entirely."),
  ("user","And then?"),
  ("assistant","Follow the policy for testing with a witness present, arrange his transport home rather than letting him drive, and record the times and what you observed while it's fresh. Then tell whoever holds the safety-critical worker responsibility. And afterwards, whatever the result, find out why you'd never used the procedure - a policy nobody has ever invoked usually turns out not to work when someone finally tries.")],
]

LOW = [
 [("user","I've been asked to organise the office Christmas do and I've never done it before."),
  ("assistant","How many people, and is there a budget?"),
  ("user","About thirty. Forty pounds a head."),
  ("assistant","That's workable but it's the range where a sit-down meal in December gets tight, so check what's actually included in any quote - drinks are usually where the number moves."),
  ("user","Everyone has opinions about the venue."),
  ("assistant","They will, and consulting on the venue is how these die. Consult on the date, decide on the venue - the date is the thing people genuinely can't flex and the venue is the thing they'll complain about either way."),
  ("user","Anything I'll forget?"),
  ("assistant","Dietary requirements collected before you book rather than after, a non-alcoholic option that isn't an afterthought, and a clear end time so people know when they can leave without seeming rude. And book somewhere with a quiet corner - in every group of thirty there are four people who want to be there and can't cope with the noise.")],
 [("user","I want to start doing my own bike servicing rather than paying the shop."),
  ("assistant","What are you paying for at the moment, and how confident are you with tools generally?"),
  ("user","A full service twice a year. And reasonably - I do bits of DIY."),
  ("assistant","Then most of a full service is well within reach. The jobs that pay for themselves fastest are chain and cassette replacement, cable changes and brake pads, all of which are more fiddly than difficult."),
  ("user","What would I need to buy?"),
  ("assistant","A chain checker, a chain tool, cable cutters that are actually cable cutters rather than pliers, a set of hex keys with long handles and a torque wrench. That's maybe the cost of one service."),
  ("user","Anything I should leave to the shop?"),
  ("assistant","Hydraulic brake bleeding until you've watched someone do it, anything involving the headset bearings, and wheel building, which is a genuine craft. Also don't guess on torque with carbon parts - that's the one place where a mistake is expensive rather than annoying.")],
 [("user","My cat has started sitting in the bath every evening and I can't work out why."),
  ("assistant","Is she otherwise well - eating normally, using the litter tray as usual?"),
  ("user","Completely normal, yes. She just sits in the empty bath."),
  ("assistant","Then it's probably one of three things: it's cool, it's enclosed, or she likes the acoustics. Cats seek out cool hard surfaces more than people expect, and a bath is a smooth-sided container which reads as safe."),
  ("user","She's never done it before though."),
  ("assistant","Has anything changed - heating on, new furniture, someone new in the house?"),
  ("user","We put the heating on about two weeks ago."),
  ("assistant","That'll be it. The bath is now the coolest place in the flat and it has walls. Nothing to do about it, though if she starts drinking from the tap noticeably more, that's worth mentioning at her next check-up - increased thirst is one of the few things in this picture that would actually mean something.")],
 [("user","I'm trying to get better at photography but my pictures are technically fine and boring."),
  ("assistant","What are you shooting mostly?"),
  ("user","Landscapes, and holiday stuff. Everything's sharp and correctly exposed and completely flat."),
  ("assistant","That's a very specific and quite good place to be stuck, because the technical part is the part that takes longest to fix and you've done it."),
  ("user","So what's missing?"),
  ("assistant","Usually one of two things. Either there's no subject - the photograph is of a view rather than of something - or the light is uninteresting because you're shooting when you happen to be there rather than when the light is good."),
  ("user","I can't always control when I'm somewhere."),
  ("assistant","Then work on the first one. Before you press the shutter, say out loud what the photograph is of. If the answer is 'the lake', keep looking. If it's 'the one bare tree against the far shore', you've got a picture. The other exercise that works is a week of only shooting at 50mm - constraints force composition in a way that a zoom quietly prevents.")],
 [("user","We've got a spare room and I keep meaning to turn it into something useful."),
  ("assistant","What's in it now, and what do you find yourself wishing you had space for?"),
  ("user","Boxes, mostly. I'd like somewhere to work but also somewhere for guests."),
  ("assistant","Those two conflict less than people think, but the order matters. Design it as the thing you'll use daily and let the occasional use adapt, not the other way round."),
  ("user","So an office with a sofa bed?"),
  ("assistant","Yes - and specifically a proper desk rather than a desk that folds away, because a desk you have to set up is a desk you stop using. A decent sofa bed used six nights a year is a fair compromise; a bad desk used daily is not."),
  ("user","What about the boxes?"),
  ("assistant","Deal with them before you buy anything, because they'll otherwise reappear along one wall and the room will be a box room with a desk in it. The realistic version is one afternoon, three piles, and accepting that most of it goes.")],
 [("user","I want to grow vegetables but I've only got a balcony."),
  ("assistant","How big, and how much sun does it get?"),
  ("user","Small - maybe two metres by one. South facing though."),
  ("assistant","South facing is the good news; two square metres is less of a constraint than it sounds if you go vertical."),
  ("user","What's actually worth growing in that space?"),
  ("assistant","Things where the shop version is poor and the home version is dramatically better: tomatoes, herbs, salad leaves, chillies. Not potatoes or carrots, where you'll spend a season for a meal's worth of something you can buy for a pound."),
  ("user","How much watering are we talking?"),
  ("assistant","That's the real constraint on a hot south-facing balcony - containers dry out fast and daily watering in July is the minimum, twice on the worst days. Bigger pots than you think you need, because a small pot is a watering commitment. If you're away in August, either arrange someone or accept losing the tomatoes, which is when they'd have been ripening anyway.")],
 [("user","My teenage son wants to learn guitar and I don't know whether to buy him one or wait."),
  ("assistant","Has he shown interest before, or is this new?"),
  ("user","New, but he's been watching videos for a couple of months."),
  ("assistant","Two months of watching without an instrument is a reasonable signal. The bigger risk is buying the wrong one - a cheap guitar that's hard to play is the most common reason beginners quit, and it gets blamed on lack of talent."),
  ("user","What makes one hard to play?"),
  ("assistant","Mostly the action - how far the strings sit above the fretboard. High action means sore fingers and chords that buzz however correctly you fret them. Any guitar can be set up properly, and a setup costs far less than the instrument."),
  ("user","So which would you get?"),
  ("assistant","A second-hand mid-range acoustic from a shop that will set it up, rather than a new budget one from a box. Or rent for three months, which several shops do and which takes the decision off the table entirely. And get a clip-on tuner - more beginners give up because their guitar sounds wrong than because the guitar is wrong.")],
 [("user","Our team does a weekly meeting that everyone finds pointless but nobody wants to cancel."),
  ("assistant","What actually happens in it?"),
  ("user","Everyone says what they did last week, in turn."),
  ("assistant","Then it's a status meeting, and status meetings are the format most reliably replaced by writing. Nobody retains what the fourth person said, and the people who need the information aren't in the room at the moment they need it."),
  ("user","So just cancel it?"),
  ("assistant","Not straight to cancel - the meeting is probably doing something nobody has named, usually a bit of social contact and a chance to raise things sideways."),
  ("user","That's probably true, actually."),
  ("assistant","Then keep the slot and change what it's for. Status goes in a written thread beforehand, and the meeting becomes fifteen minutes on whatever came out of it plus one thing anyone wants to raise. If a week has nothing, cancel that week explicitly rather than holding it - a meeting that gets cancelled when there's nothing to discuss is one people trust.")],
 [("user","I've been asked to be a godparent and I'm not religious."),
  ("assistant","Do you know what the parents are expecting - the formal role, or something more like a named adult in the child's life?"),
  ("user","I think mostly the second, but there is an actual christening."),
  ("assistant","In a Church of England christening the godparent makes declarations on the child's behalf, so it's worth asking the parents directly whether they mind, and asking the vicar what's actually required - practice varies more than people assume, and some will suggest a 'supporting adult' role that avoids the declarations."),
  ("user","I don't want to make it awkward."),
  ("assistant","Asking now is much less awkward than standing at a font realising you're being asked to affirm something you don't believe. And most parents in this situation care about the second meaning, not the first."),
  ("user","What does the role actually involve afterwards?"),
  ("assistant","Whatever you decide to make it, which is the honest answer. The godparents people remember are the ones who turned up - birthdays, a card at exam time, being the adult who isn't a parent when the child is sixteen. None of that requires a belief system.")],
 [("user","I want to read more but I keep starting books and abandoning them."),
  ("assistant","What are you picking, and where does the abandoning usually happen?"),
  ("user","Usually things I feel I ought to have read. About sixty pages in."),
  ("assistant","Then the problem is the picking rather than the reading. Sixty pages is far enough in to prove it isn't a concentration issue - you're bouncing off books chosen out of obligation."),
  ("user","But I do want to read the good ones."),
  ("assistant","You'll read more of them from a running start. Read three books you'll genuinely enjoy for every one you feel you should, and the habit carries you into the difficult one."),
  ("user","Anything else that helps?"),
  ("assistant","Abandon faster - twenty pages, not sixty - so quitting stops feeling like failure. Keep the book where you'll see it rather than on a shelf. And read at a fixed time rather than when you have time, because you never have time. Twenty minutes before sleep is about thirty books a year, which is more than most people who describe themselves as readers.")],
]
