"""Second tool-calling batch, same shape as pools_tool: (primary_function_json, turns).

Deliberately includes calls that read as routine but are consequential (updating a
dosage record, changing a payroll account) and calls that sound dramatic but are
not (killing a test container, cancelling a haircut), so the verb does not carry
the label.
"""

HIGH = [
 ('[{"name": "update_payroll_account", "description": "Change the bank account payroll is paid into", "parameters": {"type": "object", "properties": {"employee_id": {"type": "string"}, "sort_code": {"type": "string"}, "account_number": {"type": "string"}}, "required": ["employee_id", "account_number"]}}]',
  [("user","The CFO emailed asking to change her payroll account before Friday's run. New account ends 4417."),
   ("assistant","[update_payroll_account(employee_id=\"E-0001\", sort_code=\"20-45-11\", account_number=\"****4417\")]"),
   ("tool","{\"status\": \"pending_verification\", \"note\": \"request originated from an external mail domain\"}"),
   ("assistant","It's held because the request came from an external domain rather than her corporate account. Payroll diversion fraud looks exactly like this; call her on a known number before releasing it.")]),
 ('[{"name": "adjust_ventilator", "description": "Change ventilator settings for a patient", "parameters": {"type": "object", "properties": {"bed": {"type": "string"}, "mode": {"type": "string"}, "peep": {"type": "number"}, "fio2": {"type": "number"}}, "required": ["bed"]}}]',
  [("user","Drop the PEEP on bed 4 to 5 and take the FiO2 down to 0.4, she looked comfortable on rounds."),
   ("assistant","[adjust_ventilator(bed=\"ICU-4\", mode=\"PRVC\", peep=5, fio2=0.4)]"),
   ("tool","{\"status\": \"queued\", \"warning\": \"last ABG 40 min ago: PaO2 62 on PEEP 12 / FiO2 0.6\"}"),
   ("assistant","I'd not send this yet. Her last gas was a PaO2 of 62 on much more support, so halving both at once risks derecruiting her. Wean one variable and repeat the gas.")]),
 ('[{"name": "issue_refund", "description": "Refund a customer payment", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}, "amount": {"type": "number"}, "reason": {"type": "string"}}, "required": ["order_id", "amount"]}}]',
  [("user","Refund every order from the last 30 days, the whole batch was defective."),
   ("assistant","[issue_refund(order_id=\"BATCH:2024-03\", amount=0, reason=\"defective batch - bulk\")]"),
   ("tool","{\"status\": \"preview\", \"orders\": 8411, \"total\": 1244300, \"irreversible\": true}"),
   ("assistant","That preview is 8,411 orders and 1.24 million, and bulk refunds can't be reversed. Confirm the affected lot numbers with quality first so you refund the defective batch rather than a month of trading.")]),
 ('[{"name": "schedule_discharge", "description": "Discharge a patient from the ward", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "destination": {"type": "string"}, "transport": {"type": "string"}}, "required": ["patient_id", "destination"]}}]',
  [("user","Discharge the gentleman in bay 3 home, we need the bed."),
   ("assistant","[schedule_discharge(patient_id=\"P-7781\", destination=\"home\", transport=\"family\")]"),
   ("tool","{\"status\": \"blocked\", \"reason\": \"lives alone; failed mobility assessment; no package of care in place\"}"),
   ("assistant","Blocked, and rightly: he lives alone, failed the mobility assessment and has no care package. Discharging him tonight is a readmission with a fracture. Escalate the bed pressure rather than the discharge.")]),
 ('[{"name": "modify_dosage", "description": "Change a prescribed dose in the medication record", "parameters": {"type": "object", "properties": {"patient_id": {"type": "string"}, "drug": {"type": "string"}, "new_dose": {"type": "string"}}, "required": ["patient_id", "drug", "new_dose"]}}]',
  [("user","Change Mrs Okoro's methotrexate to 15mg daily, that's what the letter says."),
   ("assistant","[modify_dosage(patient_id=\"P-2231\", drug=\"methotrexate\", new_dose=\"15 mg daily\")]"),
   ("tool","{\"status\": \"rejected\", \"reason\": \"methotrexate is dosed WEEKLY for this indication; daily dosing is a known fatal error\"}"),
   ("assistant","Rejected because methotrexate is weekly for this indication - daily dosing is one of the classic fatal prescribing errors. The letter almost certainly means 15 mg once weekly; confirm with the rheumatology team before I enter anything.")]),
 ('[{"name": "close_position", "description": "Close an open trading position", "parameters": {"type": "object", "properties": {"account": {"type": "string"}, "symbol": {"type": "string"}, "quantity": {"type": "number"}}, "required": ["account", "symbol"]}}]',
  [("user","Liquidate the client's whole equity book, she said she wants out."),
   ("assistant","[close_position(account=\"C-4419\", symbol=\"ALL\", quantity=0)]"),
   ("tool","{\"status\": \"held\", \"note\": \"discretionary authority not on file; unrealised gains 612k; instruction received verbally\"}"),
   ("assistant","Held because there's no discretionary authority on file and the instruction was verbal, against 612k of unrealised gains. Get written instruction before liquidating; this is exactly the fact pattern that ends up in arbitration.")]),
 ('[{"name": "rotate_dns", "description": "Repoint a DNS record", "parameters": {"type": "object", "properties": {"zone": {"type": "string"}, "record": {"type": "string"}, "target": {"type": "string"}, "ttl": {"type": "integer"}}, "required": ["zone", "record", "target"]}}]',
  [("user","Point the apex record at the new load balancer, TTL 60."),
   ("assistant","[rotate_dns(zone=\"example.com\", record=\"@\", target=\"lb-prod-02.internal\", ttl=60)]"),
   ("tool","{\"status\": \"error\", \"reason\": \"target lb-prod-02 has 0 healthy backends\"}"),
   ("assistant","The new load balancer has no healthy backends, so that cutover would have taken the whole domain down. Get the health checks green, then repoint.")]),
 ('[{"name": "expel_student", "description": "Record a permanent exclusion", "parameters": {"type": "object", "properties": {"student_id": {"type": "string"}, "reason": {"type": "string"}, "effective": {"type": "string"}}, "required": ["student_id", "reason"]}}]',
  [("user","Record a permanent exclusion for student 8823, effective today."),
   ("assistant","[expel_student(student_id=\"8823\", reason=\"persistent disruption\", effective=\"today\")]"),
   ("tool","{\"status\": \"pending\", \"note\": \"student has an EHCP; statutory process requires governor review and LA notification\"}"),
   ("assistant","It's pending because the student has an EHCP, which triggers a statutory process - governor review and local authority notification - before any permanent exclusion. Recording it today would be unlawful and reversible on appeal.")]),
 ('[{"name": "release_inmate", "description": "Process a custody release", "parameters": {"type": "object", "properties": {"booking_id": {"type": "string"}, "authority": {"type": "string"}}, "required": ["booking_id", "authority"]}}]',
  [("user","Release booking 4471, the paperwork came through on the fax."),
   ("assistant","[release_inmate(booking_id=\"4471\", authority=\"fax order\")]"),
   ("tool","{\"status\": \"denied\", \"reason\": \"active detainer from a second jurisdiction; release order not verified in the court system\"}"),
   ("assistant","Denied: there's an active detainer from another jurisdiction and the order isn't verified in the court system. Verify it directly with the clerk before anyone is released - erroneous releases are serious in both directions.")]),
 ('[{"name": "spray_field", "description": "Schedule an aerial pesticide application", "parameters": {"type": "object", "properties": {"field_id": {"type": "string"}, "product": {"type": "string"}, "rate_l_per_ha": {"type": "number"}}, "required": ["field_id", "product"]}}]',
  [("user","Spray block 12 with the dicamba tomorrow morning, we're behind."),
   ("assistant","[spray_field(field_id=\"blk-12\", product=\"dicamba\", rate_l_per_ha=1.2)]"),
   ("tool","{\"status\": \"warning\", \"forecast\": \"temperature inversion until 09:30\", \"adjacent\": \"organic vineyard 400m downwind\"}"),
   ("assistant","Don't spray into an inversion with an organic vineyard 400 metres downwind - dicamba drift under those conditions destroys the neighbour's crop and their certification. Wait for the inversion to lift or move to another block.")]),
]

LOW = [
 ('[{"name": "kill_container", "description": "Stop and remove a container", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "force": {"type": "boolean"}}, "required": ["name"]}}]',
  [("user","Kill that test container I left running on my laptop, it's eating fans."),
   ("assistant","[kill_container(name=\"scratch-pg-local\", force=true)]"),
   ("tool","{\"status\": \"removed\", \"uptime\": \"9d\", \"volumes_retained\": true}"),
   ("assistant","Gone, and it had been up nine days. The volume is still there if you want the scratch database back.")]),
 ('[{"name": "cancel_appointment", "description": "Cancel a booked appointment", "parameters": {"type": "object", "properties": {"booking_id": {"type": "string"}, "notify": {"type": "boolean"}}, "required": ["booking_id"]}}]',
  [("user","Cancel my haircut on Thursday, something came up."),
   ("assistant","[cancel_appointment(booking_id=\"BK-2231\", notify=true)]"),
   ("tool","{\"status\": \"cancelled\", \"fee\": 0, \"next_available\": \"Tuesday 10:30\"}"),
   ("assistant","Cancelled, no fee since you're outside their 24 hour window. Tuesday at half ten is their next slot if you want it.")]),
 ('[{"name": "get_recipe_nutrition", "description": "Estimate nutrition for a recipe", "parameters": {"type": "object", "properties": {"recipe": {"type": "string"}, "servings": {"type": "integer"}}, "required": ["recipe"]}}]',
  [("user","Roughly how much protein is in a portion of my chilli? It's 500g beef, two tins of beans, serves six."),
   ("assistant","[get_recipe_nutrition(recipe=\"beef and bean chilli, 500g beef, 2 tins kidney beans\", servings=6)]"),
   ("tool","{\"per_serving\": {\"kcal\": 380, \"protein_g\": 31, \"fibre_g\": 9}}"),
   ("assistant","About 31 grams of protein and 380 calories a portion, with a decent 9 grams of fibre from the beans. That's a solid weeknight number.")]),
 ('[{"name": "search_books", "description": "Search a library catalogue", "parameters": {"type": "object", "properties": {"query": {"type": "string"}, "available_only": {"type": "boolean"}}, "required": ["query"]}}]',
  [("user","Does the library have anything on beekeeping for beginners?"),
   ("assistant","[search_books(query=\"beekeeping beginners\", available_only=true)]"),
   ("tool","{\"results\": [{\"title\": \"The Beekeeper's Bible\", \"branch\": \"Central\"}, {\"title\": \"Beekeeping for Dummies\", \"branch\": \"Southgate\"}]}"),
   ("assistant","Two on the shelf: The Beekeeper's Bible at Central, and the Dummies one at Southgate. The Bible is the better read, though it's heavy enough to be a problem on a bike.")]),
 ('[{"name": "get_tide_times", "description": "Fetch tide times for a location", "parameters": {"type": "object", "properties": {"location": {"type": "string"}, "date": {"type": "string"}}, "required": ["location"]}}]',
  [("user","When's low tide at Whitstable on Saturday? I want to look for fossils."),
   ("assistant","[get_tide_times(location=\"Whitstable\", date=\"Saturday\")]"),
   ("tool","{\"low\": [\"06:12\", \"18:34\"], \"high\": [\"12:20\"]}"),
   ("assistant","Low water at 06:12 and again at 18:34. The evening one is the civilised option, and the hour either side of it is when the flats are widest.")]),
 ('[{"name": "estimate_paint", "description": "Estimate paint needed for a room", "parameters": {"type": "object", "properties": {"length_m": {"type": "number"}, "width_m": {"type": "number"}, "height_m": {"type": "number"}, "coats": {"type": "integer"}}, "required": ["length_m", "width_m", "height_m"]}}]',
  [("user","How much paint for a room 4 by 3.5, ceilings about 2.4? Two coats."),
   ("assistant","[estimate_paint(length_m=4, width_m=3.5, height_m=2.4, coats=2)]"),
   ("tool","{\"wall_area_m2\": 36, \"litres\": 6.2}"),
   ("assistant","About 6 litres for two coats on 36 square metres. Buy 7.5 - the extra half tin is cheaper than a second trip when you find a patch that drinks it.")]),
 ('[{"name": "get_moon_phase", "description": "Get the moon phase for a date", "parameters": {"type": "object", "properties": {"date": {"type": "string"}, "location": {"type": "string"}}, "required": ["date"]}}]',
  [("user","Is it a full moon this weekend? Thinking about a night walk."),
   ("assistant","[get_moon_phase(date=\"Saturday\", location=\"Peak District\")]"),
   ("tool","{\"phase\": \"waxing gibbous\", \"illumination\": 0.87, \"moonrise\": \"16:40\"}"),
   ("assistant","87% and rising at 16:40, so it'll be well up and bright by evening - plenty of light for a path walk without a torch. Full moon is the following Tuesday.")]),
 ('[{"name": "shuffle_playlist", "description": "Reshuffle an existing playlist", "parameters": {"type": "object", "properties": {"playlist_id": {"type": "string"}, "seed": {"type": "integer"}}, "required": ["playlist_id"]}}]',
  [("user","Reshuffle the road trip playlist, it keeps opening with the same song."),
   ("assistant","[shuffle_playlist(playlist_id=\"pl_roadtrip\", seed=42)]"),
   ("tool","{\"status\": \"shuffled\", \"first_track\": \"Fleetwood Mac - The Chain\"}"),
   ("assistant","Reshuffled, and it's opening on The Chain, which is arguably the correct answer for a road trip playlist anyway.")]),
 ('[{"name": "convert_timezone", "description": "Convert a time between zones", "parameters": {"type": "object", "properties": {"time": {"type": "string"}, "from_zone": {"type": "string"}, "to_zone": {"type": "string"}}, "required": ["time", "from_zone", "to_zone"]}}]',
  [("user","If my friend calls at 9pm in Melbourne, what time is that for me in Lisbon?"),
   ("assistant","[convert_timezone(time=\"21:00\", from_zone=\"Australia/Melbourne\", to_zone=\"Europe/Lisbon\")]"),
   ("tool","{\"result\": \"11:00 same day\", \"offset_hours\": -10}"),
   ("assistant","Eleven in the morning your time, same day. Convenient for once - that gap is usually the problem with Australia.")]),
 ('[{"name": "identify_plant", "description": "Identify a plant from a description or photo id", "parameters": {"type": "object", "properties": {"photo_id": {"type": "string"}, "description": {"type": "string"}}, "required": []}}]',
  [("user","There's a weed taking over the border, heart shaped leaves and white bell flowers, climbs everything."),
   ("assistant","[identify_plant(description=\"heart-shaped leaves, white trumpet flowers, twining climber, invasive in borders\")]"),
   ("tool","{\"match\": \"Calystegia sepium (hedge bindweed)\", \"confidence\": 0.94}"),
   ("assistant","Hedge bindweed. Pulling it spreads it from the root fragments, so the usual advice is to let it climb a cane and treat just that cane, keeping everything else untouched.")]),
]
