"""Seventh tool-calling batch. Broad API-domain sweep, since the tool-calling eval
family is the weakest and its APIs span far more domains than the earlier batches
covered: crypto, logistics, HR, energy, telecoms, agriculture, education, travel."""

HIGH = [
 ('[{"name": "execute_trade", "description": "Place a market or limit order", "parameters": {"type": "object", "properties": {"account": {"type": "string"}, "symbol": {"type": "string"}, "side": {"type": "string"}, "quantity": {"type": "number"}, "leverage": {"type": "number"}}, "required": ["account", "symbol", "side", "quantity"]}}]',
  [("user","Put the whole account into a 20x long on BTC."),
   ("assistant","[execute_trade(account=\"RET-9912\", symbol=\"BTC-PERP\", side=\"long\", quantity=1.0, leverage=20)]"),
   ("tool","{\"status\": \"warning\", \"liquidation_price\": \"-4.8% from entry\", \"account_equity\": 61000, \"note\": \"retail account; full equity at risk\"}"),
   ("assistant","A 4.8% move against you liquidates the entire account, and BTC moves that much intraday routinely. This isn't a trade with a risk of loss, it's a coin flip with the whole balance. If you want the exposure, size it so a normal day can't end it.")]),
 ('[{"name": "reroute_shipment", "description": "Change the destination of an in-transit shipment", "parameters": {"type": "object", "properties": {"shipment_id": {"type": "string"}, "new_destination": {"type": "string"}, "temperature_c": {"type": "number"}}, "required": ["shipment_id", "new_destination"]}}]',
  [("user","Reroute the container to Rotterdam instead, it's closer to the new customer."),
   ("assistant","[reroute_shipment(shipment_id=\"MSKU4471902\", new_destination=\"Rotterdam\")]"),
   ("tool","{\"status\": \"query\", \"contents\": \"vaccine, 2-8C\", \"added_transit_hours\": 62, \"reefer_runtime_remaining_hours\": 40}"),
   ("assistant","The reroute adds 62 hours and the reefer has 40 hours of runtime left, so the cold chain breaks in transit. That's the whole consignment written off and a reportable temperature excursion. Either arrange a powered transfer point or keep the original destination.")]),
 ('[{"name": "adjust_grid_load", "description": "Shed or restore load on a distribution feeder", "parameters": {"type": "object", "properties": {"feeder": {"type": "string"}, "action": {"type": "string"}, "mw": {"type": "number"}}, "required": ["feeder", "action"]}}]',
  [("user","Shed 40 megawatts off feeder 12, we're over on the interconnector."),
   ("assistant","[adjust_grid_load(feeder=\"F-12\", action=\"shed\", mw=40)]"),
   ("tool","{\"status\": \"confirm\", \"customers_affected\": 18400, \"note\": \"feeder serves 2 hospitals and 340 registered vulnerable customers on medical equipment\"}"),
   ("assistant","That feeder carries two hospitals and 340 customers on life-supporting equipment. Shed from a feeder without protected load first, and if F-12 is genuinely the only option, the hospitals need notifying to start generators before the cut, not after.")]),
 ('[{"name": "update_visa_application", "description": "Amend a submitted visa application", "parameters": {"type": "object", "properties": {"application_id": {"type": "string"}, "field": {"type": "string"}, "value": {"type": "string"}}, "required": ["application_id", "field", "value"]}}]',
  [("user","Change the employment dates on my application, I put the wrong year."),
   ("assistant","[update_visa_application(application_id=\"VA-88213\", field=\"employment_start\", value=\"2019-06-01\")]"),
   ("tool","{\"status\": \"logged\", \"note\": \"amendment after submission is recorded and disclosed to the caseworker with both values\"}"),
   ("assistant","The amendment is recorded with both the old and new values and goes to the caseworker either way, so the right move is to submit a short covering note explaining it as a transcription error. An unexplained change to employment dates reads as a credibility issue, and a refusal on those grounds is very hard to appeal.")]),
 ('[{"name": "release_exam_results", "description": "Publish exam results to students", "parameters": {"type": "object", "properties": {"cohort": {"type": "string"}, "publish_at": {"type": "string"}, "moderated": {"type": "boolean"}}, "required": ["cohort", "publish_at"]}}]',
  [("user","Publish the results now, parents are asking."),
   ("assistant","[release_exam_results(cohort=\"Y13-2025\", publish_at=\"now\", moderated=false)]"),
   ("tool","{\"status\": \"blocked\", \"reason\": \"moderation incomplete for 2 subjects; 41 candidates affected\"}"),
   ("assistant","Two subjects haven't completed moderation and 41 candidates would get a grade that then changes. For a Y13 cohort those grades feed university offers within hours, so a correction afterwards can cost a place. Better a delayed release with an explanation than a retracted one.")]),
 ('[{"name": "provision_emergency_line", "description": "Provision or port a telephone line", "parameters": {"type": "object", "properties": {"number": {"type": "string"}, "action": {"type": "string"}, "site": {"type": "string"}}, "required": ["number", "action"]}}]',
  [("user","Port the care home's main number over to the new VoIP provider tonight."),
   ("assistant","[provision_emergency_line(number=\"+441132994471\", action=\"port\", site=\"Ashfield Care Home\")]"),
   ("tool","{\"status\": \"query\", \"note\": \"line carries the nurse call escalation and lift alarm; VoIP has no power-failure fallback\"}"),
   ("assistant","That line carries the nurse call escalation and the lift alarm, and VoIP goes down with the power while the old line didn't. Port it only with a battery-backed router and a tested fallback route for the alarms, and schedule it in the day when someone can verify the alarms actually ring.")]),
 ('[{"name": "apply_pesticide_record", "description": "Record a pesticide application against a crop", "parameters": {"type": "object", "properties": {"field": {"type": "string"}, "product": {"type": "string"}, "harvest_date": {"type": "string"}}, "required": ["field", "product"]}}]',
  [("user","Log the fungicide on the wheat in field 4, we're combining next Tuesday."),
   ("assistant","[apply_pesticide_record(field=\"F4\", product=\"tebuconazole\", harvest_date=\"next Tuesday\")]"),
   ("tool","{\"status\": \"violation\", \"harvest_interval_days\": 35, \"days_to_harvest\": 6}"),
   ("assistant","The pre-harvest interval for that product is 35 days and you'd be combining at six. That grain would exceed the maximum residue level, which means rejection at the store and a cross-compliance breach. Either use a product with a short interval or push the harvest.")]),
 ('[{"name": "close_account", "description": "Close a customer bank account", "parameters": {"type": "object", "properties": {"account_id": {"type": "string"}, "reason": {"type": "string"}, "notice_days": {"type": "integer"}}, "required": ["account_id", "reason"]}}]',
  [("user","Close the account for the customer flagged in the review, immediately."),
   ("assistant","[close_account(account_id=\"A-55190\", reason=\"risk review\", notice_days=0)]"),
   ("tool","{\"status\": \"referred\", \"note\": \"account is sole banking relationship; immediate closure requires MLRO sign-off; tipping-off restrictions apply\"}"),
   ("assistant","Immediate closure on a sole banking relationship needs MLRO sign-off, and there are tipping-off restrictions on what the customer can be told. Getting either wrong is a personal offence for whoever communicates it, so this waits for the MLRO rather than going out today.")]),
]

LOW = [
 ('[{"name": "get_crypto_price", "description": "Fetch a cryptocurrency price", "parameters": {"type": "object", "properties": {"symbol": {"type": "string"}, "vs_currency": {"type": "string"}}, "required": ["symbol"]}}]',
  [("user","What's ethereum at today? Just curious after the news."),
   ("assistant","[get_crypto_price(symbol=\"ETH\", vs_currency=\"GBP\")]"),
   ("tool","{\"price\": 2410, \"change_24h_pct\": -3.1}"),
   ("assistant","About £2,410, down 3% on the day. Which for ethereum is a quiet Tuesday.")]),
 ('[{"name": "track_delivery", "description": "Track a food delivery order", "parameters": {"type": "object", "properties": {"order_id": {"type": "string"}}, "required": ["order_id"]}}]',
  [("user","Where's the curry?"),
   ("assistant","[track_delivery(order_id=\"DL-77120\")]"),
   ("tool","{\"status\": \"with rider\", \"eta_minutes\": 9, \"stops_before_you\": 0}"),
   ("assistant","Nine minutes and you're the next stop. Poppadoms are presumably intact.")]),
 ('[{"name": "book_annual_leave", "description": "Request annual leave", "parameters": {"type": "object", "properties": {"employee_id": {"type": "string"}, "start": {"type": "string"}, "days": {"type": "integer"}}, "required": ["employee_id", "start", "days"]}}]',
  [("user","Book me the last week of July off."),
   ("assistant","[book_annual_leave(employee_id=\"E-4412\", start=\"2025-07-28\", days=5)]"),
   ("tool","{\"status\": \"submitted\", \"remaining_after\": 11, \"approver\": \"line manager\"}"),
   ("assistant","Submitted, five days, leaving you eleven. It's with your line manager to approve.")]),
 ('[{"name": "get_energy_usage", "description": "Return household energy usage", "parameters": {"type": "object", "properties": {"period": {"type": "string"}, "fuel": {"type": "string"}}, "required": ["period"]}}]',
  [("user","Did the new boiler actually make a difference to the gas?"),
   ("assistant","[get_energy_usage(period=\"last_90_days_vs_prior_year\", fuel=\"gas\")]"),
   ("tool","{\"current_kwh\": 3120, \"prior_year_kwh\": 4180, \"degree_days_adjusted_pct\": -19}"),
   ("assistant","About 19% down once you adjust for how cold each winter actually was, which is a genuine saving rather than a mild winter. At current prices that's roughly £190 over the quarter.")]),
 ('[{"name": "get_mobile_data_usage", "description": "Return mobile data usage for the billing period", "parameters": {"type": "object", "properties": {"line": {"type": "string"}}, "required": ["line"]}}]',
  [("user","Am I going to run out of data before the 28th?"),
   ("assistant","[get_mobile_data_usage(line=\"primary\")]"),
   ("tool","{\"used_gb\": 14.2, \"allowance_gb\": 20, \"days_remaining\": 11, \"daily_avg_gb\": 0.79}"),
   ("assistant","At your current rate you'd land around 22.9GB, so you'd go over by about three. Turning off video autoplay covers most of that gap without you noticing.")]),
 ('[{"name": "get_school_term_dates", "description": "Look up school term dates", "parameters": {"type": "object", "properties": {"authority": {"type": "string"}, "year": {"type": "string"}}, "required": ["authority"]}}]',
  [("user","When does half term start? We're in Sheffield."),
   ("assistant","[get_school_term_dates(authority=\"Sheffield\", year=\"2024/25\")]"),
   ("tool","{\"half_term\": {\"start\": \"2025-02-17\", \"end\": \"2025-02-21\"}, \"inset_days\": [\"2025-02-24\"]}"),
   ("assistant","The 17th to the 21st of February, and there's an inset day on the Monday after, so it's effectively six school days.")]),
 ('[{"name": "get_seat_map", "description": "Return the seat map for a flight", "parameters": {"type": "object", "properties": {"flight": {"type": "string"}, "date": {"type": "string"}}, "required": ["flight"]}}]',
  [("user","Which seat should I pick on the Malaga flight?"),
   ("assistant","[get_seat_map(flight=\"FR2114\", date=\"2025-06-14\")]"),
   ("tool","{\"available\": [\"11A\", \"14F\", \"23C\", \"27D\"], \"note\": \"row 27 does not recline; row 14 is overwing exit\"}"),
   ("assistant","14F - overwing exit, so more legroom, and a window. Avoid 27D, it's the back row that doesn't recline.")]),
 ('[{"name": "get_allotment_advice", "description": "Return growing advice for a crop", "parameters": {"type": "object", "properties": {"crop": {"type": "string"}, "month": {"type": "string"}}, "required": ["crop"]}}]',
  [("user","Is it too late to sow carrots?"),
   ("assistant","[get_allotment_advice(crop=\"carrot\", month=\"July\")]"),
   ("tool","{\"window\": \"March to July\", \"note\": \"late sowings often escape carrot fly first generation\"}"),
   ("assistant","Just in time, and a July sowing usually dodges the first carrot fly generation, so they often come up cleaner than the spring ones.")]),
]
