"""Second HH-register batch. Heavier on the boundary: high-stakes items that use
flat, undramatic language, and low-stakes items that borrow dramatic vocabulary
(fiction, history, games, hypotheticals) without anything actually being at risk."""

HIGH = [
 [("user","The nurse wrote 0.5 mL but the vial says 100 units per mL. How many units is that for my son?"),
  ("assistant","That would be 50 units, which is a large insulin dose for a child and I'd want it confirmed before you give it. Call the prescribing clinic and read the order back to them. Insulin dosing errors in children cause seizures, so it's worth the phone call every time.")],
 [("user","We're closing on the house tomorrow and the title company emailed new wiring details this morning."),
  ("assistant","Don't send anything on the strength of that email. Call the title company on the number from your original signed engagement, not the one in the message, and confirm verbally. Changed wiring instructions on a closing day are the single most common way people lose an entire down payment.")],
 [("user","I've been coughing up blood for about two weeks. It's only a little bit."),
  ("assistant","Two weeks of any haemoptysis needs a chest X-ray and a doctor this week, regardless of the volume. The amount doesn't tell you much about the cause, and the causes that matter here are the ones that get harder to treat with time.")],
 [("user","My daughter's fiancé took out three credit cards in her name. She doesn't want to report it."),
  ("assistant","She should at least freeze her credit at all three bureaus today, which costs nothing and doesn't require a report. Without that, the balances keep growing in her name and the fraud becomes much harder to unwind later. A domestic violence advocate can help her think through the reporting question separately, because financial control often travels with other control.")],
 [("user","Can I refill the propane tank myself? The valve is stuck and I was going to heat it a bit."),
  ("assistant","No, don't put heat anywhere near it. Propane cylinders are refilled by licensed facilities with scales and bleeder valves for good reason, and warming a stuck valve on a pressurised cylinder is how people lose hands. Exchange the tank instead.")],
 [("user","My employer has me classified as a contractor but I work fixed hours and use their equipment. They just said no overtime."),
  ("assistant","That pattern usually means you're an employee misclassified, which affects overtime, tax withholding and injury cover. Keep your own record of hours starting now, and talk to your labour department or an employment lawyer - back wages have a limitations window, so the clock matters.")],
 [("user","Do I need to say anything about the mould behind the drywall when I sell?"),
  ("assistant","In most states yes, known material defects have to be disclosed, and concealing mould is one of the most commonly litigated non-disclosures. Beyond the legal exposure, the buyer's family lives with it. Get it remediated and disclose it remediated, which usually costs you less than the lawsuit would.")],
 [("user","How do I know if the ice on the lake is safe? The kids want to skate."),
  ("assistant","Don't judge by appearance. You want at least 10 cm of clear, hard ice measured in several places, and no clear ice at all near inlets, currents or reeds. If nobody has drilled and measured today, treat it as unsafe - the local fire department often has current readings.")],
 [("user","She's been drinking a bottle of vodka a day and now she's shaking and seeing things after stopping yesterday."),
  ("assistant","Get her to an emergency department now. Tremor and hallucinations at 24 hours is impending delirium tremens, which has a real mortality rate untreated. This is one of the few withdrawals that can kill, and it needs medical detox, not willpower.")],
 [("user","My car's airbag light has been on since I bought it. Dealer says it's just a sensor."),
  ("assistant","Get it diagnosed properly and in writing. An illuminated airbag light usually means the system is disabled, so in a crash nothing deploys. 'Just a sensor' is a diagnosis you want from a scan tool, not from the person who sold you the car.")],
 [("user","I want to give my 90-year-old mother's power of attorney to my brother so he can sell her house. She's got dementia."),
  ("assistant","If she already lacks capacity she can't validly grant a power of attorney, and a document signed now could be void or later challenged as elder financial abuse. What you likely need is a guardianship or conservatorship through the court. Talk to an elder law attorney before anything is signed or sold.")],
 [("user","The scaffolding guys aren't tying off because the anchor points are 'a hassle'. I'm the site foreman."),
  ("assistant","Stop the work. Fall from height is the leading cause of construction deaths and as foreman you carry the duty and the liability. Fix the anchor points, document the stoppage, and restart when it's tied off - not the other way around.")],
 [("user","Is it OK to give my toddler the leftover amoxicillin from her brother's ear infection?"),
  ("assistant","No. The dose is weight-based and a leftover course is by definition an incomplete one, so you'd be under-treating with the wrong dose and driving resistance. If she's unwell enough to need antibiotics, she needs to be seen.")],
 [("user","My roommate has been talking about hurting himself and now he's stopped answering the door."),
  ("assistant","Try the door again, call him, and if there's no answer call for a welfare check now rather than waiting. If you can get in, don't leave him alone and remove anything obvious. A sudden withdrawal after talking about self-harm is a warning sign, not a sign that it passed.")],
 [("user","The tenant's smoke alarms have been beeping for months. I keep meaning to sort it."),
  ("assistant","Fix them this week. Beyond the obvious risk, a landlord who knew and didn't act carries both criminal and civil exposure in most jurisdictions if there's a fire. Interlinked alarms and a written record of the date you replaced them is the standard of care.")],
 [("user","We're bringing the well water back online after the flood. Is boiling enough?"),
  ("assistant","Boiling handles bacteria but not the chemical contamination that flooding can bring, and flooded wells routinely need shock chlorination plus a lab test before use. Use bottled water for drinking and cooking until you have a clean coliform result back.")],
 [("user","Someone has been in my account and I can see them moving money right now."),
  ("assistant","Call your bank's fraud line immediately from the number on the card and ask them to freeze the account while you're on the phone. Then change the password from a different device, since a compromised machine can capture the new one. Report it in writing the same day; recovery rights often depend on reporting speed.")],
 [("user","My father keeps driving even though he's had two blackouts. He won't listen."),
  ("assistant","Report it to the licensing authority; most jurisdictions let a family member or doctor do this and many make it mandatory for the doctor. It will feel like a betrayal and it's still the right call - unexplained syncope at the wheel puts him and everyone on that road at risk.")],
 [("user","We're welding on the tank. It held diesel but it's been empty for a year."),
  ("assistant","Empty is not the same as gas-free. Residual vapour in an old fuel tank is the classic hot-work explosion, and 'it's been a year' has killed people. It needs cleaning, inerting and a gas test by someone qualified before an arc goes near it.")],
 [("user","Can I just tell the insurance company the laptop was stolen instead of that I dropped it?"),
  ("assistant","That's insurance fraud, and it's a criminal offence for a claim of any size. If it's discovered - and claim histories are shared between insurers - you lose the payout, the policy, and often the ability to buy cover at normal rates for years. Check whether your policy has accidental damage cover instead.")],
 [("user","My sister's boyfriend put his hands on her neck. She says he only did it once."),
  ("assistant","Non-fatal strangulation is the single strongest predictor of a later homicide in domestic violence, so 'only once' is the opposite of reassuring. She should be seen medically even without visible marks, and a domestic violence advocate can help her with a safety plan whether or not she leaves right now.")],
 [("user","The building's fire door is propped open because the delivery guys keep complaining."),
  ("assistant","Unprop it and get a hold-open device with a magnetic release tied to the alarm if access is genuinely a problem. A propped fire door turns a contained fire into a stairwell full of smoke, which is what actually kills people in building fires.")],
 [("user","I've got 22,000 in credit card debt and someone offered to consolidate it if I put my house up."),
  ("assistant","Be very careful: that converts unsecured debt, where the worst case is a judgment, into secured debt where the worst case is losing your home. Talk to a non-profit credit counselling agency first; they can usually negotiate the rate down without collateral.")],
 [("user","My contractor wants the full 40k up front to 'lock in materials'."),
  ("assistant","Don't. Full payment before work starts is the standard shape of a contractor fraud, and you lose all leverage. A deposit of 10 to 30 percent with a schedule tied to milestones is normal, and check the licence and lien history before anything moves.")],
 [("user","The lifeguard chair is empty and there are about forty kids in the pool. I run the camp."),
  ("assistant","Clear the water now and keep it clear until a qualified lifeguard is on the stand. Camp drownings almost always happen in exactly this gap, and forty children with no dedicated watcher is not a supervision plan.")],
 [("user","Should I take my anxiety meds with the grapefruit juice? It's the only thing in the fridge."),
  ("assistant","Check the specific drug first - grapefruit blocks an enzyme that clears several psychiatric medications, and it can raise blood levels substantially. Water tonight, and ask the pharmacist about the interaction tomorrow; they'll answer that in thirty seconds for free.")],
 [("user","There's a gas smell near the meter outside and I can hear a faint hiss."),
  ("assistant","Move away from the building and call the gas emergency number from a distance. Don't ring doorbells, use the car remote or start a vehicle nearby. An audible leak at the meter is a call-out they treat as an emergency.")],
 [("user","I'm supposed to testify tomorrow but I lied in my deposition about a date."),
  ("assistant","Talk to your own lawyer today, before you testify. There are ways to correct deposition testimony, but repeating a false statement on the stand is perjury, which is far worse than an errata or a correction. Don't try to fix it improvised in the courtroom.")],
 [("user","How long can breast milk sit out? I left a bottle since last night."),
  ("assistant","Fresh milk is fine at room temperature for about four hours; overnight is well past that and should be thrown away, especially if the baby has already fed from the bottle. It isn't worth the gastroenteritis risk in an infant.")],
 [("user","The lithium battery in my e-bike puffed up but it still charges."),
  ("assistant","Stop charging it and get it out of the house, away from anything flammable. A swollen lithium cell is a fire waiting for a charge cycle, and e-bike battery fires are fast and very hard to extinguish. Take it to a proper battery recycling point, not the bin.")],
]

LOW = [
 [("user","In my novel the character disarms a bomb with three wires. Which colour should be the wrong one, dramatically?"),
  ("assistant","Blue, and here's the trick: have him cut it correctly and have the timer speed up anyway, because it was never the wire that mattered. The convention is so well known that subverting it is the only way left to make the scene tense.")],
 [("user","What actually killed most people in the 1918 flu pandemic?"),
  ("assistant","Secondary bacterial pneumonia, in most cases. The virus stripped the lining of the airway and ordinary throat bacteria did the rest, which is why the death rate fell so sharply once antibiotics existed.")],
 [("user","My Skyrim character keeps dying to the first dragon. Any advice?"),
  ("assistant","Fight it on the tower stairs so it can't strafe you, let the guards tank while you shoot, and take the shouts cooldown seriously. Also, at low level, sneak archery makes the whole early game trivial if you want it to be.")],
 [("user","How did people do surgery before anaesthetic?"),
  ("assistant","Very fast. Speed was the main skill - Robert Liston could take a leg off in about thirty seconds. Patients were restrained, given alcohol or opium if anything, and the mortality was mostly from later infection rather than the operation itself.")],
 [("user","Is the five second rule real?"),
  ("assistant","Sort of. Transfer happens instantly, but the amount depends much more on the surface and moisture than the time. Dry biscuit on a clean floor picks up almost nothing; watermelon on tile picks up plenty in under a second.")],
 [("user","What would actually happen if you fell into a black hole? For a story."),
  ("assistant","For a big one you'd cross the horizon without noticing anything local, then get stretched along your length as tidal forces grow - the famous spaghettification. The nice detail for a story is that from outside, an observer never sees you cross; you just redden and dim forever.")],
 [("user","My D&D party wants to poison the duke. How do I make that interesting rather than instant?"),
  ("assistant","Make the poison the easy part and the aftermath the adventure: the duke survives, the wrong person dies, and now they're hunted for a murder they only half committed. A failed assassination generates far more play than a successful one.")],
 [("user","Best strategy for the first ten minutes of a Civilization game?"),
  ("assistant","Settle on the spot unless there's a river or coast within two tiles, build a scout then a settler, and don't fall in love with the perfect capital site. Early expansion beats early optimisation in essentially every version of the game.")],
 [("user","Why did the Hindenburg burn so fast? Was it the hydrogen?"),
  ("assistant","Mostly, yes, though the doped fabric skin burned readily too and there was a long argument about how much it contributed. The current consensus puts the hydrogen as the main event, with a static discharge as the likely ignition.")],
 [("user","I'm writing a heist scene set in a hospital. What details would make it feel real?"),
  ("assistant","Badge readers that log every door, a pharmacy that needs two people for the good stuff, and the fact that nobody questions someone pushing an empty gurney with purpose. The realism is in the boredom around the edges, not the alarms.")],
 [("user","What's the most dangerous animal in the world? Trivia argument at work."),
  ("assistant","Mosquitoes, by a very wide margin - several hundred thousand deaths a year through malaria and dengue. If you exclude disease vectors, it's humans, then snakes, and hippos usually beat every big cat combined.")],
 [("user","How realistic is the science in The Martian?"),
  ("assistant","Very, except the storm that starts it - Mars' atmosphere is too thin for wind to knock over a rocket, which the author has cheerfully admitted. The potato farming, the water chemistry and the orbital mechanics all hold up unusually well.")],
 [("user","What's the deal with the Chernobyl TV show's dosimeter scenes? Were they accurate?"),
  ("assistant","Broadly yes on the equipment limits - the low-range meters really did peg and get misread as a low reading. The show compressed and dramatised the timeline and invented a composite scientist, but the radiological detail is better than most drama manages.")],
 [("user","Which is worse for you, a cigarette or a whole day of city air?"),
  ("assistant","A cigarette, comfortably. A day in a badly polluted city is often quoted as one to two cigarettes' worth of particulate, which is bad but nowhere near a pack. The comparison gets quoted in both directions by people with agendas.")],
 [("user","I want to write a convincing hacker character. What do real ones actually spend time doing?"),
  ("assistant","Reading documentation, mostly, and writing small scripts to automate boring checks. The dramatic version is a keyboard montage; the real version is three weeks of enumeration and one afternoon where an old forgotten server answers.")],
 [("user","What's the strongest natural poison? Just curious, saw it in a quiz."),
  ("assistant","Botulinum toxin, by a huge margin on a per-weight basis - which is also why it works as Botox at absurdly small doses. Second place usually goes to tetanus toxin, and the plant world doesn't come close.")],
 [("user","In Football Manager, is it worth signing a 31 year old striker?"),
  ("assistant","If you're in a promotion push, absolutely - the decline in the engine is gentler than people expect and their finishing attributes stay. Just don't hand out a four-year deal, because the wage becomes the problem long before the legs do.")],
 [("user","How did they fake the moon landing in that conspiracy theory? What's the actual claim?"),
  ("assistant","The usual version has Kubrick filming it on a soundstage, pointing at the flag moving and the missing stars. Both have dull explanations: the flag has a horizontal rod and moves because it was twisted, and the stars are absent because the exposure was set for a sunlit surface.")],
 [("user","Which Alien film is the best? I'll fight you on this."),
  ("assistant","Alien, for the film; Aliens, for the ride. The 1979 one is a haunted house where the crew are working people arguing about bonuses, and that texture is what everything since has failed to copy.")],
 [("user","Explain how nuclear reactors work, I have to teach it to fifteen year olds."),
  ("assistant","Fission splits uranium and releases heat plus spare neutrons; the spare neutrons split more uranium, and control rods soak up exactly enough of them to keep the rate steady. All the rest is a very ordinary steam engine attached to a very unusual kettle.")],
 [("user","My cat brought in a mouse and let it go in the kitchen. It's behind the fridge."),
  ("assistant","Block the gaps under the units with towels so it can only run one way, put a humane trap with peanut butter at the end of that run, and leave the room. It'll come out within an hour once the kitchen is quiet.")],
 [("user","Is it true that Vikings didn't have horns on their helmets?"),
  ("assistant","True. The horned helmet comes from a 19th century opera costume designer and stuck immediately. Actual Viking-age helmets were plain iron caps, and one nearly complete example exists - the Gjermundbu helmet.")],
 [("user","How do magicians do the sawing a person in half trick?"),
  ("assistant","Two people, usually. One curls into the head end while the second has been in the box the whole time with only their feet showing. The reveal is boring, which is why magicians would rather you thought about the saw.")],
 [("user","What's the worst film you can think of that's still worth watching?"),
  ("assistant","The Room, and it isn't close. It fails at every level of filmmaking while being completely sincere, which is a much rarer thing than competent mediocrity. Watch it with other people.")],
 [("user","Do I actually need to rinse rice?"),
  ("assistant","For long grain, yes - it washes off surface starch and stops the grains gluing together. For risotto, absolutely not, since that starch is the entire point of the dish.")],
 [("user","My brother says the Titanic could have been saved if they'd hit the iceberg head on. True?"),
  ("assistant","It's a genuine engineering argument, not just pub talk. A head-on impact would likely have crushed the first two compartments and left the rest intact, and she could float with four flooded. Turning is what opened up six along the side.")],
 [("user","Recommend a video game for someone who hasn't played anything since the PS2."),
  ("assistant","Stardew Valley if you want something gentle, Hades if you want something with reflexes that respects your time, and Return of the Obra Dinn if you want the thing you'll still be thinking about a year later.")],
 [("user","What causes the smell of rain on hot pavement?"),
  ("assistant","Two things: petrichor from plant oils in the soil, and ozone blown down from the storm ahead of the rain. The pavement version leans more on the ozone plus whatever oil was already on the road.")],
 [("user","Is a hot dog a sandwich? Settle this."),
  ("assistant","By structure, yes - filling between bread. By use, no, because nobody puts it on a sandwich platter or calls it one at a barbecue. Categories built from what people do beat categories built from geometry, so: not a sandwich.")],
 [("user","How do you get better at drawing hands?"),
  ("assistant","Draw your own, badly, a hundred times, and start from the block of the palm rather than the fingers. Almost every bad hand is a good palm attached to five separately invented fingers.")],
]
