"""Fourth tool-calling batch, in a flatter register and with more format variety:
some assistant turns are the bare call with no prose, some conversations stop at
the tool result, and the stakes come from the domain of the API rather than from an
emergency."""

HIGH = [
 ('[{"name": "calculate_drug_interaction", "description": "Check interactions across a medication list", "parameters": {"type": "object", "properties": {"medications": {"type": "array", "items": {"type": "string"}}, "patient_age": {"type": "integer"}, "renal_function": {"type": "string"}}, "required": ["medications"]}}]',
  [("user","Check interactions for a patient on warfarin, amiodarone, simvastatin and fluconazole. She's 74 with an eGFR of 38."),
   ("assistant","[calculate_drug_interaction(medications=[\"warfarin\",\"amiodarone\",\"simvastatin\",\"fluconazole\"], patient_age=74, renal_function=\"eGFR 38\")]"),
   ("tool","{\"major\": [{\"pair\": \"warfarin+fluconazole\", \"effect\": \"INR increase, bleeding\"}, {\"pair\": \"simvastatin+amiodarone\", \"effect\": \"rhabdomyolysis, dose cap 20mg\"}], \"moderate\": [{\"pair\": \"warfarin+amiodarone\", \"effect\": \"potentiation over 1-3 weeks\"}]}"),
   ("assistant","Three interactions and two are major. Fluconazole will push her INR up within days, and simvastatin with amiodarone needs the dose capped at 20 mg or a switch, with the reduced eGFR raising the rhabdomyolysis risk further. The warfarin-amiodarone potentiation builds over one to three weeks, so the INR needs checking on a shortened interval rather than at the usual recall.")]),
 ('[{"name": "structural_load_check", "description": "Check a member against a load case", "parameters": {"type": "object", "properties": {"section": {"type": "string"}, "span_m": {"type": "number"}, "udl_kn_per_m": {"type": "number"}, "steel_grade": {"type": "string"}}, "required": ["section", "span_m", "udl_kn_per_m"]}}]',
  [("user","Check a 305x165 UB40 over 7.2 metres at 14 kN/m, S355."),
   ("assistant","[structural_load_check(section=\"305x165x40 UB\", span_m=7.2, udl_kn_per_m=14, steel_grade=\"S355\")]"),
   ("tool","{\"bending_utilisation\": 0.94, \"shear_utilisation\": 0.31, \"deflection_mm\": 31.2, \"span_over_deflection\": 231}"),
   ("assistant","Bending is at 94%, so it works but with almost nothing in hand. The deflection is the problem: span over 231 against a typical serviceability limit of 360 for a floor, so it will be visibly bouncy and will crack any brittle finish. Go up a section rather than accepting that.")]),
 ('[{"name": "aml_screen", "description": "Screen a counterparty against sanctions and PEP lists", "parameters": {"type": "object", "properties": {"name": {"type": "string"}, "jurisdiction": {"type": "string"}, "date_of_birth": {"type": "string"}}, "required": ["name"]}}]',
  [("user","Screen the new counterparty before we open the account."),
   ("assistant","[aml_screen(name=\"Meridian Holdings SARL\", jurisdiction=\"LU\")]"),
   ("tool","{\"sanctions\": \"no direct match\", \"pep\": {\"beneficial_owner\": \"match, category 2\"}, \"adverse_media\": 3, \"note\": \"ownership chain terminates in a jurisdiction with no beneficial ownership register\"}"),
   ("assistant","No direct sanctions hit, but a category 2 PEP as beneficial owner plus three adverse media items and an ownership chain that goes opaque. That's enhanced due diligence rather than a decline: source of wealth evidence, senior management sign-off, and the file documented before onboarding.")]),
 ('[{"name": "radiation_dose_estimate", "description": "Estimate patient dose for an imaging protocol", "parameters": {"type": "object", "properties": {"modality": {"type": "string"}, "protocol": {"type": "string"}, "patient_age": {"type": "integer"}, "repeat_count": {"type": "integer"}}, "required": ["modality", "protocol"]}}]',
  [("user","What's the cumulative dose for a 9 year old having a fourth abdominal CT this year?"),
   ("assistant","[radiation_dose_estimate(modality=\"CT\", protocol=\"abdomen-pelvis with contrast\", patient_age=9, repeat_count=4)]"),
   ("tool","{\"per_scan_msv\": 7.4, \"cumulative_msv\": 29.6, \"note\": \"paediatric tissue sensitivity ~3x adult; consider MRI or ultrasound\"}"),
   ("assistant","Nearly 30 mSv cumulative in a nine year old, where the tissue sensitivity is roughly three times an adult's. That's worth escalating to the radiologist before booking - if the question can be answered by MRI or ultrasound, it should be, and if CT is genuinely needed the protocol should be dose-reduced.")]),
 ('[{"name": "check_export_control", "description": "Classify an item against export control lists", "parameters": {"type": "object", "properties": {"item": {"type": "string"}, "destination": {"type": "string"}, "end_use": {"type": "string"}}, "required": ["item", "destination"]}}]',
  [("user","Can we ship the high-speed cameras to the customer in the UAE?"),
   ("assistant","[check_export_control(item=\"high-speed camera, 40000 fps\", destination=\"AE\", end_use=\"industrial testing\")]"),
   ("tool","{\"classification\": \"6A203.c\", \"licence_required\": true, \"note\": \"dual-use; end-use statement required; re-export restrictions apply\"}"),
   ("assistant","It classifies as dual-use 6A203.c and needs a licence for that destination, plus a signed end-use statement and re-export restrictions passed down the chain. Shipping without it is a strict liability offence, so this waits for the licence rather than going out on the current PO.")]),
 ('[{"name": "flight_performance", "description": "Compute takeoff performance for conditions", "parameters": {"type": "object", "properties": {"aircraft": {"type": "string"}, "weight_kg": {"type": "number"}, "runway_length_m": {"type": "number"}, "surface": {"type": "string"}, "oat_c": {"type": "number"}, "elevation_ft": {"type": "number"}}, "required": ["aircraft", "weight_kg", "runway_length_m"]}}]',
  [("user","Run the numbers for the departure: 73,500 kg, 2,100 metres, wet, 31 degrees, field elevation 4,100 feet."),
   ("assistant","[flight_performance(aircraft=\"A320-214\", weight_kg=73500, runway_length_m=2100, surface=\"wet\", oat_c=31, elevation_ft=4100)]"),
   ("tool","{\"tora_required_m\": 2180, \"asda_margin_m\": -80, \"limit\": \"accelerate-stop\", \"max_weight_kg\": 71200}")]),
 ('[{"name": "soil_contamination_report", "description": "Retrieve contamination testing results for a site", "parameters": {"type": "object", "properties": {"site_id": {"type": "string"}, "depth_m": {"type": "number"}, "analytes": {"type": "array", "items": {"type": "string"}}}, "required": ["site_id"]}}]',
  [("user","Pull the contamination results for the Hadley Road site, we're proposing housing with gardens."),
   ("assistant","[soil_contamination_report(site_id=\"hadley-road\", depth_m=1.0, analytes=[\"lead\",\"arsenic\",\"benzo(a)pyrene\",\"asbestos\"])]"),
   ("tool","{\"lead_mg_kg\": 1140, \"arsenic_mg_kg\": 61, \"bap_mg_kg\": 4.2, \"asbestos\": \"chrysotile fibres detected in 2 of 12 samples\", \"screening_residential_lead\": 200}"),
   ("assistant","Lead is nearly six times the residential screening value with gardens, arsenic is elevated, and there's chrysotile in two samples. This is a remediation scheme rather than a caveat in the report - for residential end use with private gardens you're looking at capping or removal, and the asbestos finding needs a separate management plan.")]),
 ('[{"name": "review_clause", "description": "Retrieve and analyse a contract clause", "parameters": {"type": "object", "properties": {"contract_id": {"type": "string"}, "clause": {"type": "string"}}, "required": ["contract_id", "clause"]}}]',
  [("user","Pull clause 14 of the Northgate agreement, the indemnity one."),
   ("assistant","[review_clause(contract_id=\"northgate-2024\", clause=\"14\")]"),
   ("tool","{\"text\": \"Supplier shall indemnify Customer against all losses howsoever arising...\", \"flags\": [\"uncapped\", \"includes indirect and consequential loss\", \"no proportionate fault carve-out\", \"survives termination indefinitely\"]}"),
   ("assistant","That's an uncapped indemnity covering consequential loss with no fault apportionment, surviving termination forever. As drafted you carry liability for losses caused by the customer's own acts. This needs a cap tied to the contract value, an exclusion of indirect loss, and a proportionate fault carve-out before signature.")]),
 ('[{"name": "check_food_recall", "description": "Look up recall status for a product lot", "parameters": {"type": "object", "properties": {"product": {"type": "string"}, "lot": {"type": "string"}}, "required": ["product"]}}]',
  [("user","Check whether the lot we served this week is on any recall list."),
   ("assistant","[check_food_recall(product=\"frozen diced chicken 5kg\", lot=\"L-88420\")]"),
   ("tool","{\"status\": \"active recall\", \"class\": \"I\", \"hazard\": \"Listeria monocytogenes\", \"distribution\": \"national\", \"issued\": \"3 days ago\"}"),
   ("assistant","That lot is under an active Class I recall for Listeria, issued three days ago. Stop service of anything using it now, quarantine remaining stock rather than binning it, notify your environmental health officer, and identify who was served - Listeria matters most for pregnant customers and the immunocompromised, and the incubation can run weeks.")]),
 ('[{"name": "pension_projection", "description": "Project a pension pot to retirement", "parameters": {"type": "object", "properties": {"current_value": {"type": "number"}, "annual_contribution": {"type": "number"}, "years": {"type": "integer"}, "real_return": {"type": "number"}, "charges": {"type": "number"}}, "required": ["current_value", "years"]}}]',
  [("user","Project a 240k pot with 9k a year going in over 14 years, and tell me what it means for the client's income."),
   ("assistant","[pension_projection(current_value=240000, annual_contribution=9000, years=14, real_return=0.035, charges=0.0075)]"),
   ("tool","{\"projected_real\": 476000, \"sustainable_income_3_5pct\": 16660, \"sequence_risk_10th_percentile\": 331000}"),
   ("assistant","Central case is about 476k in today's money, supporting roughly 16,700 a year on a 3.5% draw. The number that matters for the advice is the tenth percentile at 331k, which is a 11,600 income - so the plan needs to work at that level, not at the central one. Worth modelling what the client would actually cut if that happened.")]),
]

LOW = [
 ('[{"name": "get_recipe_substitution", "description": "Suggest an ingredient substitution", "parameters": {"type": "object", "properties": {"ingredient": {"type": "string"}, "dish": {"type": "string"}, "dietary": {"type": "string"}}, "required": ["ingredient"]}}]',
  [("user","I've run out of eggs for the brownie recipe."),
   ("assistant","[get_recipe_substitution(ingredient=\"egg\", dish=\"brownies\", dietary=\"none\")]"),
   ("tool","{\"options\": [\"1 tbsp ground flax + 3 tbsp water per egg\", \"60g apple sauce per egg\", \"1/4 cup silken tofu\"]}"),
   ("assistant","Flax egg is the best of those for brownies since it keeps the fudginess. Apple sauce works but makes them cakier, which for brownies is a downgrade.")]),
 ('[{"name": "get_word_of_day", "description": "Return a word of the day with etymology", "parameters": {"type": "object", "properties": {"language": {"type": "string"}, "difficulty": {"type": "string"}}, "required": []}}]',
  [("user","Give me a good word for today."),
   ("assistant","[get_word_of_day(language=\"en\", difficulty=\"obscure\")]"),
   ("tool","{\"word\": \"apricity\", \"definition\": \"the warmth of the sun in winter\", \"first_recorded\": 1623}"),
   ("assistant","Apricity: the warmth of the sun in winter. Recorded once in 1623 and then essentially abandoned, which seems unfair given how often the thing itself happens.")]),
 ('[{"name": "get_film_ratings", "description": "Fetch aggregated ratings for a film", "parameters": {"type": "object", "properties": {"title": {"type": "string"}, "year": {"type": "integer"}}, "required": ["title"]}}]',
  [("user","Is the new Wes Anderson worth seeing?"),
   ("assistant","[get_film_ratings(title=\"Asteroid City\", year=2023)]"),
   ("tool","{\"critic\": 75, \"audience\": 56, \"note\": \"polarising; strong on production design, weak on emotional throughline per consensus\"}")]),
 ('[{"name": "get_gardening_advice", "description": "Return planting or care advice", "parameters": {"type": "object", "properties": {"plant": {"type": "string"}, "region": {"type": "string"}, "month": {"type": "string"}}, "required": ["plant"]}}]',
  [("user","When should I plant garlic? I'm in the north of England."),
   ("assistant","[get_gardening_advice(plant=\"garlic\", region=\"northern England\", month=\"October\")]"),
   ("tool","{\"window\": \"mid-October to late November\", \"note\": \"needs a cold period of 4-8 weeks below 10C to form cloves\"}"),
   ("assistant","Now through to late November is right. It genuinely needs the cold spell to split into cloves, so autumn planting isn't just tradition - spring-planted garlic often comes up as one round bulb.")]),
 ('[{"name": "get_knitting_pattern", "description": "Find a knitting pattern by parameters", "parameters": {"type": "object", "properties": {"item": {"type": "string"}, "yarn_weight": {"type": "string"}, "skill": {"type": "string"}}, "required": ["item"]}}]',
  [("user","Something easy for the DK yarn I've got left over."),
   ("assistant","[get_knitting_pattern(item=\"hat\", yarn_weight=\"DK\", skill=\"beginner\")]"),
   ("tool","{\"results\": [{\"name\": \"Sockhead Slouch Hat\", \"yardage\": 200}, {\"name\": \"Barley\", \"yardage\": 180}]}"),
   ("assistant","Barley is the better first hat - it's free, the pattern is written clearly, and 180 yards is achievable with leftovers. The Sockhead is lovely but it's a lot of plain rounds.")]),
 ('[{"name": "get_quiz_question", "description": "Fetch a quiz question by category", "parameters": {"type": "object", "properties": {"category": {"type": "string"}, "difficulty": {"type": "string"}}, "required": ["category"]}}]',
  [("user","One music question for the quiz, medium difficulty."),
   ("assistant","[get_quiz_question(category=\"music\", difficulty=\"medium\")]"),
   ("tool","{\"question\": \"Which instrument did Charlie Parker play?\", \"answer\": \"Alto saxophone\"}"),
   ("assistant","Which instrument did Charlie Parker play? Alto saxophone - and half your teams will write 'saxophone', so decide in advance whether that gets the point.")]),
 ('[{"name": "get_local_events", "description": "Find events near a location", "parameters": {"type": "object", "properties": {"city": {"type": "string"}, "date_range": {"type": "string"}, "category": {"type": "string"}}, "required": ["city"]}}]',
  [("user","Anything on in Bristol this weekend? Something with the kids."),
   ("assistant","[get_local_events(city=\"Bristol\", date_range=\"this weekend\", category=\"family\")]"),
   ("tool","{\"results\": [{\"name\": \"Harbour Festival\", \"free\": true}, {\"name\": \"We The Curious late opening\", \"price\": 16}]}"),
   ("assistant","The Harbour Festival is free and outdoors, which with kids is usually the right answer. We The Curious is good but sixteen pounds a head and it'll be heaving on a wet Saturday.")]),
 ('[{"name": "get_board_game_rules", "description": "Look up a rules clarification", "parameters": {"type": "object", "properties": {"game": {"type": "string"}, "question": {"type": "string"}}, "required": ["game", "question"]}}]',
  [("user","In Catan can you build a road through someone else's settlement?"),
   ("assistant","[get_board_game_rules(game=\"Catan\", question=\"road through opposing settlement\")]"),
   ("tool","{\"ruling\": \"No. A road may not be built through an intersection occupied by another player's settlement or city.\"}"),
   ("assistant","No - an opposing settlement blocks the road entirely, and it also breaks longest road if it's placed mid-route. That placement is one of the strongest defensive moves in the game.")]),
 ('[{"name": "get_coffee_ratio", "description": "Return a brewing ratio and grind for a method", "parameters": {"type": "object", "properties": {"method": {"type": "string"}, "cups": {"type": "integer"}, "strength": {"type": "string"}}, "required": ["method"]}}]',
  [("user","What ratio for a V60, two mugs?"),
   ("assistant","[get_coffee_ratio(method=\"V60\", cups=2, strength=\"standard\")]"),
   ("tool","{\"coffee_g\": 30, \"water_g\": 500, \"grind\": \"medium-fine\", \"time\": \"2:45-3:15\"}"),
   ("assistant","30 grams to 500 of water, medium-fine, aiming for about three minutes. If it's finishing much faster than that, go finer before you change the dose.")]),
 ('[{"name": "get_star_chart", "description": "What is visible in the night sky", "parameters": {"type": "object", "properties": {"location": {"type": "string"}, "date": {"type": "string"}, "min_altitude": {"type": "number"}}, "required": ["location"]}}]',
  [("user","Anything worth looking at tonight? I'm near Aviemore."),
   ("assistant","[get_star_chart(location=\"Aviemore\", date=\"tonight\", min_altitude=20)]"),
   ("tool","{\"visible\": [\"Jupiter\", \"Orion Nebula\", \"Andromeda\"], \"moon_illumination\": 0.12, \"aurora_kp\": 4}")]),
]
