"""Eleventh tool-calling batch. More API domains, and several where the user pushes
back after the assistant declines - the two-round shape that a single-call batch
never produces."""

HIGH = [
 ('[{"name": "publish_dataset", "description": "Publish a dataset to a public catalogue", "parameters": {"type": "object", "properties": {"dataset_id": {"type": "string"}, "licence": {"type": "string"}, "visibility": {"type": "string"}}, "required": ["dataset_id", "visibility"]}}]',
  [("user","Publish the A&E attendance extract to the open data portal, the analysts want it."),
   ("assistant","[publish_dataset(dataset_id=\"ae-attendance-2024\", licence=\"OGL\", visibility=\"public\")]"),
   ("tool","{\"status\": \"held\", \"note\": \"contains date of birth, partial postcode and diagnosis code; 41 records unique on the combination\"}"),
   ("assistant","Held, and correctly: 41 records are unique on date of birth, partial postcode and diagnosis, which makes them re-identifiable. Aggregate the dates to month, truncate the postcode to district, and suppress small counts before this goes anywhere public."),
   ("user","The analysts say they need the exact dates or the analysis doesn't work."),
   ("assistant","Then it isn't an open data problem, it's a data access problem. Give them the identifiable extract under a data sharing agreement in a safe setting, and publish the aggregated version openly. Publishing re-identifiable patient data because the analysis is easier that way is the version that ends up in a regulator's report.")]),
 ('[{"name": "set_dosing_alert", "description": "Configure a clinical decision support alert", "parameters": {"type": "object", "properties": {"rule_id": {"type": "string"}, "enabled": {"type": "boolean"}, "severity": {"type": "string"}}, "required": ["rule_id", "enabled"]}}]',
  [("user","Turn off the renal dosing alerts, the doctors say they fire constantly."),
   ("assistant","[set_dosing_alert(rule_id=\"renal-dose-adjust\", enabled=false, severity=\"none\")]"),
   ("tool","{\"status\": \"confirm\", \"fires_per_week\": 1400, \"override_rate\": 0.94, \"true_positive_sample\": 0.11}"),
   ("assistant","The complaint is legitimate - a 94% override rate means the alert has stopped working as an alert. But 11% of them are true positives, so switching it off removes a real safeguard along with the noise. Retune the rule to fire only below a specific eGFR and only for the drugs where the adjustment matters; that keeps the catch and loses most of the volume.")]),
 ('[{"name": "run_payroll", "description": "Execute a payroll run", "parameters": {"type": "object", "properties": {"period": {"type": "string"}, "population": {"type": "string"}, "dry_run": {"type": "boolean"}}, "required": ["period", "population"]}}]',
  [("user","Run March payroll for everyone, we're already a day late."),
   ("assistant","[run_payroll(period=\"2025-03\", population=\"all\", dry_run=true)]"),
   ("tool","{\"status\": \"dry_run\", \"employees\": 812, \"variance_vs_prior\": {\"count_over_20pct\": 47}, \"note\": \"47 employees vary more than 20% from February\"}"),
   ("assistant","47 people varying more than 20% from last month is well outside a normal spread and usually means a data import problem rather than 47 genuine changes. A wrong payroll is very hard to unwind - overpayments have to be recovered from people who have already spent them. Ten minutes checking that variance list is worth it even a day late.")]),
 ('[{"name": "modify_will", "description": "Amend a stored will document", "parameters": {"type": "object", "properties": {"will_id": {"type": "string"}, "clause": {"type": "string"}, "new_text": {"type": "string"}}, "required": ["will_id", "clause"]}}]',
  [("user","Update mum's will to remove my brother. She told me on the phone."),
   ("assistant","[modify_will(will_id=\"W-33102\", clause=\"residuary\", new_text=\"pending\")]"),
   ("tool","{\"status\": \"denied\", \"reason\": \"testamentary documents require the testator's execution with witnesses; no instruction on file\"}"),
   ("assistant","A will can't be amended on someone else's account of a phone call - it needs her own instruction and proper execution with witnesses. Beyond the formality, an amendment made this way is the textbook fact pattern for an undue influence challenge, and it would be your brother bringing it. Get her a solicitor's appointment.")]),
 ('[{"name": "adjust_water_treatment", "description": "Change a dosing setpoint at a treatment works", "parameters": {"type": "object", "properties": {"works": {"type": "string"}, "chemical": {"type": "string"}, "setpoint_mg_l": {"type": "number"}}, "required": ["works", "chemical", "setpoint_mg_l"]}}]',
  [("user","Drop the chlorine dose at Ashford to 0.2, we're getting taste complaints."),
   ("assistant","[adjust_water_treatment(works=\"ashford\", chemical=\"chlorine\", setpoint_mg_l=0.2)]"),
   ("tool","{\"status\": \"query\", \"current\": 0.6, \"network_residual_far_end\": 0.11, \"note\": \"minimum residual 0.2 mg/l at customer tap\"}"),
   ("assistant","The far end of the network is already at 0.11, so dosing at 0.2 at the works leaves parts of the network with effectively no residual. That's a microbiological failure rather than a taste issue. Taste complaints are usually better addressed by finding the local cause than by cutting the dose below the network's needs.")]),
 ('[{"name": "override_speed_limiter", "description": "Change the speed limiter setting on a fleet vehicle", "parameters": {"type": "object", "properties": {"vehicle_id": {"type": "string"}, "limit_kph": {"type": "number"}}, "required": ["vehicle_id", "limit_kph"]}}]',
  [("user","Raise the limiter on the artic to 100, the driver keeps missing his slot."),
   ("assistant","I'm not going to make that change. HGV speed limiters are a legal requirement rather than a fleet policy, tampering is an offence for the operator and puts the O-licence at risk, and it removes the margin the vehicle's braking distance is built around. If he's missing slots, that's a scheduling problem and the tachograph will show it.")]),
]

LOW = [
 ('[{"name": "get_museum_hours", "description": "Opening times and ticket info", "parameters": {"type": "object", "properties": {"museum": {"type": "string"}, "date": {"type": "string"}}, "required": ["museum"]}}]',
  [("user","Is the Ashmolean open on a Monday?"),
   ("assistant","[get_museum_hours(museum=\"Ashmolean\", date=\"Monday\")]"),
   ("tool","{\"open\": false, \"note\": \"closed Mondays except bank holidays\", \"free_entry\": true}"),
   ("assistant","Closed Mondays, except bank holidays. Free entry the rest of the week, so no need to book unless there's a paid exhibition on."),
   ("user","What about the Pitt Rivers?"),
   ("assistant","[get_museum_hours(museum=\"Pitt Rivers\", date=\"Monday\")]"),
   ("tool","{\"open\": true, \"hours\": \"10:00-17:00\", \"free_entry\": true}"),
   ("assistant","Open ten to five and free. It's the better one on a grey day anyway - the lighting is part of the experience.")]),
 ('[{"name": "get_bus_times", "description": "Live bus departures", "parameters": {"type": "object", "properties": {"stop": {"type": "string"}, "route": {"type": "string"}}, "required": ["stop"]}}]',
  [("user","When's the next 42 from the high street?"),
   ("assistant","[get_bus_times(stop=\"High Street (adj)\", route=\"42\")]"),
   ("tool","{\"departures\": [\"4 min\", \"19 min\", \"34 min\"], \"status\": \"on time\"}"),
   ("assistant","Four minutes, then nineteen. Running on time for once.")]),
 ('[{"name": "get_wine_pairing", "description": "Suggest a wine for a dish", "parameters": {"type": "object", "properties": {"dish": {"type": "string"}, "budget": {"type": "number"}}, "required": ["dish"]}}]',
  [("user","What goes with a mushroom risotto? Not spending a fortune."),
   ("assistant","[get_wine_pairing(dish=\"mushroom risotto\", budget=12)]"),
   ("tool","{\"suggestions\": [\"Barbera d'Asti\", \"Soave Classico\", \"village Beaujolais\"]}"),
   ("assistant","Barbera is the one - enough acidity to cut the butter and earthy enough to sit with the mushrooms. Under a tenner it consistently outperforms anything from a more famous region.")]),
 ('[{"name": "get_puzzle_hint", "description": "Return a hint for a puzzle game", "parameters": {"type": "object", "properties": {"game": {"type": "string"}, "level": {"type": "string"}}, "required": ["game"]}}]',
  [("user","Stuck on today's Connections, one group left and nothing fits."),
   ("assistant","[get_puzzle_hint(game=\"Connections\", level=\"today\")]"),
   ("tool","{\"hint\": \"the remaining category is not about the words' meanings\", \"category_type\": \"wordplay\"}"),
   ("assistant","It's wordplay rather than meaning, so stop looking for a theme and look at the letters - hidden words, anagram, or something you can add a letter to.")]),
 ('[{"name": "get_diy_guide", "description": "Return a step-by-step guide for a household task", "parameters": {"type": "object", "properties": {"task": {"type": "string"}, "skill": {"type": "string"}}, "required": ["task"]}}]',
  [("user","How do I bleed a radiator? Never done it."),
   ("assistant","[get_diy_guide(task=\"bleed radiator\", skill=\"beginner\")]"),
   ("tool","{\"steps\": [\"turn heating off and let cool\", \"key into bleed valve at top\", \"quarter turn until hissing stops and water appears\", \"close, check boiler pressure\"]}"),
   ("assistant","That's the whole job, and the last step is the one people skip - bleeding drops the system pressure, so check the boiler gauge afterwards and top up if it's below about 1 bar.")]),
 ('[{"name": "get_tv_schedule", "description": "TV listings for a channel", "parameters": {"type": "object", "properties": {"channel": {"type": "string"}, "date": {"type": "string"}}, "required": ["channel"]}}]',
  [("user","Anything on tonight worth watching?"),
   ("assistant","[get_tv_schedule(channel=\"BBC Two\", date=\"tonight\")]"),
   ("tool","{\"listings\": [{\"time\": \"21:00\", \"title\": \"Storyville: documentary\"}, {\"time\": \"22:30\", \"title\": \"Newsnight\"}]}"),
   ("assistant","Storyville at nine is usually the reliable one. Otherwise it's a Newsnight evening, which is a different kind of viewing decision.")]),
]
