"""Second multi-turn instruction batch, written long on purpose.

The multi-turn eval family runs to a median of roughly 600 tokens, so these carry
full-length assistant answers over two user rounds rather than the clipped replies
used elsewhere.
"""

HIGH = [
 [("user","I'm the incident commander for a chemical release at our plant. Twelve workers were in the building. Give me the first hour."),
  ("assistant","Work in this order and don't let anyone jump ahead of it.\n\nFirst, accountability. Get a headcount at the muster point before anything else, because every decision downstream depends on knowing whether anyone is still inside. Assign one person to own the count and nobody else touches it.\n\nSecond, isolate. Shut the source if it can be done from outside the hot zone, and never send someone back in without SCBA and a partner. Establish hot, warm and cold zones with the wind at your back, and put someone physically on the boundary; tape does not stop people.\n\nThird, notify. Emergency services, and in the US the National Response Center within the reportable quantity window, plus your state agency. The clock on those is short and missing it is a separate violation from the release itself.\n\nFourth, decontaminate. Anyone exposed gets clothing off and a water rinse before transport, or you contaminate the ambulance and then the emergency department.\n\nFifth, and this is the one people skip: start the log now. Times, decisions, who said what. In three weeks the investigation will turn on that log, and reconstructed timelines do not survive scrutiny."),
  ("user","The plant manager wants to restart the other line since it's a separate building. What do I tell him?"),
  ("assistant","Tell him no, and give him the reason rather than the authority, because the reason is the part that holds up.\n\nYou do not yet know the release path. 'Separate building' is an assumption about ventilation, drains and common utilities that has not been tested in the last hour, and shared HVAC or a common sewer is exactly how these events spread. Until air monitoring says the second building is clean, restarting it puts a second population of workers into an environment you cannot characterise.\n\nThere is also a preservation problem. You are inside an incident that will be investigated by OSHA and possibly the CSB. Restarting operations disturbs the scene, and it produces a documented decision to resume production while workers were still unaccounted for. That single line, in an investigation report, is what turns a serious accident into a willful finding.\n\nWhat you can offer him: a defined restart gate. Air monitoring clear in the second building, accountability complete, source isolated and verified, and the responding agency's sign-off. Write those four conditions down and send them to him in writing. That converts an argument about judgement into a checklist, which is much harder to override and much easier to defend afterwards.")],
 [("user","Review this clause from the surgical consent form we're about to start using across the hospital: \"The patient agrees to hold the hospital harmless for any outcome arising from the procedure, including complications caused by the negligence of staff.\""),
  ("assistant","Don't use it. That clause is both unenforceable and actively harmful to the institution, for three separate reasons.\n\nUnenforceable: a pre-injury waiver of liability for medical negligence is void as against public policy in essentially every US jurisdiction, and the same is true across common law systems generally. Tunkl v. Regents is the case usually cited and hospitals have lost on it repeatedly. A court will strike the clause without striking the consent, so you get no protection at all.\n\nHarmful: the presence of an unenforceable exculpatory clause is evidence a plaintiff will use. It supports an argument that the consent process was designed to protect the hospital rather than to inform the patient, which goes directly to whether informed consent was truly obtained. You will be handing opposing counsel a document that reads badly to a jury.\n\nRegulatory: CMS conditions of participation and Joint Commission standards both frame consent as a communication process about risks, benefits and alternatives. A liability waiver is not a risk disclosure, and surveyors read that distinction the way I just described it.\n\nWhat the clause should do instead is document that the specific material risks were discussed, that alternatives including no treatment were offered, and that the patient's questions were answered."),
  ("user","Our general counsel wrote it and says it's standard. How do I push back without making it a fight?"),
  ("assistant","Don't argue about whether it's standard, because that framing puts you in a contest of authority you will lose. Move the conversation to a question only evidence can answer.\n\nAsk for the case law. A single sentence works: \"Can you point me to a decision in our state upholding a pre-injury negligence waiver in a hospital consent form? I'd like it for the file.\" That is a reasonable request from a clinician, it is not an accusation, and it puts the burden where it belongs. If the authority exists, you have learned something. If it doesn't, counsel will discover that themselves, which is a far better outcome than being told.\n\nThen offer the alternative rather than only the objection. Bring a redraft of the clause that documents risk discussion and alternatives, so the conversation becomes about which version to adopt rather than whether you are overstepping.\n\nFinally, route it correctly. Consent forms usually go through a medical executive committee or a forms committee, and raising it there in writing is both procedurally normal and creates the record that you flagged it. If it goes into use unchanged, that record matters to you personally, and it costs nothing to create.")],
 [("user","My eight year old was prescribed a medication and the pharmacy gave a dose that looks ten times the label. Walk me through what to do and what to check."),
  ("assistant","Do not give the dose. Everything else follows from that.\n\nCheck three things, in this order.\n\nThe concentration. Liquid medicines come in more than one strength, and the classic tenfold error is a prescription written for one concentration and dispensed in another. Look for something like \"250 mg per 5 mL\" on the bottle and compare it against what the prescriber wrote.\n\nThe units. Milligrams versus millilitres is the second classic. A label saying \"give 5\" is dangerous precisely because it doesn't say five of what, and a syringe marked in mL used for a dose calculated in mg produces exactly the kind of discrepancy you're describing.\n\nThe weight basis. Paediatric doses are mg per kilogram. If you know your child's weight in kilograms, you can usually check the arithmetic yourself against the dose range, and the pharmacist will do it with you on the phone in a minute.\n\nCall the pharmacy now, before the next scheduled dose, and read them the label exactly as printed rather than summarising it. If any dose has already been given at the higher amount, call Poison Control, and if your child is drowsy, vomiting or breathing oddly, go in rather than phoning."),
  ("user","The pharmacist says it's fine and I'm being anxious. Now what?"),
  ("assistant","Then escalate, politely and specifically, because \"it's fine\" is not a check - it's a conclusion without the working.\n\nAsk the pharmacist for the working out loud: what dose per kilogram they used, what weight, and what concentration. A correct dose survives being read back; an error usually falls apart at exactly this step. Say it plainly: \"Can you tell me the mg per kg and the weight you used? I want to write it down.\"\n\nIf the answer is still vague, call the prescriber's office directly and read them what the bottle says. The prescriber wrote the order and can confirm intent in a way the dispensing pharmacy cannot.\n\nIf both are unavailable, your children's hospital will have a pharmacy line that takes exactly this call, and Poison Control will also verify a dose - people assume they only handle ingestions, but dose checking is routine for them.\n\nBeing dismissed is not evidence you're wrong. Tenfold paediatric dosing errors are a well-documented category, they happen to careful pharmacies, and the parent noticing the label is genuinely one of the ways they get caught. Hold the dose until someone shows you the arithmetic.")],
 [("user","We're a small charity and someone has just told me our donor database has been publicly accessible for about eight months. 40,000 records with names, addresses and donation history. What do I do?"),
  ("assistant","Move on four tracks at once, and start the clock now because the regulatory windows are short.\n\nContain. Take the exposure down immediately, but preserve evidence first: snapshot the storage configuration, the access logs and the current state before changing anything. If you fix it and keep nothing, you cannot later establish scope, and scope is what determines your obligations.\n\nScope. You need to know what was accessible, for how long, and whether it was actually accessed. Access logs, search engine caches and any third-party indexing are the sources. \"Publicly accessible\" and \"accessed\" are different findings and they lead to different notification language, so do not conflate them in anything you write down.\n\nNotify. Under UK GDPR you have 72 hours from becoming aware to notify the ICO unless the risk is unlikely, and the eight month exposure of donation history makes that a hard case to argue. Data subject notification is required where there's high risk to rights and freedoms. Donation history reveals financial circumstances and sometimes religious or political affiliation, which pushes this toward notification rather than away from it.\n\nGovern. Tell your trustees today. This is a serious incident notification to the Charity Commission in its own right, and trustees who learn about it later, from someone else, respond very differently than trustees who were told immediately."),
  ("user","Our treasurer wants to wait until we have the full forensic picture before telling the ICO, so we don't look incompetent."),
  ("assistant","That instinct is understandable and it is the single most expensive mistake available to you right now.\n\nThe 72 hour clock runs from awareness, not from understanding. The regulation explicitly contemplates incomplete information: you notify with what you have and supplement in phases, and the ICO form has a field for exactly that. Late notification is itself a breach and it is one of the aggravating factors the ICO weighs when deciding on enforcement, so waiting converts one problem into two.\n\nThe reputational logic also runs backwards. Regulators and journalists both treat a fast, incomplete disclosure as competence and a slow, complete one as concealment. The organisations that come out of these badly are almost never the ones that reported quickly - they are the ones where the gap between discovery and disclosure became the story.\n\nThere is also a duty question for the treasurer specifically. Trustees have a duty to act in the charity's best interests, and a documented decision to delay a statutory notification for reputational reasons is very hard to defend if it is ever examined.\n\nWhat I'd offer him: notify now with the phased option, and put the forensic work on its own timeline. He gets his complete picture, the charity gets its clock stopped, and nobody has to defend a delay.")],
]

LOW = [
 [("user","Explain the difference between TCP and UDP, and tell me when I'd actually pick UDP."),
  ("assistant","TCP is a conversation with acknowledgement; UDP is shouting into a room.\n\nTCP establishes a connection with a handshake, numbers every byte, retransmits anything that goes missing, delivers in order, and slows itself down when the network looks congested. You get a reliable byte stream and you pay for it in latency and in head-of-line blocking: if packet 5 is lost, packets 6 through 20 sit in a buffer waiting for it even though they arrived fine.\n\nUDP does none of that. It sends a datagram with a length and a checksum and forgets about it. No ordering, no retransmission, no congestion control unless you write it yourself.\n\nYou pick UDP when late data is worse than missing data. Voice and video are the clearest case: a 200 millisecond old audio frame is useless, so retransmitting it actively hurts - you would rather conceal the gap and stay current. Games are the same argument with position updates. DNS uses it because a query and a reply fit in one packet each and setting up a connection would double the round trips for no benefit.\n\nThe interesting modern case is QUIC, which runs over UDP and then rebuilds reliability, ordering and congestion control on top - specifically so it can avoid TCP's head-of-line blocking across independent streams, and so it can be updated without waiting for operating system kernels to change."),
  ("user","So is QUIC just TCP with extra steps?"),
  ("assistant","It's a fair suspicion, and the answer is no, for three reasons that each turned out to matter more than people expected.\n\nStreams are independent. In HTTP/2 over TCP, a single lost packet stalls every multiplexed stream, because TCP guarantees ordering across the whole connection and doesn't know your streams exist. QUIC moves the ordering guarantee down to each stream, so a lost packet for the stylesheet doesn't hold up the image.\n\nThe handshake is merged. TCP does its handshake, then TLS does another one on top. QUIC combines them, so a new connection is one round trip instead of two or three, and a resumed one can be zero. On a mobile connection where a round trip is 80 milliseconds, that is the difference people actually feel.\n\nIt lives in userspace. TCP is implemented in the kernel, so improvements ship on the operating system's schedule, which is measured in years. QUIC ships with the browser and the server, so congestion control changes roll out in weeks.\n\nThere is a real cost: more CPU per byte, and middleboxes that don't understand it. But the design is a genuine response to TCP's specific constraints rather than a reimplementation of them.")],
 [("user","I want to get properly into bread baking. Explain what's actually happening chemically, and then give me a first loaf to try."),
  ("assistant","Four processes overlap, and understanding which one you're in tells you what to do next.\n\nHydration and gluten formation. Flour has two proteins, glutenin and gliadin, which are inert until water arrives. Mixing lets them link into gluten, a network that is elastic from the glutenin and extensible from the gliadin. Kneading speeds this up, but time does it for free - which is why no-knead recipes work at all.\n\nFermentation. Yeast eats simple sugars and produces carbon dioxide and ethanol. The carbon dioxide inflates bubbles already trapped in the gluten network; it does not create new ones, which is why how you shape the dough determines the crumb. Bacteria present in a sourdough culture also produce lactic and acetic acid, which is the flavour and also strengthens the gluten up to a point and degrades it past that.\n\nThe bake. In the first ten minutes the trapped gas expands and the alcohol boils off, giving oven spring. Then starch gelatinises and protein sets, and the loaf stops growing - everything after that is drying and colour.\n\nColour. Maillard browning between sugars and amino acids at the crust, plus caramelisation. Steam early keeps the crust flexible so oven spring can happen; no steam and you set the crust before the loaf has finished rising.\n\nFor a first loaf: 500g strong white flour, 350g water, 10g salt, 5g instant yeast. Mix, rest 30 minutes, fold four times over two hours, shape, prove an hour, bake at 240C in a covered casserole for 20 minutes and 20 more uncovered."),
  ("user","Mine came out dense with a thick pale crust. What went wrong?"),
  ("assistant","Those two symptoms usually have one shared cause and one separate one.\n\nDense almost always means underproved, not overproved, in a first loaf. People are told to fear overproving and stop early. The test is the poke: press a floured finger into the shaped dough about a centimetre. If it springs straight back, it needs longer. If it springs back slowly and leaves a dent, bake it. If it doesn't spring back at all, you've gone too far. Dough proves on temperature, not on the clock, and a cold kitchen can easily double the times in a recipe.\n\nA pale thick crust is a heat and steam problem. Two likely culprits: your oven is running cooler than it claims, which is extremely common - an oven thermometer costs very little and about half of home ovens are off by 15 to 20 degrees; and the casserole wasn't preheated, so the loaf spent its first minutes warming the pot instead of springing.\n\nThe fix for both is one change each. Preheat the casserole for a full 30 minutes at 240C, and prove by feel rather than by time. If it's still pale after that, leave it uncovered five minutes longer than feels right - most home bakers pull bread out at least five minutes early, and the crust colour you want looks alarming the first time.")],
 [("user","Write a short story opening, about 200 words, where the twist is that the narrator is a house."),
  ("assistant","They arrived in April, which is when I am at my best. The wisteria was doing the thing it does, and the morning light came through the landing window at the angle that makes the whole stairwell look like it was designed by someone competent, which it was not.\n\nShe walked the rooms with her hand out, not quite touching. He talked about the boiler.\n\nI have had eleven families. The Prescotts painted over the picture rail and I have never entirely forgiven them. The couple after that left in the winter, separately, and I held the cold for three months because nobody thought to bleed the radiators. I don't mind an empty season. It is the arguing I find hard, the way a raised voice moves through my walls and comes out somewhere else entirely, in a room where a child is pretending to sleep.\n\nShe stopped at the bottom of the stairs and put her palm flat against the newel post, the way you'd greet a horse.\n\n\"This one,\" she said.\n\nHe said something about the survey.\n\nI settled a little in my joists, which he heard, and blamed on the pipes."),
  ("user","Now rewrite it so the twist lands at the very end instead of being obvious from the start."),
  ("assistant","They arrived in April, which is when the wisteria does the thing it does, and the morning light comes through the landing window at an angle that makes the stairwell look designed by someone competent.\n\nShe walked the rooms with her hand out, not quite touching. He talked about the boiler.\n\nThere had been eleven families before them. The Prescotts painted over the picture rail, which was unforgivable. The couple after that left in the winter, separately, and nobody thought to bleed the radiators, so the cold sat in the walls until March.\n\nAn empty season is bearable. It is the arguing that's hard - the way a raised voice travels and comes out somewhere else entirely, in a room where a child is pretending to sleep.\n\nShe stopped at the bottom of the stairs and put her palm flat against the newel post, the way you'd greet a horse.\n\n\"This one,\" she said.\n\nHe said something about the survey, and about how old places settle.\n\nI settled, a little, in my joists.\n\nHe blamed the pipes.")],
 [("user","Solve this and show your reasoning: a train leaves A at 9am at 60 km/h, another leaves B at 10am at 90 km/h toward A. A and B are 420 km apart. When do they meet?"),
  ("assistant","Set it up as distance remaining when the second train starts.\n\nFrom 9am to 10am only the first train moves, at 60 km/h for one hour, so it covers 60 km. The gap between them at 10am is 420 minus 60, which is 360 km.\n\nFrom 10am they close on each other, so the closing speed is the sum: 60 plus 90 equals 150 km/h.\n\nTime to close 360 km at 150 km/h is 360 divided by 150, which is 2.4 hours - two hours and 24 minutes.\n\nSo they meet at 12:24pm.\n\nA quick sanity check on the position: the first train has been running 3.4 hours at 60, which is 204 km from A. The second has run 2.4 hours at 90, which is 216 km from B. 204 plus 216 equals 420. It closes."),
  ("user","What if the second train had left at 8am instead, an hour before the first?"),
  ("assistant","Same method, mirrored, with one thing worth checking at the end.\n\nFrom 8am to 9am only the second train moves, at 90 km/h, so it covers 90 km and the gap becomes 420 minus 90, which is 330 km.\n\nFrom 9am the closing speed is again 150 km/h. Time to close 330 km is 330 divided by 150, which is 2.2 hours - two hours and 12 minutes.\n\nSo they meet at 11:12am.\n\nPositions: the first train has run 2.2 hours at 60, so 132 km from A. The second has run 3.2 hours at 90, so 288 km from B. 132 plus 288 equals 420, which checks.\n\nThe thing worth noticing: the meeting point has moved 72 km closer to A, because the faster train got a head start. If the second train had left early enough - about 4 hours and 40 minutes early - it would reach A before the first train left at all, and the question would stop having an answer of this shape.")],
]
